### ISSUE TITLE
Tray icon missing in KDE Plasma

### ISSUE THREAD

**Issue by SinTan1729** [Martchus/syncthingtray#100]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.1.8-1, 6.4.2-1, 5.10.5-1
* Qt version: 5.15.2
* Operating system (name and version): Manjaro

**Bug description**
The tray icon is not appearing.

**Steps to reproduce**
1. Launch the app.

**Expected behavior**
Tray icon should appear.

**Comment by Martchus** [comment]
I cannot reproduce. Since you're using Manjaro I would guess it is the same problem as https://github.com/Martchus/syncthingtray/issues/98.

**Comment by SinTan1729** [comment]
Recompiling manually using `makepkg` solved the issue.

**Comment by Martchus** [comment]
Then it was just the same issue.
