### ISSUE TITLE
Crash with SIGBUS

### ISSUE THREAD

**Issue by mpartel** [Martchus/syncthingtray#102]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.1.8, 6.4.2, 5.10.5
* Qt version: 5.6.2
* C++ compiler (name and version): <using AppImage>
* C++ standard library (name and version): <not sure which one it links against on Ubuntu 20.04>
* Operating system (name and version): Ubuntu 20.04

**Bug description**

After running for some time, it crashes with a SIGBUS.

Stacktrace as recorded by systemd-coredump:

```
                #0  0x00007f752afea134 strcmp (ld-linux-x86-64.so.2 + 0x20134)
                #1  0x00007f752afd5395 check_match (ld-linux-x86-64.so.2 + 0xb395)
                #2  0x00007f752afd588a do_lookup_x (ld-linux-x86-64.so.2 + 0xb88a)
                #3  0x00007f752afd61e9 _dl_lookup_symbol_x (ld-linux-x86-64.so.2 + 0xc1e9)
                #4  0x00007f752afdb187 _dl_fixup (ld-linux-x86-64.so.2 + 0x11187)
                #5  0x00007f752afe2c2e _dl_runtime_resolve_xsavec (ld-linux-x86-64.so.2 + 0x18c2e)
                #6  0x00000000004cbc3e n/a (/usr/bin/syncthingtray + 0xcbc3e)
```

Stdout+stderr:

```
QObject::connect: Cannot queue arguments of type 'QProcess::ProcessState'
(Make sure 'QProcess::ProcessState' is registered using qRegisterMetaType().)
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
Bus error (core dumped)
```
(The first three lines appear immediately, bu the bus error takes a long time to happen)

**Steps to reproduce**
1. Run it for some time. I wish I knew more.

**Additional context**

I run it under KDE. It's configured to autostart and autoconnect to syncthing (1.18.0).

This *may* happen during (long?) computer suspends. I'll try to keep an eye on it.

**Comment by Martchus** [comment]
Hard to tell why this is happening. The QObject error is likely not related to the crash.

Note that your Qt version is very old. It would also be good to know how you configured your build.

If you were using the AppImage then I recommend to use a proper build instead. (The AppImage is more for trying it out than for using it permanently due to the old libraries which are bundled within.)

**Comment by Martchus** [comment]
I'm not going to look into crashes with unsupported Qt versions.
