### ISSUE TITLE
[Linux] v1.1.8-1 test cases fail

### ISSUE THREAD

**Issue by brackenhill-mob** [Martchus/syncthingtray#105]
Compiling v1.1.8-1 on Arch on 3 PCs and they all throw the same error. It won't connect to the server when executing the test cases. The beginning part of the output is

<pre>
1: Executing test cases ...
1: .
1:  - Setup configuration for Syncthing tests ...
1:  - Using timeout factor 3
1: 
1:  - Launching Syncthing: syncthing -gui-address=http://localhost:65380 -gui-apikey=syncthingtestinstance -home=/tmp/aurbuilder/.cache/yay/syncthingtray-qt6/src/syncthingtray-1.1.9/connector/testfiles/workingdir/testconfig -no-browser -verbose
1: Info: Launched process, PID: 38376
1: 
1:  - Preparing connection ...
1: 
1:  - Error handling in case of insufficient conficuration ...
1:  - Connection error: Connection configuration is insufficient.
1: 
1:  - Error handling in case of inavailability ...
1:  - Connection error: Unable to request Syncthing config: Connection refused
1:  - Connection error: Unable to request Syncthing status: Connection refused
1: [start] 07:54:39 INFO: syncthing v1.18.1 "Fermium Flea" (go1.16.6 linux-amd64) builduser@archlinux 2021-08-05 18:53:57 UTC [noupgrade]
1: [start] 07:54:39 INFO: Generating ECDSA key and certificate for syncthing...
1: [start] 07:54:39 INFO: Archiving a copy of old config file format at: /tmp/aurbuilder/.cache/yay/syncthingtray-qt6/src/syncthingtray-1.1.9/connector/testfiles/workingdir/testconfig/config.xml.v28
1: [DQBJD] 07:54:39 INFO: My ID: DQBJDXS-LDC5ILQ-24RTI3K-BXQXXDJ-CGPA4SV-XQMNSQU-BOHLUAM-G3HSWAS
1:  - Connection error: Unable to request Syncthing config: Connection refused
1:  - Connection error: Unable to request Syncthing status: Connection refused
1: [DQBJD] 07:54:40 INFO: Single thread SHA256 performance is 2059 MB/s using minio/sha256-simd (502 MB/s using crypto/sha256).
1: [DQBJD] 07:54:40 VERBOSE: Starting up (/tmp/aurbuilder/.cache/yay/syncthingtray-qt6/src/syncthingtray-1.1.9/connector/testfiles/workingdir/testconfig)
1:  - Connection error: Unable to request Syncthing config: Connection refused
1:  - Connection error: Unable to request Syncthing status: Connection refused
1: [DQBJD] 07:54:40 INFO: Hashing performance is 1229.17 MB/s
1: [DQBJD] 07:54:40 INFO: Running database migration 1...
1: [DQBJD] 07:54:40 INFO: Running database migration 2...
1: [DQBJD] 07:54:40 INFO: Running database migration 3...
1: [DQBJD] 07:54:40 INFO: Running database migration 5...
1: [DQBJD] 07:54:40 INFO: Running database migration 6...
1: [DQBJD] 07:54:40 INFO: Running database migration 7...
1: [DQBJD] 07:54:40 INFO: Running database migration 9...
1: [DQBJD] 07:54:40 INFO: Running database migration 10...
1: [DQBJD] 07:54:40 INFO: Running database migration 11...
1: [DQBJD] 07:54:40 INFO: Running database migration 13...
1: [DQBJD] 07:54:40 INFO: Running database migration 14...
1: [DQBJD] 07:54:40 INFO: Running database migration 16...
1: [DQBJD] 07:54:40 INFO: Running database migration 17...
1: [DQBJD] 07:54:40 INFO: Running database migration 19...
1: [DQBJD] 07:54:40 INFO: Compacting database after migration...
1: [DQBJD] 07:54:40 INFO: Overall send rate is unlimited, receive rate is unlimited
1: [DQBJD] 07:54:40 INFO: No stored folder metadata for "test1"; recalculating
1: [DQBJD] 07:54:40 INFO: Using discovery mechanism: global discovery server https://discovery.syncthing.net/v2/?noannounce&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
1: [DQBJD] 07:54:40 INFO: Using discovery mechanism: global discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
1: [DQBJD] 07:54:40 INFO: Using discovery mechanism: global discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
1: [DQBJD] 07:54:40 INFO: Using discovery mechanism: IPv4 local broadcast discovery on port 21027
1: [DQBJD] 07:54:40 INFO: Using discovery mechanism: IPv6 local multicast discovery on address [ff12::8384]:21027
1: [DQBJD] 07:54:40 INFO: Ready to synchronize test1 (sendreceive)
1: [DQBJD] 07:54:40 INFO: Loading HTTPS certificate: open /tmp/aurbuilder/.cache/yay/syncthingtray-qt6/src/syncthingtray-1.1.9/connector/testfiles/workingdir/testconfig/https-cert.pem: no such file or directory
1: [DQBJD] 07:54:40 INFO: Creating new HTTPS certificate
1: [DQBJD] 07:54:40 VERBOSE: Folder "test1" is now scan-waiting
1: [DQBJD] 07:54:40 VERBOSE: Folder "test1" is now scanning
1: [DQBJD] 07:54:40 INFO: Completed initial scan of sendreceive folder test1
1: [DQBJD] 07:54:40 VERBOSE: Folder "test1" is now idle
1: [DQBJD] 07:54:40 INFO: Listen (BEP/tcp): lookup localhost on 8.8.8.8:53: no such host
1: [DQBJD] 07:54:40 INFO: listenerSupervisor@tcp://localhost:32452: service tcp://localhost:32452 failed: lookup localhost on 8.8.8.8:53: no such host
1: [DQBJD] 07:54:40 INFO: Listen (BEP/tcp): lookup localhost on 8.8.8.8:53: no such host
1: [DQBJD] 07:54:40 INFO: listenerSupervisor@tcp://localhost:32452: service tcp://localhost:32452 failed: lookup localhost on 8.8.8.8:53: no such host
1: [DQBJD] 07:54:40 VERBOSE: Discovered device CLRH527-OI6LKKO-P3NULLR-WJEP7RV-5FUCC6N-5RVOGI4-XP5XG5K-RWADPQK at [tcp://[fe80::3547:2201:f24d:b181%25enp5s0]:22000 tcp://10.0.1.11:22000 tcp://[fe80::3547:2201:f24d:b181%25enp5s0]:0 relay://45.14.233.128:22067/?id=V2T4PS5-FYCFHSO-SVTIOEW-WXHZLHM-ATL4CWK-ZQCJ6LE-W54T7UA-SOFBOQ2&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=vidister quic://[fe80::3547:2201:f24d:b181%25enp5s0]:22000 quic://10.0.1.11:22000 quic://81.174.132.17:22000]
1: [DQBJD] 07:54:40 INFO: Listen (BEP/tcp): lookup localhost on 8.8.8.8:53: no such host
1: [DQBJD] 07:54:40 INFO: listenerSupervisor@tcp://localhost:32452: service tcp://localhost:32452 failed: lookup localhost on 8.8.8.8:53: no such host
1: [DQBJD] 07:54:40 WARNING: Failed starting API: listen tcp: lookup localhost on 8.8.8.8:53: no such host
1: [DQBJD] 07:54:40 WARNING: Starting API/GUI: listen tcp: lookup localhost on 8.8.8.8:53: no such host
1: [DQBJD] 07:54:40 INFO: Exiting
1: [monitor] 07:54:40 INFO: Syncthing exited: exit status 1
1:  - Connection error: Unable to request Syncthing config: Connection refused
</pre>

The interesting part is
<pre>
1:  - Error handling in case of insufficient conficuration ...
1:  - Connection error: Connection configuration is insufficient.
</pre>

a) there is a minor typo "conficuration" should be configuration and b) there is no hint as to what the insufficient configuration might be so I can't fix it!

HTH

**Comment by Martchus** [comment]
Please try again with v1.1.9 as I cannot support older versions and there should be no need to stick with v1.1.8.

Regardless of that I'm afraid that  I cannot reproduce the problem with any version, see my build logs attached. Note that (beside the typo) there's nothing wrong with the output "Connection error: Connection configuration is insufficient.". The test simply tests whether it behaves as expected  in this particular error case which is logged accordingly.

I suppose the real error is `1: [DQBJD] 07:54:40 WARNING: Starting API/GUI: listen tcp: lookup localhost on 8.8.8.8:53: no such host`. This log line comes from Syncthing itself (the test launches a test instance) which apparently fails to do the DNS lookup for `localhost`.

---

[syncthingtray-qt6-1.1.8-1-x86_64-build.log](https://github.com/Martchus/syncthingtray/files/6949196/syncthingtray-qt6-1.1.8-1-x86_64-build.log)
[syncthingtray-qt6-1.1.8-1-x86_64-check.log](https://github.com/Martchus/syncthingtray/files/6949197/syncthingtray-qt6-1.1.8-1-x86_64-check.log)
[syncthingtray-qt6-1.1.8-1-x86_64-package.log](https://github.com/Martchus/syncthingtray/files/6949198/syncthingtray-qt6-1.1.8-1-x86_64-package.log)
[syncthingtray-qt6-1.1.9-1-x86_64-build.log](https://github.com/Martchus/syncthingtray/files/6949199/syncthingtray-qt6-1.1.9-1-x86_64-build.log)
[syncthingtray-qt6-1.1.9-1-x86_64-check.log](https://github.com/Martchus/syncthingtray/files/6949200/syncthingtray-qt6-1.1.9-1-x86_64-check.log)
[syncthingtray-qt6-1.1.9-1-x86_64-package.log](https://github.com/Martchus/syncthingtray/files/6949201/syncthingtray-qt6-1.1.9-1-x86_64-package.log)

**Comment by Martchus** [comment]
Can you apply the following patch to see whether it helps? https://github.com/Martchus/syncthingtray/commit/321bac0bf762d45e6e0b2d776450900c8e018084.patch

**Comment by brackenhill-mob** [comment]
v1.1.19-1 just dropped on my boxes. Same issue as before.

Applied your patch (also changed all localhost lines in misctest.cpp to be sure) and now all tests passed and app installed.

Thanks

**Comment by Martchus** [comment]
Thanks, then I'll merge that branch on master. However, if changing `localhost` to `127.0.0.1` helps (which is all the patch does), that means the DNS setup in your build environment is somewhat broken.
