### ISSUE TITLE
[Linux] Launcher argument '-no-console' doesn't exist/work on Linux and causes it to fail

### ISSUE THREAD

**Issue by newtant** [Martchus/syncthingtray#106]
**Relevant components**
* [X] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.1.9.-1, 6.5.0-1, 5.11.0-1
* Qt version: 5.….…
* C++ compiler (name and version): …
* C++ standard library (name and version): …
* Operating system (name and version): …

**Bug description**
Syncthing Tray -> Settings -> Startup -> Syncthing launcher

The automatically populated arguments include '-no-console' which, according to `man syncthing`, doesn't exist/work on Linux and causes the automated launch of Syncthing to fail with `syncthing: error: unknown flag --no-console`.

**Steps to reproduce**
1. Activate the "Launch Syncthing when starting the tray icon" option on Linux
2. Observe if '-no-console' has been added to the list of arguments by default
3. Relaunch the program or reboot the machine
4. Check if Syncthing has been successfully started
5. If not check the logs

**Expected behavior**
Syncthing is successfully started when starting the tray icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/2772806/130223474-db4de6d7-ab1f-45a6-8c2d-2ca4973e593a.png)

**Additional context**
The Syncthing error message itself weirdly contains an additional hyphen which isn't present during input nor a valid argument according to its manpage.

**Comment by Martchus** [comment]
These are just suggested defaults, you can always replace them with whatever you want. Of course it makes sense to omit `-no-console` on any platforms other than Windows (like the `.exe` suffix of the default executable name is omitted).

**Comment by Martchus** [comment]
I changed the default arguments so this should be fixed in the next release. You likely won't see a difference when you've already launched Syncthing Tray because existing settings are not replaced.

**Comment by newtant** [comment]
Thank you, and absolutely, I get that these are just suggested defaults. I didn't write this bug report to get a fix for the problem on _my_ end, I obviously did take care of that myself already, I opened this issue because I think the defaults should work for most users.

Thanks again!

**Comment by Martchus** [comment]
The change will be part of the next release so I'm closing this issue.
