### ISSUE TITLE
Flag for not creating console window on Windows

### ISSUE THREAD

**Issue by sledgehammer999** [Martchus/syncthingtray#108]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: latest
* Qt version: 5.….…
* C++ compiler (name and version): …
* C++ standard library (name and version): …
* Operating system (name and version): windows 7 and windows 10

**Bug description**
On Windows even if you use `-no-console` the OS still creates a console window for syncthing when it is launched, which afterwards syncthing deallocates due to the above switch. Aka there is a very brief period where the user sees a black console window.
However, the launching process (aka syncthingtray) can indicate to the OS to not create a console window at all.
So in your `boost::process::child()` you just have to pass [boost::process::windows::create_no_window](https://www.boost.org/doc/libs/1_77_0/doc/html/boost/process/windows/create_no_window.html)

I have tested it locally with a test program and it works with syncthing.

**Comment by Martchus** [comment]
It is very strange that I cannot reproduce this issue with `-no-console`. However, I suppose passing the boost argument cannot hurt so I'll add it.

**Comment by sledgehammer999** [comment]
>It is very strange that I cannot reproduce this issue with -no-console.

If your system is very fast(eg SSD) or under no load you won't notice. It is just a flicker on launch. I notice it more often on user logon because there are other things loading concurrently with syncthing and things get slowed a bit in those first seconds.

**Comment by Martchus** [comment]
That could be the case, indeed.

---

I added the flag on master. I'll test it tomorrow under Windows, here's a build if you like to test it: https://martchus.no-ip.biz/repo/experimental/win/syncthingtray-b828d7c27491b373faf58b5c239338f6529e335b.exe

**Comment by Martchus** [comment]
> I have tested it locally with a test program and it works with syncthing.

So I'm confident it works although I couldn't reproduce the issue myself. Of course you can reopen the issue if it didn't work after all.
