### ISSUE TITLE
Option to autolaunch "syncthing" crashes "syncthingtray"

### ISSUE THREAD

**Issue by maguilara** [Martchus/syncthingtray#109]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries 

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.1.10-1, 6.5.0-1, 5.11.1-1
* Qt version: qt5-base 5.15.2+kde+r222-2 (qt qt5)
* C++ compiler (name and version):  gcc 11.1.0-1 (base-devel)
* C++ standard library (name and version): gcc-libs 11.1.0-1 (this is the correct package, right?)
* Operating system (name and version): Arch Linux 

**Bug description**
Launching the SyncthingTray from the menu fails. 

**Steps to reproduce**
1. Launch syncthingtray from the menu/icon

**Expected behavior**
Launching syncthingtray should make appear the syncthing tray icon and launch syncthing too (syncthingtray handles the syncthing process)

**Screenshots**
N/A

**Additional context**
When launching via the menu, for a brief moment appears the syncthing icon on my taskbar, as if the web GUI had been requested, and then it dissapears and STT fails to launch. Launching via the terminal, syncthingtray works fine, and the previous behaviuor does not happen. Only output I get from launching via the terminal is:
```
Info: Launched process, PID: 92382
Icon theme "gnome" not found.
```
Not sure how to get output when launching it via the menu.

EDIT: Okay, when launching via the terminal and keeping that one alive, if I try to open another instance of STT via the menu, it works. And I can keep opening multiple instances. BTW, the behaviour of the ST icon appearing briefly in the taskbar keeps happening when launching via the menu.

**Comment by Martchus** [comment]
> Not sure how to get output when launching it via the menu.

You can launch the "menu" (whatever process it is, possible the graphical shell you're using) manually from a terminal. A stacktrace (e.g. obtained via `coredumpctl`) would be helpful as well.

**Comment by maguilara** [comment]
First time installing STT, so no baseline. I'm using KDE. I refer to menu to the "Application launcher" widget found on KDE.  When it failed I tried to customize the .desktop file adding the ampersand symbol, because why not, didn't work either and reverted to the original config (which is simply 'syncthingtray'). Can't say nothing about the qt6, will try to give it a try. I deleted the config and it worked fine, so I have isolated the issue that when it tries to autolaunch syncthing, it's not able to do so and fails. I'll try to get the stacktrace.

**Comment by maguilara** [comment]
Here is the output I got from using the following command: `coredumpctl debug --debugger-arguments="-batch -ex 'info all-registers'"
`, following the manpage for it. Let me know if this is correct.
[https://pastebin.com/1WkG7iy9](https://pastebin.com/1WkG7iy9)

**Comment by Martchus** [comment]
Judging by the stack trace, the C++ standard library fails to create a locale. It looks like the locale isn't setup correctly on your machine. Did you follow https://wiki.archlinux.org/title/Locale#Generating_locales ?

**Comment by maguilara** [comment]
Sorry, forgot to mention that when launching from console it does work, crash only happens when launched "standalone" via *.desktop file (?) Not sure what's the correct term. But it doesn't happen because my .zshrc file has set the LC_ALL/LC_LANG environmental variable, when I commented those bits (I think I added them for a similar issue with other programs), it now fails when launching from shell with the error you indicate. Plasma also adds their own LC_ related envs from .config/plasma-localerc, deleted those just in case and rebooted. Now it works. But I see a new aesthetic (?) bug, an orphan plasmoid appears on the system tray even when STT hasn't been initialized yet. If I start STT, another plasmoid appears which is linked to the stt process. Should I open a new issue?

**Comment by Martchus** [comment]
> an orphan plasmoid appears on the system tray even when STT hasn't been initialized yet. Is this a knows issue?

I'm not exactly sure what you mean but I'm aware that sometimes the Plasmoid shows up as part of the system tray Plasmoid and one has to disable it there manually again. That seems to be a limitation of Plasma, though.

---

Good that we could pin down the issue. I guess you're not the first user hit by this issue. I remember one had problems running tests because the build environment lacked the correct locale setup. It would be good if one would get a warning instead of a hard crash and if it would just fallback to the "C" locale which should hopefully always work. Not sure whether that would be possible but I suppose I could check out that possibility.

**Comment by maguilara** [comment]
> I'm not exactly sure what you mean but I'm aware that sometimes the Plasmoid shows up as part of the system tray Plasmoid and one has to disable it there manually again. That seems to be a limitation of Plasma, though.

I'll open a new issue then, just in case someone else experiences it too.

> It would be good if one would get a warning instead of a hard crash and if it would just fallback to the "C" locale which should hopefully always work. Not sure whether that would be possible but I suppose I could check out that possibility.

 That seems the most sensible choice, but it's a common failure not being able to default to a locale. Not sure why.

**Comment by Martchus** [comment]
It doesn't look like you've created a new issue but the unhandled exception should be fixed by https://github.com/Martchus/syncthingtray/commit/239d75134221aae1edd08ac6eac2f6d25402184c.
