### ISSUE TITLE
Invisible buttons in the tray interface

### ISSUE THREAD

**Issue by cyqsimon** [Martchus/syncthingtray#117]
Apologies beforehand for the lacklustre information I may be providing. I'm really not sure where to even start in diagnosing this issue - nothing I did caused any change in application behaviour. Feel free to drill me for any additional information you may want.

**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* `syncthingtray`: 1.1.12, `qtutilities`: 6.5.2, `c++utilities`: 5.11.3
* Qt version: 6.2.0
* C++ compiler (name and version): gcc (GCC) 11.1.0
* C++ standard library (name and version): Sry not sure how to check this, not a C++ dev
* Operating system (name and version): Linux 5.4.150-1-MANJARO x86_64

**Bug description**
Buttons not visible in the tray interface; see screenshot

**Steps to reproduce**
1. Install `syncthingtray-qt6` via AUR and launch with no args
2. Left click the tray icon

**Expected behavior**
Interface buttons visible

**Screenshots**
![shot-20211104-033055](https://user-images.githubusercontent.com/28627918/140181886-ffde31b2-5406-46b5-b6cc-ed39ab7a26c6.png)

**Additional context**
 - The buttons **are there** and respond to clicks; if I hover with the cursor, the tooltip also pops up. It's just they're completely invisible.
 - I have tried to use alternate icons/theme/etc., via system settings, `syncthingtray-qt6` CLI args, and syncthingtray GUI settings. Nothing I did had any effect.

**Comment by Martchus** [comment]
Looks like the icon engine plugin is installed into the wrong directory for the Qt 6 version. I'll fix that. As a workaround you can use the Qt 5 version in the meantime.

**Comment by Martchus** [comment]
This should be fixed in the latest version of the `qtforkawesome-qt6` package.

**Comment by cyqsimon** [comment]
Thank you! Confirmed fixed after updating `qtforkawesome-qt6` and restarting `syncthingtray-qt6`.
