### ISSUE TITLE
Icons missing in widgets and menus on Gentoo

### ISSUE THREAD

**Issue by CaseOf** [Martchus/syncthingtray#122]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.1.13, 6.5.3, 5.11.3
* Qt version: 5.15.2
* C++ compiler (name and version): gcc 11.2.0
* C++ standard library (name and version): gcc 11.2.0
* Operating system (name and version): Gentoo 17.1

**Bug description**

I am building syncthingtray from my own Gentoo’s ebuilds from my overlay:
https://framagit.org/Case_Of/gentoo-overlay/-/blob/master/x11-plugins/syncthingtray/syncthingtray-1.1.13.ebuild
Since version 1.1.13, some icons are missing on widgets and on context menu.
I’m using XFCE desktop environment with Arc Dark theme provided to Qt with qt5ct and qtstyleplugins.

**Steps to reproduce**
1. On Gentoo system, install syncthingtray 1.1.13 from my overlay
2. Start syncthingtray

**Expected behavior**

Missing icons should be shown.

**Screenshots**
![Screenshot of the widget](https://i.imgur.com/8UT7GHy.png)
![Screenshot of the context menu](https://i.imgur.com/P35F1mT.png)
**Additional context**
If you find any mistakes in my build process, dont hesitate to tell me.

**Comment by Martchus** [comment]
These icons should be provided by qtforkawesome. There's likely a packaging issue. You've configured it to use the woff2 icon file. This won't work if freetype2 isn't configured with brotli support (see https://github.com/Martchus/qtforkawesome/#providing-the-font-file). It could also be that the icon engine plugin from the qtforkawesome package cannot be located at runtime. It should be installed under the same directory as Qt's SVG icon plugin.

**Comment by CaseOf** [comment]
Hi,
I just rebuilt freetype with brotli support via its use flag, and now icons are shown.
I’ll fix the dependency in my ebuild then.

**Comment by Martchus** [comment]
Glad to hear it was that simple. By the way, it would make sense to mention your packages in the download section of the README.
