### ISSUE TITLE
AUR syncthingtray-lite seems to be looking for the wrong version of qtforkawesome

### ISSUE THREAD

**Issue by jeremiah-miller** [Martchus/syncthingtray#123]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [x] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.1.11-1, 6.5.2-1, 5.11.3-1
* Qt version: 5.15.2+kde+r268-1
* C++ compiler (name and version): gcc version 11.1.0
* C++ standard library (name and version): gcc version 11.1.0
* Operating system (name and version): Manjaro 21.2.0 Qonos

**Bug description/Steps to reproduce**
```
~ $ syncthingtray
syncthingtray: error while loading shared libraries: libqtforkawesome.so.0.0.1: cannot open shared object file: No such file or directory
~ $ ls /lib | grep qtfork
libqtforkawesome.so -> libqtforkawesome.so.0.0.2*
libqtforkawesome.so.0.0.2*
```

**Expected behavior**
Syncthingtray to launch and run

**Comment by Martchus** [comment]
Just rebuild Syncthing Tray. Note that the litter package is outdated and not maintained by myself. I recommend to use packages provided by me or updating the lite package first.

**Comment by jeremiah-miller** [comment]
Oh nice, that fixed it. Thanks!
