### ISSUE TITLE
Syncthing menu becomes partly transparent and black when hovering over title bar.

### ISSUE THREAD

**Issue by gohanko** [Martchus/syncthingtray#124]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)

**Environment and versions**
* Qt version: 5.15.2
* Syncthing Tray: 1.1.5
* Operating system: Fedora 35
* Gnome version: 41.3
* Windowing System: Wayland

**Bug description**
Syncthing menu becomes partly transparent and black when hovering over title bar.

**Steps to reproduce**
1. Open the Syncthing Tray menu by clicking "Open Syncthing"
2. Hover over the minimize/maximize and exit button

**Expected behavior**
Hovering over title bar should make the window partly transparent and black.

**Screenshots**
https://user-images.githubusercontent.com/26451183/149661826-279f112f-76bd-47ce-b9c5-ef82cdc3adf5.mp4

**Comment by Martchus** [comment]
This seems to be really specific to your environment because under KDE (X11 or Wayland) I haven't seen this problem so far. Maybe a bug of GNOME's Wayland compositor or a bug of Qt WebEngine which only occurs in certain environments. It could of course also be a problem of the way I use Qt WebEngine but it seems quite unlikely. Did it work at some point before? I haven't done any significant changes in the web view code. If it worked before then likely an update of GNOME or Qt WebEngine broke it.

**Comment by Martchus** [comment]
By the way, you're using a very outdated version of Syncthing Tray. I recommend updating to the latest version of it and its dependencies (although it likely won't fix this particular problem). I'm generally reluctant to reproduce bugs on older versions except for bisecting regressions.

**Comment by gohanko** [comment]
Hi Martchus, this has always been the problem ever since I started using syncthingtray half a year ago, and I think it occurred on Fedora 34 as well. 

And on the outdated version of it, I will try to update it. I actually never checked which version of syncthingtray is the latest as I only followed your install documentation. 

Is it possible for you to add a Fedora 34 and Fedora 35 syncthingtray and the latest versions to your opensuse repository?

https://software.opensuse.org/download.html?project=home:mkittler&package=syncthingtray

**Comment by Martchus** [comment]
> Hi Martchus, this has always been the problem ever since I started using syncthingtray half a year ago, and I think it occurred on Fedora 34 as well.

Ok, maybe I can try it out myself on GNOME/Wayland at some point but still it is likely that it is not a problem of Syncthing Tray itself.

> Is it possible for you to add a Fedora 34 and Fedora 35 syncthingtray and the latest versions to your opensuse repository?

There are repositories for Fedora 34 and 35 - it is just that the "fancy" `https://software.opensuse.org/download.html?…` page doesn't show them, see https://download.opensuse.org/repositories/home:/mkittler/ instead.

> Edit: When I looked close, seems like dnf is downloading the 1.1.5 version as oppose to the 1.1.14 one even though it is available. Not quite sure why.

I don't use dnf myself but some reasons come to my mind: package locked, repository update disabled, the new package would leave something unresolvable

**Comment by gohanko** [comment]
Seems like the dependency is broken because `libsyncthingconnector` requires `libboost_filesystem` version 1.75 but the system has 1.76 instead. If I have time I will try to see if I can install version 1.75 of `libboost_filesystem` but I wonder if updating the dependency version and recompiling it would fix the broken dependency issue. 

I'm assuming this is broken because Fedora 35 ship with a newer version of the dependency whereas previously there wasn't any broken dependency errors due to previous version of Fedora shipping the exact required version of that library?

![Screenshot from 2022-01-20 00-49-36](https://user-images.githubusercontent.com/26451183/150176841-53c6edb8-9613-4fb0-8aed-6beb7ba66fef.png)

I've never developed and packaged an app for linux so please bear with me.

**Comment by Martchus** [comment]
Are you sure you're using the right repository for your Fedora version (and not a repository meant for an older Fedora version)?

**Comment by Martchus** [comment]
I've just downloaded https://download.opensuse.org/repositories/home:/mkittler/Fedora_35/x86_64/libsyncthingconnector1_1_14-1.1.14-1.1.x86_64.rpm and `readelf -d` tells me that the contained library `libsyncthingconnector.so.1.1.14` is linked against `libboost_filesystem.so.1.76.0`. So you must be using a wrong repository version. Note that when migrating to the next Fedora release you'll also have to take care of adjusting the repository URLs for 3rdparty repositories (as it is apparently not happening automatically in your workflow).

**Comment by gohanko** [comment]
Looking at the [install script](https://github.com/gohanko/dotfiles/blob/0ff129fe5a715083aef6d96f7846ba1664b1916d/.functions#L63) it indeed uses an older version of the repository. Updating it solved the update problem. Now it runs on 1.1.14.

However, the bug reported initially still occurs with the updated version.

**Comment by Martchus** [comment]
I've just tested it under a pristine GNOME 41.3 Wayland session with default settings and Qt 5.15.2+kde+r294 (Qt WebEngine is 5.15.8) and could *not* reproduce the issue. I also tested the Qt 6 build of Syncting Tray (which is *not* packaged for Fedora) with Qt 6 6.2.2 and couldn't reproduce the issue as well. So it looks like a Fedora/configuration-specific issue.

Apparently the standard GNOME desktop doesn't support system tray icons so I had to start Syncthing Tray via `--windowed`. What did you install to have a system tray area under GNOME (although it likely makes no difference here I'd be interested)?

**Comment by gohanko** [comment]
If that's the case, it's probably a Fedora specific issue I have this issue every time I reinstall my Fedora workstation and I've only used the `syncthingtray` on Fedora and Windows (which does not have this problem).

As for what I use to have the system tray, I'm using the [gnome appindicator](https://github.com/ubuntu/gnome-shell-extension-appindicator) extension.

I'm wondering how would one go about to debug this issue? If it were me I'd probably leave it since it's not a breaking bug.

**Comment by Martchus** [comment]
> I'm wondering how would one go about to debug this issue?

I would check whether other apps using Qt WebEngine are affected as well. I would also check whether switching between the Walyand and X11 session makes a difference. It could be that even the graphics driver makes a difference, e.g. NVIDIA's proprietary driver on Wayland might be problematic. I'd also try whether using different Qt platform abstraction plugins makes a difference. Not sure which one you're using but maybe a special one Fedora provides for better integration of Qt apps within GNOME (e.g. I'm aware of https://github.com/FedoraQt/adwaita-qt). Possibly there are also already issues filed in relevant upstream projects (Qt, GNOME, Fedora). But I'd likely not put that much effort into it as well.
