### ISSUE TITLE
issues in LICENSES-windows-distribution.md

### ISSUE THREAD

**Issue by sten0** [Martchus/syncthingtray#127]
Hi Martchus,

What version of GCC are you using the for Windows build?  GCC 4.2.1 was the last GPL2 version.  The GDFL license is exclusively used for documentation.  If there are other issues, I missed them in my quick scan.

Cheers,
Nicholas

**Comment by Martchus** [comment]
I'm using the latest version of GCC available at the time. So I suppose I'll have to regenerate LICENSES-windows-distribution.md (which is actually generated from licensing meta-data and files found in the corresponding Arch Linux packages). Maybe the license of `mingw-w64-gcc` was wrongly set there at the time of generating the licensing file.

> The GDFL license is exclusively used for documentation.

That might be the case but I suppose filtering licenses for parts of dependencies I don't use isn't worth the effort. The licensing document will be very lengthy anyways.

**Comment by sten0** [comment]
Martchus ***@***.***> writes:

> I'm using the latest version of GCC available at the time. So I suppose I'll have to regenerate LICENSES-windows-distribution.md (which is actually generated from licensing meta-data and files found in the corresponding Arch Linux packages). Maybe the license of `mingw-w64-gcc` was wrongly set there at the time of generating the licensing file.
>

Oh!  Yes, it sounds like this could be a bug in the Arch package, or
more likely mingw-w64-gcc, because GCC has been GPL-3+ since 2008, and
surely the GCC package Maintainer for Arch has reviewed the license
since 2007...  P.S. Debian is by far the strictest when it comes to
painstakingly documenting licenses.  Often painfully so ;-)

>> The GDFL license is exclusively used for documentation.
>
> That might be the case but I suppose filtering licenses for parts of dependencies I don't use isn't worth the effort. The licensing document will be very lengthy anyways.
>

I totally agree.  Maybe it would be possible (and easy) to change "GCC"
to "GCC (GPL for code, GFDL for docs, see licence for version)"?

**Comment by Martchus** [comment]
I updated the file. It now states GPL3 for GCC and since I had to make it a special case anyways I also removed the documentation license (as I don't redistribute its documentation).

**Comment by sten0** [comment]
Belated thank you!
