### ISSUE TITLE
Toolbar buttons padding seems not correct

### ISSUE THREAD

**Issue by mrpink17** [Martchus/syncthingtray#129]
**Relevant components**
* [x] Plasmoid/applet for Plasma desktop

**Environment and versions**
* syncthingtray 1.1.17
* qtutilities 6.6
* c++utilities 5.14
* Qt version: 5.15.13
* C++ compiler (name and version): gcc 11.2
* C++ standard library (name and version) glibc 2.35
* Operating system (name and version): KDE plasma 5.24.4

**Bug description**
It seems toolbar buttons padding is not correct

**Steps to reproduce**
Always

**Expected behavior**
Icons and text centered inside buttons

**Screenshots**
![01](https://user-images.githubusercontent.com/13852200/162027893-1b9babe9-e8af-45b1-bb77-36e138f381bf.png)

![02](https://user-images.githubusercontent.com/13852200/162027922-868ea666-9674-41b1-a15a-1439267bf085.png)

**Comment by Martchus** [comment]
The icons look smaller in your case. So I suppose that only happens when the icons sizes are configured to be smaller (than the default).

Note that glibc is *not* the C++ standard library; it is the C standard library. And KDE Plasma is also not an OS. However, I suppose that doesn't really matter for the sake of this issue. You're definitely running something recent enough.

**Comment by Martchus** [comment]
Where did you configure the icon size? I can only find the setting that affects normal applications but not Plasmoids.

**Comment by mrpink17** [comment]
I think I never changed any setting related to icons or font size. Looking at System Settings app it seems the settings are at their default values (no orange dots)

![image](https://user-images.githubusercontent.com/13852200/162286517-e77cffe1-9d94-489c-99b6-bec30b5ac7e1.png)

**Comment by Martchus** [comment]
I can also reproduce it with KDE plasma 5.24.4 and the default theme. Should be fixed via https://github.com/Martchus/syncthingtray/commit/329a928476016718111aa6c9826a2fb2f31b2fa5.
