### ISSUE TITLE
Show ID instead of name in Recent changes

### ISSUE THREAD

**Issue by giovEra** [Martchus/syncthingtray#130]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* OS: openSUSE Tumbleweed
* Repo: [latest releases for Tumbleweed](https://download.opensuse.org/repositories/home:/mkittler/openSUSE_Tumbleweed/)
* syncthingtray: 1.1.17
* Windowing System: X11
* Desktop Environment: KDE

**Bug description**
Releted to https://github.com/Martchus/syncthingtray/issues/115:  _Show name instead of ID in Recent changes_.
The "Recent changes" tab  display the ID of directory instead of name.

**Steps to reproduce**
1. Add a folder to syncthing
2. Inside the folder run ``touch {0..15}``

**Expected behavior**
The issue #115 has been close, so I expect that in the tab "Recent Changes" is display the name of directory instead of ID.
Note: In the settings I didn't find an option to choose whether to display ID or name of directories.

**Screenshots**
"Directories" tab:
[![directories.jpg](https://i.postimg.cc/Pq0gVgHg/directories.jpg)](https://postimg.cc/KKrpRsRf)

"Recent Changes" tab:
[![recent-changes.jpg](https://i.postimg.cc/vT43RBvX/recent-changes.jpg)](https://postimg.cc/H8CQXTR7)

**Comment by Martchus** [comment]
Implemented by https://github.com/Martchus/syncthingtray/commit/bc3cc22d60edc9b0bc0fbb41ee125efa87068c3a.

Note that I interpret "Show ID instead of name in Recent changes" as what's wrong and not as what I should do. It would make more sense to phrase it like #115 (for which I've only covered devices).
