### ISSUE TITLE
Disable ANSI escape codes automatically in environments which are known to not support it

### ISSUE THREAD

**Issue by tomasz1986** [Martchus/syncthingtray#132]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [x] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: syncthingctl v1.1.17
* Qt version: 6
* C++ compiler (name and version): N/A
* C++ standard library (name and version): N/A
* Operating system (name and version): Windows 10 21H2

**Bug description**

Result of running `syncthingctl --help`:

```
[1mSyncthing control (Qt 6), version 1.1.17

[0mCommand line app to control Syncthing

Available operations:
[1mstatus, -s[0m
  shows the overall status and/or directory/device specific status
  [1m--stats[0m
    shows overall statistics
  [1m--dir, -d[0m [ID]
    specifies a directory by ID
  [1m--dev[0m [ID/name]
    specifies a device by ID or name
  [1m--all-dirs[0m
    applies the operation for all directories
  [1m--all-devs[0m
    applies the operation for all devices

  example: syncthingctl status # shows all dirs and devs
           syncthingctl status --dir dir1 --dir dir2 --dev dev1 --dev dev2

[1mlog, -l[0m
  shows the Syncthing log

[1mstop[0m
  stops Syncthing

[1mrestart[0m
  restarts Syncthing

[1mrescan, -r[0m [dir ID] ...
  rescans the specified directories
  example: syncthingctl rescan dir1 dir2 dir4 dir5

[1mrescan-all[0m
  rescans all directories

[1mpause[0m
  pauses the specified directories and devices
  [1m--dir, -d[0m [ID]
    specifies a directory by ID
  [1m--dev[0m [ID/name]
    specifies a device by ID or name
  [1m--all-dirs[0m
    applies the operation for all directories
  [1m--all-devs[0m
    applies the operation for all devices

  example: syncthingctl pause --dir dir1 --dir dir2 --dev dev1 --dev dev2
           syncthingctl pause --all-dirs

[1mresume[0m
  resumes the specified directories and devices
  [1m--dir, -d[0m [ID]
    specifies a directory by ID
  [1m--dev[0m [ID/name]
    specifies a device by ID or name
  [1m--all-dirs[0m
    applies the operation for all directories
  [1m--all-devs[0m
    applies the operation for all devices

  example: syncthingctl resume --dir dir1 --dir dir2 --dev dev1 --dev dev2
           syncthingctl resume --all-devs

[1mwait-for-idle, -w[0m
  waits until the specified dirs/devs are idling
  [1m--dir, -d[0m [ID]
    specifies a directory by ID
  [1m--dev[0m [ID/name]
    specifies a device by ID or name
  [1m--all-dirs[0m
    applies the operation for all directories
  [1m--all-devs[0m
    applies the operation for all devices
  [1m--at-least, -a[0m [number]
    specifies for how many milliseconds Syncthing must idle (prevents exiting too early in case of flaky status)
  [1m--timeout, -t[0m [number]
    specifies how many milliseconds to wait at most

  example: syncthingctl wait-for-idle --timeout 1800000 --at-least 5000 && systemctl poweroff
           syncthingctl wait-for-idle --dir dir1 --dir dir2 --dev dev1 --dev dev2 --at-least 5000

[1mpwd, -p[0m
  operates in the current working directory
  [1mstatus, -s[0m
    prints the status of the current working directory
  [1mrescan, -r[0m
    rescans the current working directory
  [1mpause, -p[0m
    pauses the current working directory
  [1mresume[0m
    resumes the current working directory

[1mcat[0m
  prints the current Syncthing configuration

[1medit[0m
  allows editing the Syncthing configuration using an external editor
  [1m--editor[0m [editor name] [editor option] ...
    specifies the editor to be opened
    default environment variable: EDITOR
  [1m--script[0m [path]
    runs the specified UTF-8 encoded ECMAScript on the configuration rather than opening an editor
  [1m--js-lines[0m [line] ...
    runs the specified ECMAScript lines on the configuration rather than opening an editor
  [1m--dry-run[0m
    writes the altered configuration to stdout instead of posting it to Syncthing

Available top-level options:
[1m--config-file, -f[0m [path]
  specifies the Syncthing config file to read API key and URL from, when not explicitly specified
  default environment variable: SYNCTHING_CTL_CONFIG_FILE
  example: syncthingctl status --dir dir1 --config-file ~/.config/syncthing/config.xml

[1m--api-key, -k[0m [key]
  specifies the API key
  default environment variable: SYNCTHING_CTL_API_KEY

[1m--url, -u[0m [URL]
  specifies the Syncthing URL, default is http://localhost:8080
  default environment variable: SYNCTHING_CTL_URL

[1m--credentials, -c[0m [user name] [password]
  specifies user name and password
  example: syncthingctl status --dir dir1 --credentials name supersecret

[1m--cert[0m [path]
  specifies the certificate used by the Syncthing instance
  default environment variable: SYNCTHING_CTL_CERTIFICATE

[1m--no-color[0m
  disables formatted/colorized output
  default environment variable: ENABLE_ESCAPE_CODES

Linked against: C++ Utilities (static): 5.14.0, Connection backend of Syncthing Tray (Qt 6): 1.1.17, Qt Qml: 6.2.4, Qt Core: 6.2.4, Qt Network: 6.2.4, Qt Gui: 6.2.4, Qt Svg: 6.2.4

Project website: https://github.com/Martchus/syncthingtray
```

**Steps to reproduce**

1. Run `syncthingctl --help` from the default CMD console in Windows.

**Expected behavior**

The command line output should not contain characters that cannot be printed using the CMD console.

**Screenshots**

**Additional context**

**Comment by Martchus** [comment]
Use `--no-color` or `set ENABLE_ESCAPE_CODES=0` to disable use of ANSI escape codes if they're not supported by your environment. However, I'd generally like to keep them enabled - e.g. they work just fine under Windows when using Mintty/MSYS2. When I remember correctly, it even worked in some new terminal emulator provided by Microsoft.

I consider it a feature request to disable the use of ANSI escape codes by default in environments which are known to not support it.

**Comment by Martchus** [comment]
Note that `syncthingctl` will also unconditionally print output as UTF-8 so you also need to set your consoles' code page to UTF-8 when using `cmd.exe` to avoid broken non-ASCII characters.

**Comment by Martchus** [comment]
Yes, see my first comment which also mentions an env var. The hint about UTF-8 is just in addition because it might be the next problem you might run into.

**Comment by tomasz1986** [comment]
Just out of curiosity, are these escape codes only used to colorise the command line output? If yes, then is this the only way to achieve it? I'm asking, because both CMD and PowerShell console themselves are capable of displaying 16 colours, i.e.

![image](https://user-images.githubusercontent.com/5626656/172305416-f8f390f9-0b53-404b-9f61-d48ec03545b1.png)

and I've seen multiple colours used in other CLI programs, e.g. Git or aria2, so it's not like the command line in Windows itself is limited to two colours only.

**Comment by Martchus** [comment]
> If yes, then is this the only way to achieve it?

No, one can use certain WinAPI functions under Windows. However, I'm not going to spend any effort on using them when I can just use a decent terminal. No reason to go the extra mile to cover Microsoft's non-standard ways of doing things.

**Comment by tomasz1986** [comment]
> I can just use a decent terminal.

Yeah, but please keep in mind that there are many situations, where you can't do that (e.g. when using the software on another person's computer for troubleshooting, or in a restricted office environment, or when you use other software that relies on CMD being the default console, etc.). Another problem is that this is broken in PowerShell as well, and there is no alternative to PowerShell as such.

**Comment by Martchus** [comment]
Note that I'd generally accept a (well written) PR to improve this. It is just that I'm not going to spend the effort myself as I don't see the use case myself.

**Comment by tomasz1986** [comment]
My C-related skills are too minimal to be able to do anything really, so at this point my only request would be limited to at least not display the question marks and such by default there, as they make the output almost unreadable.

To tell the truth, I'm also not really a fan of replacing CMD with 3rd party terminals myself, as in my experience they don't really handle multi-language input well, especially when you need to input Asian scripts (e.g. Chinese characters and such).

**Comment by Martchus** [comment]
Looks like there's a registry hack to enable ANSI escape codes under Windows 10: https://stackoverflow.com/questions/16755142/how-to-make-win32-console-recognize-ansi-vt100-escape-sequences

And even better, it would be quite easy to enable ANSI escape codes from the application side: https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#example-of-select-anniversary-update-features=

So I'll give it a try.
