### ISSUE TITLE
When usb stick is connected it scans all drives

### ISSUE THREAD

**Issue by sledgehammer999** [Martchus/syncthingtray#14]
Sorry for the messed up title. Here's the deal:

When I connect a usb stick, Windows pops up an error message saying to insert media into `D:\` drive. In my PC `D:\` drive is a cd/dvd drive/writer.

I run `Process Monitor` and observed syncthingtray.
It seems that when a new drive is connected a signal is fired, syncthingtray reacts to it and starts querying all the drives. But when it reaches the cd/dvd drive I get that above message dialog (from Windows).

I know Qt and C++ programming but I am too lazy to dive into your project atm.
If you can't find what the problem is, at least point me to where your code listens for drive changes and where it reacts to it (slot).

Thank you.

Version: 0.7.3
Windows 7 sp1 64bit

**Comment by sledgehammer999** [comment]
I forgot to mention: Why do need to react to drive changes and query their info?

**Comment by Martchus** [comment]
So you get an error when the available devices change. What error do you get exactly? Maybe a screenshot would be helpful.

> Why do need to react to drive changes and query their info?

Actually I don't do that. So I can't point you to my code for that, too. Not sure what's triggering the rescan in your case.

**Comment by Martchus** [comment]
I'm closing because the issue doesn't not contain enough information for further investigation. Just reopen if you can provide more details (see my last comment).

**Comment by sledgehammer999** [comment]
Sorry for my late response I have been busy. Just for kicks, I tried it again today and I don't get the Windows error popup. My OS and syncthing version hasn't changed.
Weird...
Anyway, good call into closing this.
