### ISSUE TITLE
Create and maintain Pacstall package

### ISSUE THREAD

**Issue by trymeouteh** [Martchus/syncthingtray#143]
Please add this app into the pacstall repository. Pacstall is the AUR for Ubuntu which will allow Ubuntu users to easily install the app and receive updates very shortly after an update is released.

https://pacstall.dev/

**Comment by Martchus** [comment]
I cannot provide packaging for every kind of repository. I only provide packages/binaries for platforms I'm using myself. Feel free to add and maintain packages there yourself. It should not be hard to convert the Arch Linux PKGBUILDs.
