### ISSUE TITLE
Fedora 36 repository

### ISSUE THREAD

**Issue by 13k** [Martchus/syncthingtray#147]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [x] Dolphin integration
* [x] Command line tool (`syncthingctl`)
* [x] Integrated Syncthing instance (`libsyncthing`)
* [x] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**

Fedora release 36

**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Add repository for Fedora 36 on OBS.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by Martchus** [comment]
Added the repo, let's see whether all packages build.

**Comment by 13k** [comment]
wow, that was fast, thank you so much.

Build seems to have failed for `qtutilities` and packages depending on it (not sure why, it's complaining about clang 13 libs, but there's `clang13-libs` in Fedora 36).

In my `system-upgrade`'ed system from 35 to 36 it's not complaining though (packages were already installed previously). dnf downloads metadata and it's ok with the versions, so I assume it's because they were already installed.

**Comment by Martchus** [comment]
It does not even start to build because OBS has a choice for installing dependend packages and one needs to tell it how to choose:

```
unresolvable: have choice for libclang.so.13()(64bit) needed by qt5-doctools: clang-libs clang13-libs, have choice for libclang.so.13(LLVM_13)(64bit) needed by qt5-doctools: clang-libs clang13-libs 
```

I added

```
%if 0%{?fedora_version}
Prefer: clang-libs
%endif
```

to tell it to use `clang-libs`. `qtutilities` builds now.

**Comment by Martchus** [comment]
It builds so I'm closing the issue.
