### ISSUE TITLE
hi,i'm a C++ noob,how can i install application in windows11? i had install WinGW and set environment variable

### ISSUE THREAD

**Issue by YangHgRi** [Martchus/syncthingtray#149]
what should i do next?

**Comment by Martchus** [comment]
Just download the pre built binary from the release section here in GitHub. There is a README, you should really read it.

**Comment by YangHgRi** [comment]
thanks,i had download and start syncthingctl-1.2.1-x86_64-w64-mingw32.exe,but it crashed

**Comment by Martchus** [comment]
Crashed or just closed again immediately? It's the CLI, you likely want the GUI.

**Comment by YangHgRi** [comment]
wow,it is closed again immediately,so how can get GUI

**Comment by Martchus** [comment]
By downloading the exe for the GUI. It is syncthing*tray*... and NOT syncthing*ctl*.

**Comment by YangHgRi** [comment]
ok,thank u
