### ISSUE TITLE
Additional requirement for LGPL requirement

### ISSUE THREAD

**Issue by sten0** [Martchus/syncthingtray#150]
Hi Marius,

Sorry I've been out of touch.  The Debian package was just rejected...twice...prompting yet another license review...  LGPL §4.c states that Uri Herrera needs to be credited and the LGPL noted in the "About" popup (confirmed for the plasmoid, but likely also exists for the tray).  It is likely that similar requirements exist with the MPL and possibly the Fork Awesome license.

This stuff is really not fun.
Cheers

**Comment by Martchus** [comment]
I suppose I'll have to look into what's required exactly. Note that Fork Awesome is already mentioned. And this project is actually GPL, where does LGPL come into place? It is also not clear to me what icons Uri Herrera should be attributed for.

**Comment by Martchus** [comment]
Not sure whether I can help here without having an understanding of why this is required. And even if we have established the reasoning it would be good if the require wording would be stated explicitly.

**Comment by sten0** [comment]
My PR took care of the source repo copyright and license requirements, and it's the runtime ones that are outstanding:

The Breeze Icons are © Uri Herrera and are LGPL-3+.  See LICENSE.LESSER.  I remember you said that these icons are only "for fallback", but if they're in the repository and might end up in the application as a file asset, resource, etc, then attribution is required in the application.  It says so in the license...and yes, LGPL is tricker than and != to GPL.

The minimum format for "copyright attribution" is typically:
{"Copyright" and/or "©"} {year[s]} {copyright holder’s name}

but in LGPL-3+ prominent notice of the license is also required.  Basically you need to do the above, as well as the short name for a license, and you can use well-established short-forms, or SPDX short-forms, as well as a link to a license.  When "attribution in a prominent location at runtime" is required, or when the clause for an "application" rather than a "library" is activated, then this info usually goes in the "About" dialogue, as you're already doing for Fork Awesome.  If you check out the Help -> About Firefox -> Licensing information, you'll see that even web browsers have to include a local copy of the license...this is often required...check your license text for details.

So the essential bits are
1. Who
2. When
3. What license
4. Short license name
5. Provide full license text

Other than that there's a lot of flexibility:
  https://opensource.stackexchange.com/questions/6622/lgpl-2-1-attributions-required

**Comment by sten0** [comment]
and yes, this is a bug not a feature request

**Comment by Martchus** [comment]
I've been adding the copyright notice, the name of the license and a link to the full license text: https://github.com/Martchus/syncthingtray/commit/114faa6cf36c7e06b934b92aece1b785de7c2abb

This is now the same for all about dialogs in all components.

**Comment by sten0** [comment]
Martchus ***@***.***> writes:

> I've been adding the copyright notice, the name of the license and a link to the full license text: https://github.com/Martchus/syncthingtray/commit/114faa6cf36c7e06b934b92aece1b785de7c2abb
>
> This is now the same for all about dialogs in all components.
>

Thank you!  Yes, as far as I can tell this work now fulfills the minimal
legal requirements of the LGPL, either §4 or §5, whichever is active in
Syncthing Tray.  To be fair, it's unlikely the copyright holders would
attack a fellow FLOSS project :)

For legal and liability reasons I also have to say IANAL and this is not
legal advice...

So yeah, I think this issue can be closed as resolved by
114faa6cf36c7e06b934b92aece1b785de7c2abb

**Comment by Martchus** [comment]
Good, so I'm closing the issue.
