### ISSUE TITLE
Broken screenshot link at AppImage website and likely in Appstream and README.md (when viewed externally)

### ISSUE THREAD

**Issue by sten0** [Martchus/syncthingtray#154]
See broken link here: https://appimage.github.io/Syncthing_Tray/

I think this is probably due to failure to use the "raw" link, which is needed to cut out the github website stuff that is irrelevant to providing a screenshot.

**Comment by Martchus** [comment]
I stopped providing AppImage builds anyway. Having to build on the last LTS Ubuntu (or an equivalently old distro) and shipping those old dependencies plus hacks to load the right version of libstdc++ is just unreasonable. Users are now pointed at the self-contained binaries within the release section on GitHub.

**Comment by Martchus** [comment]
Besides, I'm not responsible for the page you're mentioning (and how they make use of the files provided in this GitHub repo).
