### ISSUE TITLE
Broken link in readme for Gentoo

### ISSUE THREAD

**Issue by dgasaway** [Martchus/syncthingtray#155]
**Bug description**

The link in the readme for Gentoo currently leads to a 404.  I've been using the repository provided by @CaseOf for some time now, and it has been working great for me.  I suggest linking to that.  https://codeberg.org/Case_Of/gentoo-overlay

**Comment by Martchus** [comment]
Why don't you just create a PR? :-)

**Comment by Martchus** [comment]
And if you have fixes like https://codeberg.org/Case_Of/gentoo-overlay/src/branch/master/x11-plugins/syncthingtray/files/syncthingtray-fix-build-without-systemd-on-USE-kde.patch then don't hesitate to create a PR as well.

**Comment by dgasaway** [comment]
I didn't (yet) to give @CaseOf an opportunity to comment. :)

**Comment by CaseOf** [comment]
I agree.

**Comment by Martchus** [comment]
Ok, I've added the link.
