### ISSUE TITLE
libqtforkawesome from OpenSUSE in fresh Fedora 36

### ISSUE THREAD

**Issue by JonasV328** [Martchus/syncthingtray#164]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [x] Backend libraries

**Bug description**
I am trying to install syncthingtray on a fresh Fedora 36 install with x86_64. I did this on a number of computers already a few weeks ago.
But now I get an error.

```
[jonas@Jonas-Laptop-U727 ~]$ LANG=C sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/home:mkittler/Fedora_36/home:mkittler.repo
[sudo] password for jonas: 
Adding repo from: https://download.opensuse.org/repositories/home:mkittler/Fedora_36/home:mkittler.repo

[jonas@Jonas-Laptop-U727 ~]$ LANG=C sudo dnf install syncthingtray
Last metadata expiration check: 0:01:47 ago on Sun Nov  6 16:48:30 2022.
Error: 
 Problem: conflicting requests
  - package syncthingtray-1.2.4-2.2.armv7hl does not have a compatible architecture
  - nothing provides ld-linux-armhf.so.3 needed by syncthingtray-1.2.4-2.2.armv7hl
  - nothing provides ld-linux-armhf.so.3(GLIBC_2.4) needed by syncthingtray-1.2.4-2.2.armv7hl
  - nothing provides libgcc_s.so.1(GCC_3.5) needed by syncthingtray-1.2.4-2.2.armv7hl
  - nothing provides libc++utilities.so.5 needed by syncthingtray-1.2.4-2.2.armv7hl
  - nothing provides libqtutilities.so.6 needed by syncthingtray-1.2.4-2.2.armv7hl
  - nothing provides libsyncthingconnector.so.2 needed by syncthingtray-1.2.4-2.2.armv7hl
  - nothing provides libsyncthingmodel.so.2 needed by syncthingtray-1.2.4-2.2.armv7hl
  - nothing provides libsyncthingwidgets.so.2 needed by syncthingtray-1.2.4-2.2.armv7hl
  - nothing provides libqtforkawesome.so.0.0.4 needed by syncthingtray-1.2.4-2.2.armv7hl
  - package syncthingtray-1.2.4-2.2.ppc64le does not have a compatible architecture
  - nothing provides libqtforkawesome.so.0.0.4()(64bit) needed by syncthingtray-1.2.4-2.2.ppc64le
  - nothing provides libqtforkawesome.so.0.0.4()(64bit) needed by syncthingtray-1.2.4-2.2.x86_64
```

I assume the last line is critical for my system. I see that your package libqtforkawesome1-0.1.0-1.1.x86_64.rpm was updated on 04-Nov-2022 in the Fedora 36 OpenSUSE repository, but syncthingtray-1.2.4-2.2.x86_64.rpm is still from 24-Oct-2022 and might somehow require the older 0.0.4 version?

I am sorry that I am not able to solve this myself, I am new to RPM packages.

Any help is gladly appreciated!

Kind regards,
Jonas

**Comment by Martchus** [comment]
This is because the build of Syncthing Tray is failing and apparently OBS isn't smart enough to hold back qtforkawesome from being publish. Just ignore the update of qtforkawesome for now. The build will likely be fixed in the next release.

**Comment by Martchus** [comment]
Had to adjust the spec file. It now builds again (at least for some targets but Fedora 36 x86_64 is among them).
