### ISSUE TITLE
WebView folder selection bug

### ISSUE THREAD

**Issue by Forger125** [Martchus/syncthingtray#165]
Before the bug report, I just want to say a huge **THANK YOU** to @Martchus for this incredible piece of software. It is a huge quality of life improvement to have this available, and it is clearly a very robust project. We don't say it enough as a community / users, so THANK YOU!

**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: …, …, …
   * Syncthingtray 1.3.0-5 (AUR)
   * qtutilities 6.10.0-1
   * c++utilities 5.20.0-1
* Qt version: 5.15.6+kde+r181-1
* C++ compiler (name and version): GCC 12.2.0-1
* C++ standard library (name and version): (couldn't find)
* Operating system (name and version): Manjaro KDE, Kernel 5.15.76-1-Manjaro, KDE 5.26.2, Frameworks 5.99.0

**Bug description**
When using the KDE file selection dialog through the Plasmoid web view "select directory..." button, after saving the actual path used in the synced folder is the Syncthing default based on the Folder Label / Folder ID rather than the Folder Path selected with the select directory button.

**Steps to reproduce**
1. Open Syncthing web view from plasmoid
2. Input basic information about the folder (image 1)
3. Use "select directory..." button to pick different folder (image 2)
4. Save folder
5. The folder in the folder list uses the auto-generated path based on the Folder Label (the one showed in image 1, i.e. /home/\*\*\*/test) rather than the one selected using the dialog (image 2, i.e. /home/\*\*\*/bin/cli). The same problem happens if no Folder Labal is used, in that case syncthing just uses the Folder ID

**Expected behavior**
The resulting Syncthing folder should match the directory selected from the KDE file dialog

**Screenshots**

**<u>Image 1</u>**
![image](https://user-images.githubusercontent.com/786092/202900308-3a06f803-b6fe-4da3-a0f5-71dc57506c04.png)

**<u>Image 2</u>**
![image](https://user-images.githubusercontent.com/786092/202900347-300c929b-e010-442e-958b-838ccc6003f0.png)

**Additional context**

- This has been a longstanding issue in my use of SyncthingTray, has happened for as long as I have had a system using the Plasmoid integration (~12-18 months) across updates of both syncthingtray and the system (i.e. KDE, QT, etc.)
- In conjunction with this error (i.e. closing and reopening the file dialog) I have also seen sporadic issues with duplication of the "select directory..." button (image below), which I know may be a separate issue
![image](https://user-images.githubusercontent.com/786092/202900545-ba2148f0-b12c-4c72-b7fc-bdd0b5263ef2.png)

**Comment by Martchus** [comment]
This likely broke a long time ago. I haven't used this feature myself for ages. Considering that it was more a cool hack than something really useful it might make sense to better just remove that hacky and half-baked feature.

**Comment by Forger125** [comment]
Thanks so much for the quick response!

Big picture, it would be nice for users in a GUI frontend designed to integrate into the environment to have a GUI folder select, a la Syncthing-GTK. But if it's effectively unmaintained removing it would have the benefits of both resolving a bug / simplifying the code as well as putting it in line with the Syncthing WebGUI :)

And again, thanks for everything you do on this project!

**Comment by Martchus** [comment]
I've just tested it and it is indeed broken in the ways you've said. For now I've just put it behind the runtime option to enable WIP features. Maybe I'll have the motivation to fix it at some point but it might break again when the official Syncthing GUI alters their HTML/JavaScript code slightly so it is likely not very worthwhile. Maybe I'll create an own GUI for configuring folders at some point but it has of course the problem of having to catch-up with changes in the official GUI so that's also problematic.
