### ISSUE TITLE
Fonts way too large in Windows after v1.3.1 when using DPI scaling

### ISSUE THREAD

**Issue by tomasz1986** [Martchus/syncthingtray#168]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`: 1.3.1
* Qt version: 6.4.1
* Operating system (name and version): Windows 10

**Bug description**

After upgrading to v1.3.1, fonts in SyncthingTray have increased in size drastically. For example, when the OS is set to 150% scaling, the fonts seem to be scaled at 175%, and when the OS is set to 175%, the fonts look as if they were scaled at 200%, etc.

**Steps to reproduce**
1. Set DPI scaling in Windows to a value larger than 100%, e.g. 150%.
2. Start SyncthingTray.

**Expected behavior**

Font size should match the size used in the rest of the OS (with the correct DPI scaling applied)

**Screenshots**

As seen in the screenshot, the icons are scaled correctly but the fonts are much larger than necessary.

![image](https://user-images.githubusercontent.com/5626656/206898634-895f6e93-c549-44ba-afb9-a6ecfd7eb454.png)

**Comment by Martchus** [comment]
It is an issue in Qt itself, see the updated release note in the GitHub release section.

**Comment by tomasz1986** [comment]
I did actually see the note but I thought the v1.3.1 version itself was already supposed to be fixed. I've only now noticed the separate download… I use a custom script to download and upgrade SyncthingTray but it wasn't able to automatically catch the additional download, only the original release 🙁. Thank you for the quick fix anyway!

**Comment by Martchus** [comment]
By the way, last time I had just swapped out binaries after fixing a specific build and then users were concerned about the binary being compromised. So this time I decided to upload the new binary only in addition.
