### ISSUE TITLE
Installing on Linux Mint: "E: Unable to locate package syncthingtray"

### ISSUE THREAD

**Issue by ReaderGuy42** [Martchus/syncthingtray#169]
I'd like to install this on my Linux Mint (based on Ubuntu) machine via `sudo apt install syncthingtray` as it says in your Readme. But then I just get:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package syncthingtray
```

I can't find anything about this online.
Any ideas?
Thanks!

**Comment by ReaderGuy42** [comment]
OK, thanks, I just wanted to check if I was doing something wrong. I'll ask elsewhere. Thanks :)

**Comment by ReaderGuy42** [comment]
Also thanks for replying so far!!

**Comment by sten0** [comment]
@Martchus,

Thank you for taking care of this user support :)

@ReaderGuy42

Martchus ***@***.***> writes:

>> Any ideas?
>
> Ask you distribution's packagers to add a package if you'd like to have one. This issue tracker is not the best place to ask. I can only offer you the generic GNU/Linux found in the release section on GitHub or to follow the build instructions to create your own build.

+1.  Also, I'm surprised that Mint is unlike most other Ubuntu (and thus
Debian) derivatives...most of them inherited syncthing and
syncthingtray.  It also makes me curious if all of golang is excluded.

ReaderGuy42 ***@***.***> writes:

> OK, thanks, I just wanted to check if I was doing something wrong. I'll ask elsewhere. Thanks :)

If you think of it, could you forward a link to Mint's reply here?

> Also thanks for replying so far!!

Sorry my response time was poor.

**Comment by ReaderGuy42** [comment]
Apologies, that was meant to say "fast" because Martchus replied quickly. No sarcasm meant!

**Comment by sten0** [comment]
@clefebvre, I was surprised to see that Linux Mint didn't inherit
syncthingtray from Ubuntu.  When you have time, would you please share
why that decision was made?  Alternatively, I wonder if it might be a
situation like this: all new packages must be manually approved, and
there was insufficient free time to look at this one :)

Please let me know if anything needs to be done on the Debian side
(ideally using bugs.debian.org, but as you wish).

ReaderGuy42 ***@***.***> writes:

> Apologies, that was meant to say "fast" because Martchus replied quickly. No sarcasm meant!
>

No need to apologies, and oh my!  When I wrote "Sorry my response time
was poor" it didn't occur to me that it could be interpreted as
sarcastic.
