### ISSUE TITLE
Make clear that "Syncthing URL" needs to start with `https://`

### ISSUE THREAD

**Issue by TheJoeSchr** [Martchus/syncthingtray#172]
I was lost for hours why this wasn't working :facepalm:

**Comment by Martchus** [comment]
Or `http://` if you don't use TLS. I'm wondering how you tried to start the URL.

Note that the wizard should help you configure things automatically. The config dialog also allows to fill out the connection settings automatically from the Syncthing config. Did this not work for you? (Of course if you want to connect to a Syncthing instance on a different host then this is clearly not clearly not useful.)

I suppose I could add "https://" as placeholder text but that would be misleading in case Syncthing does not use TLS as it then needed to be "http://".

**Comment by TheJoeSchr** [comment]
I somehow never got to see the wizard until way later when I stumbled into
it.

I guess I must have updated, restarted a bunch of times (remotely via ssh)
before I was sitting in front of the computer again.

Once I was in the wizard, it correctly filled it out. But I didn't know
there was a wizard until I found it


__

Typed on a mobile, please excuse any typing mistakes or short-spokeness.

**Comment by TheJoeSchr** [comment]
The error message said something about `protocol "" not found ` which makes
sense to me now, but not then. Maybe this would be a good point to mention
URL should contain sth like http[s]


__

Typed on a mobile, please excuse any typing mistakes or short-spokeness.

**Comment by Martchus** [comment]
I have added explaining placeholder texts, see referencing commit message for details. This should be good enough.

Good to know that the wizard generally worked. Maybe you've just (accidentally) dismissed it when setting things up.

With that I suppose this issue can be considered resolved.

**Comment by TheJoeSchr** [comment]
Thanks, good call!
