### ISSUE TITLE
installing boost-libs (1.81.0-2) breaks dependency 'libboost_filesystem.so=1.80.0-64' required by syncthingtray

### ISSUE THREAD

**Issue by JackDinn** [Martchus/syncthingtray#173]
Sorry but probably should not be asking this here but im going to :P

How do i resolve this dependency problem when trying to upgrade archlinux-keyring-20230130-1-any

`installing boost-libs (1.81.0-2) breaks dependency 'libboost_filesystem.so=1.80.0-64' required by syncthingtray`

Kernel: 6.0.19-3-MANJARO arch: x86_64 bits: 64
Desktop: KDE Plasma v: 5.26.5 Distro: Manjaro Linux
aur/syncthingtray 1.3.2-2 (+70 2.84)

**Comment by Martchus** [comment]
> Sorry but probably should not be asking this here but im going to :P

At least not like this. This is also not a bug. Please read https://aur.archlinux.org/packages/syncthingtray#comment-568348. Also note that this has nothing to do with the keyring package at all.

If you still have questions, you can ask here or in the AUR but please tell use what you were actually trying to do, e.g. the used AUR helper or whether you used my binary repo.

**Comment by JackDinn** [comment]
Not a bug no, but the only options are "bug" and "Feature request", i dont see "question" anywhere.

No it may have nothing to do with keyring but all i know is what i was doing (system upgrade) which wanted to upgrade the keyring first
```
:: Some packages should be upgraded first...
resolving dependencies...
looking for conflicting packages...

Packages (1) archlinux-keyring-20230130-1
```
And then it throws the syncthingtray dependacy error.

Sorry for posting here, i should have posted in the manjaro forum or arch (AUR) repo section.

I shall try something like yay -Syu --nodeps boost-libs and see what happens.

Thx though :)

**Comment by Martchus** [comment]
> Not a bug no, but the only options are "bug" and "Feature request", i dont see "question" anywhere.

Right, this seems to be a downside of the issue templates. You can always set tags as needed (or don't set any tags at all) but the upfront selection makes it not very obvious. Maybe I should add an additional template for "other" issues.

---

There are two suggestions mentioned in the linked pinned AUR comment. You're generally welcome to use this issue tracker here as well for general questions (if they're filed as such). However, it makes sense to read AUR comments first (and the Arch Linux Wiki if you have trouble understanding them). Note that I cannot give concrete help for all operating systems, their flavors and different tooling people possibly use. So if you want concrete advice about those you must ask the respective vendors.
