### ISSUE TITLE
Since Syncthingtray 0.8.0-1, reconnect interval doesn't work

### ISSUE THREAD

**Issue by sez11a** [Martchus/syncthingtray#18]
Updated from AUR a few days ago. In the plasmoid, I have the reconnect setting to 10000 ms (reconnect every 10 seconds). Generally, when I boot up, Syncthing hasn't fully started (since I start it via Plasma 5's Startup and Shutdown -> Autostart settings), so the Plasmoid in my tray isn't connected. The reconnect setting in the past has always automatically made the connection happen. With this new release, it seems the reconnect is ignored. The only way I can get the plasmoid to connect to Syncthing is to go into Settings and click *Apply Connection Settings and try to reconnect with the currently selected config*. 

The reconnect setting should make the plasmoid attempt to reconnect every 10 seconds, but it doesn't seem to be doing that.

**Comment by Martchus** [comment]
> The only way I can get the plasmoid to connect to Syncthing is to go into Settings and click Apply Connection Settings and try to reconnect with the currently selected config.

So not even clicking on the connect button on the tray helps?

Ensure you disabled to take the systemd status into account (just uncheck all checkboxes in the Systemd settings tab).

If you used the widgets-based tray application before, also ensure that the status of the internal launcher is not taken into account (just uncheck all checkboxes in the Syncthing launcher settings tab).

**Comment by sez11a** [comment]
I can click the connect button and it works. Sorry; I've never used that before, because it always auto-connected. I am not using systemd to start Syncthing, and the boxes in the Systemd are both unchecked.

**Comment by Martchus** [comment]
And the status of the internal launcher?

Maybe it would be the best if you can send me your config (located under `~/.config/syncthingtray.ini`). Be sure to remove sensible data like your API key.

**Comment by sez11a** [comment]
I just moved my syncthingtray.ini out of the `~/.config` folder and rebooted to get a default configuration. After configuring with the API key and reconnecting, it connected. I then rebooted to see if it would reconnect automatically like it's supposed to (I noticed the new reconnect default is 30 seconds), but it still doesn't reconnect automatically. Here's the new config file: 

``[qt]
customfont=false
customicontheme=false
customlocale=false
custompalette=false
customstylesheet=false
customwidgetstyle=false
font=",11,-1,5,50,0,0,0,0,0"
icontheme=amiga-kde
iconthemepath=
locale=en_US
palette="@Variant(\0\0\0\x44\x1\x1\xff\xff\0\0\0\0\0\0\0\0\x1\x1\xff\xff==\x86\x86\xd2\xd2\0\0\x1\x1\xff\xff\xe0\x84\xe5\xe4\xe8\xb3\0\0\x1\x1\xff\xff\xc2!\xcd\x87\xd3Q\0\0\x1\x1\xff\xffV\xf3]\xca\x61\x36\0\0\x1\x1\xff\xff\x93\xe6\x9f\x88\xa5Y\0\0\x1\x1\xff\xff\0\0\0\0\0\0\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff\0\0\0\0\0\0\0\0\x1\x1\xff\xff\xec\xec\xec\xec\xec\xec\0\0\x1\x1\xff\xff\xb2\xb2\xc0\xc0\xc7\xc7\0\0\x1\x1\xff\xff\x35\x81\x39\xb6;\xd1\0\0\x1\x1\xff\xff\xab\xab\xbe\xbe\xd2\xd2\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff\0\0ww\xef\xef\0\0\x1\x1\xff\xff^^__\xa6\xa6\0\0\x1\x1\xff\xff\xc9\xc9\xdf\xdf\xf5\xf5\0\0\x1\x1\xff\xffX\xd0^Ia\x11\0\0\x1\x1\xff\xff\\\xe0\x98\xa8\xe1\xaa\0\0\x1\x1\xff\xff\xeb\x86\xeeT\xef\xcf\0\0\x1\x1\xff\xff\xcc\xc2\xd4U\xd8?\0\0\x1\x1\xff\xff[\xb8\x61`d=\0\0\x1\x1\xff\xff\x9b\x64\xa4\xf9\xa9\xd3\0\0\x1\x1\xff\xff_\x1a_\x1a_\x1a\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff\x38\xe7]\x9b\x8a\x64\0\0\x1\x1\xff\xff\xee\xe9\xee\xe9\xee\xe9\0\0\x1\x1\xff\xff\xbd\xa7\xc7\xe3\xcd\x1a\0\0\x1\x1\xff\xff\x37Z:\xc4<\x7f\0\0\x1\x1\xff\xff\xbd\xa7\xc7\xe3\xcd\x1a\0\0\x1\x1\xff\xffX\xd0^Ia\x11\0\0\x1\x1\xff\xff`\x3\x96\xe0\xcd\xd1\0\0\x1\x1\xff\xff\x80\a\x80\xb7\xae\xbf\0\0\x1\x1\xff\xff\xd3\x7f\xe2\xd9\xf2\xc3\0\0\x1\x1\xff\xff\0\0\0\0\0\0\0\0\x1\x1\xff\xff==\x86\x86\xd2\xd2\0\0\x1\x1\xff\xff\xe0\x84\xe5\xe4\xe8\xb3\0\0\x1\x1\xff\xff\xc2!\xcd\x87\xd3Q\0\0\x1\x1\xff\xffV\xf3]\xca\x61\x36\0\0\x1\x1\xff\xff\x93\xe6\x9f\x88\xa5Y\0\0\x1\x1\xff\xff\0\0\0\0\0\0\0\0\x1\x1\xff\xff\xff\xff\xff\xff\xff\xff\0\0\x1\x1\xff\xff\0\0\0\0\0\0\0\0\x1\x1\xff\xff\xec\xec\xec\xec\xec\xec\0\0\x1\x1\xff\xff\xb2\xb2\xc0\xc0\xc7\xc7\0\0\x1\x1\xff\xff\x35\x81\x39\xb6;\xd1\0\0\x1\x1\xff\xff\xab\xab\xbe\xbe\xd2\xd2\0\0\x1\x1\xff\xff\0\0\0\0\0\0\0\0\x1\x1\xff\xff\0\0ww\xef\xef\0\0\x1\x1\xff\xff^^__\xa6\xa6\0\0\x1\x1\xff\xff\xc9\xc9\xdf\xdf\xf5\xf5\0\0)"
plugindir=
stylesheetpath=
trpath=
widgetstyle=

[startup]
considerForReconnect=false
considerLauncherForReconnect=false
showButton=false
syncthingArgs=
syncthingAutostart=false
syncthingPath=syncthing
syncthingUnit=syncthing.service
useLibSyncthing=false

[tray]
brightTextColors=false
connections\1\apiKey=@ByteArray(redacted)
connections\1\authEnabled=false
connections\1\devStatsPollInterval=60000
connections\1\errorsPollInterval=30000
connections\1\httpsCertPath=
connections\1\label=Primary instance
connections\1\password=
connections\1\reconnectInterval=30000
connections\1\syncthingUrl=http://127.0.0.1:8384
connections\1\trafficPollInterval=2000
connections\1\userName=
connections\size=1
dbusNotifications=true
frameStyle=54
ignoreInavailabilityAfterStart=15
notifyOnDisconnect=true
notifyOnErrors=true
notifyOnLocalSyncComplete=false
notifyOnNewDeviceConnects=false
notifyOnNewDirectoryShared=false
notifyOnRemoteSyncComplete=false
showSyncthingNotifications=true
showTraffic=true
tabPos=1
trayMenuSize=@Size(450 400)

[webview]
disabled=false
geometry=@ByteArray()
keepRunning=false
zoomFactor=2

**Comment by Martchus** [comment]
I haven't tested with a real reboot yet, but I suppose the problems should be gone with the latest changes on master.

**Comment by Martchus** [comment]
Still a problem in 0.8.1 or Git master?

**Comment by sez11a** [comment]
Nope. This is fixed. Thanks!
