### ISSUE TITLE
Create syncthingtray installer for windows

### ISSUE THREAD

**Issue by soredake** [Martchus/syncthingtray#180]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)

**Is your feature request specific to a certain platform/environment? Please specify.**
Windows 10/11.

**Is your feature request related to a problem? Please describe.**
Right now syncthingtray does not have installer, which creates problems like this in chocolatey https://gitlab.com/yan12125/chocolatey-packages/-/issues/2

**Describe the solution you'd like**
Have installer will make installation easy, and installer can also restart syncthingtray after updating (which choco package currently don't do)

**Describe alternatives you've considered**

**Additional context**

**Comment by Martchus** [comment]
I don't plan working on this. Contributions are welcome of course (similar to how it has already been done for certain GNU/Linux distributions, see https://github.com/Martchus/syncthingtray#packages-and-binaries).

I have been pondering about allowing the creation of a desktop icon and start menu entry via the wizard (besides the existing ability to configure the auto start). This would be a cross-platform feature. Under Windows it would also make sense to allow moving the binary to a default/custom application directory creating an entry in the Application Registration. This way the installer part would be cross-platform (as far as possible), the actual application could be the same binary and the installation would be neatly integrated with the general setup.

I have also been considering adding an auto-update feature similar to what Syncthing itself provides. This would then of course also allow one to restart Syncthing Tray if wanted.

I haven't implemented any of this yet due to lack of time and motivation. However, that's how I would move this forward - instead of implementing a Windows-specific installer (possibly using some additional installer framework).

**Comment by Martchus** [comment]
> and installer can also restart syncthingtray after updating

For the restarting part I've just introduced the `--replace` argument. This could be used when making an installer.

---

When I find the time to implement an auto-update feature as mentioned in my previous comment I'm also going to make use of that mechanism.

**Comment by yan12125** [comment]
How should I use the `--replace` option? From time to time, I got an error after `syncthingtray-1.4.2-x86_64-w64-mingw32.exe --replace`:

> Unable to request Syncthing config: 連線被拒

The error message is "connection refused" in English I guess.

**Comment by Martchus** [comment]
I've just created a new release but haven't taken care of this yet.

By the way, are you using the built-in library or an external application? I've only tested it with the built-in library so far (where I also sometimes ran into "Error opening database"). It always helped to simply start Syncthing again in the launcher settings. So the database lock seems to be released eventually and the 2nd instance is just too fast.

**Comment by yan12125** [comment]
I'm using the built-in (bundled) syncthing, and I can confirm restart syncthing in settings works.

**Comment by yan12125** [comment]
Maybe `--replace` is not what I need for the chocolatey package. During upgrades, I need kill the running proces anyway, so that I can remove the old exe and install the new exe to the same path.

**Comment by Martchus** [comment]
I guess the installer/updater I'd implement at some point would simply move away the old executable while it is running (this should work even under Windows) and move the new executable where the old one was. It would then invoke the new executable with `--replace` and remove the old binary.

Maybe you needed a  `--quit` option to close a possibly running instance. This would be very easy to implement but maybe you can just close the running process yourself (or tell the user to close it before continuing).

**Comment by yan12125** [comment]
> you can just close the running process yourself

Good point, I just implemented that in relevant chocolatey packaging scripts.

**Comment by mckayc** [comment]
Hey @yan12125 I just saw your comment from a few minutes ago. I am getting an error when trying to install with chocolatey.

> ERROR: Checksum for 'C:\Users\~\AppData\Local\Temp\chocolatey\syncthingtray\1.4.3\syncthingtray-1.4.3-x86_64-w64-mingw32.exe.zip' did not meet 'e52b4a6dfb17ec21d901da60402c8df1b444680eb20603d716d9cd3af8b8135d' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
> The install of syncthingtray was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\syncthingtray\tools\chocolateyInstall.ps1'.
>  See log for details.

Any ideas on why this is not working? It has not been working since yesterday. Thanks!

**Comment by yan12125** [comment]
Probably something wrong during downloads. Anyway this is more likely a chocolatey issue than a syncthingtray one, so https://gitlab.com/yan12125/chocolatey-packages or https://community.chocolatey.org/packages/syncthingtray#discussion is a better place for further discussions.

**Comment by soredake** [comment]
Not stale.

**Comment by Neurrone** [comment]
Am also experiencing the checksum errors when I tried installing it. The ftp download is also extremely slow

**Comment by Martchus** [comment]
What checksums are you talking about? I do not even provide downloads via FTP.

**Comment by Neurrone** [comment]
Ah sorry, after reading the above comments, I realize I should bring that in the chocolatey package repository.

It happens when I try installing [this chocolatey package](https://community.chocolatey.org/packages/syncthingtray)

**Comment by soredake** [comment]
Still interested.

**Comment by Tarek-Hasan** [comment]
Is there any chance you guys could use [Syncthing Windows Setup](https://github.com/Bill-Stewart/SyncthingWindowsSetup) project to make a windows installer?

**Comment by Martchus** [comment]
I guess it would be best if that installer would include Syncthing Tray if that is wanted. Probably the creator/maintainer of that installer doesn't use Syncthing Tray, though.

I personally don't need/want the sophisticated setup this installer aims for so I wouldn't put any effort into utilizing that myself. In fact, I generally prefer the simple setup Syncthing Tray currently offers. As already stated in https://github.com/Martchus/syncthingtray/issues/180#issuecomment-1508361539 this is something other contributors are welcome provide, though.

Note that you can use Syncthing Tray together with the Syncthing itself installed via [Syncthing Windows Setup](https://github.com/Bill-Stewart/SyncthingWindowsSetup), see https://github.com/Martchus/syncthingtray/blob/master/README.md#does-this-launch-or-bundle-syncthing-itself-what-about-my-existing-syncthing-installation.

**Comment by G2G2G2G** [comment]
Yea the installer would be nice literally just need to move the program to a different directory (like appdata) and then execute it as it already does. I see 90% of users leaving it in their downloads folder and then if they clear that out accidentally delete it lmao
