### ISSUE TITLE
Publish to microsoft store in msix format

### ISSUE THREAD

**Issue by soredake** [Martchus/syncthingtray#181]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)

**Is your feature request specific to a certain platform/environment? Please specify.**
Windows 10/11

**Is your feature request related to a problem? Please describe.**
Example benefits of msix package format: https://github.com/felixrieseberg/windows95/issues/221 https://learn.microsoft.com/en-us/windows/msix/overview#key-features

**Describe the solution you'd like**
syncthingtray published to microsoft store in msix format

**Describe alternatives you've considered**

**Additional context**

**Comment by Martchus** [comment]
I have also pondering about this but haven't have the time/motivation yet. Contributions are welcome of course. In case this is not uploaded directly by myself it would make sense to clarify in the store page that this is not uploaded by upstream itself, though.

Note that I am also pondering about the creation of a Flatpak. This is just one of many things I haven't had time/motivation for.

In case anybody wants to contribute to this, feel free to come up with necessary upstream contributions so the required meta-data files can be generated automatically from the build system. So far my workflow is that I build the Windows version on a GNU/Linux host that ends up creating an archive with everything needed for publishing (e.g. https://martchus.no-ip.biz/repo/arch/ownstuff/os/x86_64/mingw-w64-syncthingtray-qt6-1.4.1-1-any.pkg.tar.zst). That archive mainly contains the binary but it is conceivable to create additional meta-data files for certain platforms during the build and installing them so they end up in that archive and are available for publishing. I have already taken that approach for providing AppStream files for GNU/Linux stores.

**Comment by soredake** [comment]
Not stale.

**Comment by soredake** [comment]
Not stale.

**Comment by soredake** [comment]
Not stale.

**Comment by soredake** [comment]
Not stale.

**Comment by soredake** [comment]
Not stale.

**Comment by Martchus** [comment]
I'm reopening this issue althbough I don't think anybody is interested in actually creating and maintaining Syncthing Tray in the Microsoft store.
