### ISSUE TITLE
Adding programs / services (syncthing for example)

### ISSUE THREAD

**Issue by thinkbig1979** [Martchus/syncthingtray#183]
Hi there.,

Using fleek to add packages has worked without a hitch so far, so really cool and happy to have this tool. However, I'm struggling with programs/services. The fleek documentation is really sparse here.

Case in point: Trying to add syncthing, which needs to run as a service, and there is an entry in the home-manager documentation relating to syncthing as well, so I assume it needs to be added as a program.

Tried using the command line:
```shell
❯ fleek add --program syncthing

# fleek | vv0.8.5

## Usage
> Add a new package or program to your configuration

fleek add [package] [package] ...

## Description
Add a new package or program to your configuration.
Use the `--program` flag to specify a program which can also be configured by nix.
## Flags
-a, --apply   | apply configuration after adding
-h, --help    | help for add
-q, --quiet   | suppress logs
-v, --verbose | show more detailed output


  ERROR   unknown flag: --program

``` 
That did not work as you can see.
Also tried the syntax below, but same result.
```shell
fleek add syncthing --program
``` 

Trawling through the fleek directory looking for clues,  I found these two files:
```
~/.local/share/fleek/programs.nix
~/.local/share/fleek/user.nix
```
The comments in these files suggest that programs and their configs respectively should be listed in these two files before adding them to . 
I added `programs.syncthing.enable = true;` to programs.nix and `services.syncthing.enable = true; `to user.nix. Then added syncthing to the list of programs in the `fleek.yml` file and applied the config. It ran without errors, but syncthing was not installed. 

A bit of help here would be appreciated.  :-)

Thanks!

**Comment by Martchus** [comment]
I have no idea what fleek even is. A brief search gave me nothing. I don't think anyone who knows fleek reads this issue tracker. You issue doesn't even seem to mention Syncthing Tray (only Syncthing itself). So I'm sorry but I must close this. I don't see how this is relevant here not how I could help.

**Comment by thinkbig1979** [comment]
My apologies @Martchus! Too many tabs open I think! 
Will go and raise this issue in the correct repo now.
