### ISSUE TITLE
Missing packages on Fedora 37

### ISSUE THREAD

**Issue by creeloper27** [Martchus/syncthingtray#184]
Hi, I just tried installing the `syncthingtray` package on my Nobara 37 installation (which is based on Fedora 37) as I saw that packages are supposedly available for Fedora : https://github.com/Martchus/syncthingtray#packages-and-binaries with:

`sudo dnf install syncthingtray`

tho it failed with:
```
        Last metadata expiration check: 0:59:13 ago on Fri 28 Apr 2023 17:51:02.
No match for argument: syncthingtray
Error: Unable to find a match: syncthingtray
```
I can't seem to find them, I even checked on fedoraproject.org: https://packages.fedoraproject.org/search?query=syncthingtray and indeed they do not seem to be available, am I be missing something obvious?

Thanks in advance.

**Comment by creeloper27** [comment]
For some reason by reading the readme I thought that it was in the official repositories.

For anyone else who cannot read like me you need to add the repository manually, there is a link you can click here in that section.
![image](https://user-images.githubusercontent.com/20074177/235210784-7f0867e3-f252-42a9-bbf1-79dcb2a2090b.png)
I need to get more sleep.

**Comment by Martchus** [comment]
Good night :-)
