### ISSUE TITLE
Version 1.4.1 and 1.4.2 Don't Respect QT Palette Settings

### ISSUE THREAD

**Issue by Ryonez** [Martchus/syncthingtray#186]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.4.1+1.4.2 unknown unknown
*  Qt version: unknown
* C++ compiler (name and version): unknown
* C++ standard library (name and version): unknown
* Operating system (name and version): Windows 10 Pro Version 22H2 Build 22621.1778

**Bug description**
The QT Palette selected is not respected. The colours are incorrect, and when the setting dialog is closed it is reverted to default.

**Steps to reproduce**
Set QT setting to:
![image](https://github.com/Martchus/syncthingtray/assets/16157130/7de40c82-11fb-41e3-b64a-0928948103e0)
With the following Palette:
[dark-palette.zip](https://github.com/Martchus/syncthingtray/files/11682505/dark-palette.zip)

**Expected behaviour**
For the palette to be correctly used.

**Screenshots**
Synctray Version 1.3.2 to 1.4.0
![image](https://github.com/Martchus/syncthingtray/assets/16157130/8e3806f0-c35b-4c4b-a235-4c8e10476629)
![image](https://github.com/Martchus/syncthingtray/assets/16157130/a707fa52-80d3-4b3a-892f-0e8091565b0c)

Synctray Version 1.4.1 and up
![image](https://github.com/Martchus/syncthingtray/assets/16157130/109730e9-f334-4756-b1ab-572d70fc6908)
![image](https://github.com/Martchus/syncthingtray/assets/16157130/286812e9-fdf3-49b1-90ad-0c0ce53a75d2)
Applying the dark-palette
![image](https://github.com/Martchus/syncthingtray/assets/16157130/932234b9-e80f-43cf-9207-0b9e5d3eb6a7)
And after clicking Ok
![image](https://github.com/Martchus/syncthingtray/assets/16157130/9aee7cc1-01af-4042-8da0-f7c60e2cf3ee)

**Comment by Martchus** [comment]
I'm pretty sure I tested this at some point but you're right, this is not really working now. The palette can be changed but when changing the style it is reset accidentally.

**Comment by Ryonez** [comment]
Would like to note it's not just the saving that's a problem, the palette file imported isn't read correctly either. The colours don't match previous version.

**Comment by Martchus** [comment]
I think the loading part is fine. Likely you tried to load the dark palette mentioned in the initial issue comment and it was then overridden with the dark "defaults" from the Qt framework - because that is the one problem I could reproduce and have already fixed.

**Comment by Martchus** [comment]
I've noticed that some color roles could indeed not be loaded correctly, or rather not be immediately applied correctly.

I've just made a new release that is supposed to fix problems with the palette settings (and a few other regressions). Perhaps there are still some subtile bugs in the palette editor or in the way palettes are applied but as an immediate fix this is hopefully good enough.

**Comment by Ryonez** [comment]
The 1.4.3 release seams to make things start to work again. It does still lose settings from <=1.40, but I am able to load the palette and it seems to remain persistent.

Thank you very much for getting that sorted. I know it didn't impact functionality elsewhere, but that would've bugged me to keep around.

I'll leave you to close the issue if you'd like, I'm happy where it's at. Not sure if the settings getting lost in the first place is worth pursuing or not. I'm guessing maybe a qt config dir changed somewhere.

**Comment by Martchus** [comment]
> It does still lose settings from <=1.40

I assume you mean "<= 1.4.0". So you have preserved a config file that was last saved using 1.4.0 or lower and tried to load that with 1.4.1 or newer? I would expect that this works as of 1.4.3. If this doesn't work then presumably Qt changed how QPalette objects are serialized. Of course this won't work anyways if the config file was messed with by 1.4.1 or 1.4.2; then 1.4.3 won't be able to restore what has been lost.

If you have any problems just with 1.4.3 feel free to share the details (e.g. some color role is not stored persistently). I've already noticed that the link color isn't used in all places where I'd expected it to be used but that's likely a problem of Qt itself and not worth persuing.
