### ISSUE TITLE
Error while loading shared library

### ISSUE THREAD

**Issue by herrwusel** [Martchus/syncthingtray#20]
And here is my next problem when launching syncthingtray:

> $ syncthingtray
syncthingtray: error while loading shared libraries: libsyncthingwidgets.so.0.8.2: cannot open shared object file: No such file or directory

As install prefix I chose `/usr/local` and the library is there. Do I miss something?

**Comment by Martchus** [comment]
Read `man ld.so`. If you would like to set the `rpath` for the installed binaries, this is possible using the CMake variable `CMAKE_INSTALL_RPATH`.

Note that the binaries inside the build tree should have the rpath anyways (unless you set `CMAKE_SKIP_RPATH`).

**Comment by herrwusel** [comment]
Thanks for the hints. Created a config in `/etc/ld.so.conf.d/`. Working as intended now!

**Comment by Martchus** [comment]
So far there's no way to make donations, but I also don't think it is necessary. But thanks for the offer! If you like, you can of course also make a donation to the main Syncthing project.

Btw, contributions to the code (to extend functionality, fix bugs or add tests) are always welcome of course :)
