### ISSUE TITLE
Move/rename "Own device" in list

### ISSUE THREAD

**Issue by JohnVeness** [Martchus/syncthingtray#203]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Is your feature request related to a problem? Please describe.**
In the list of devices, the "Own device" is listed in alphabetical order. If you have a lot of devices, this can bury it a bit.

**Describe the solution you'd like**
I would prefer if that device is pinned to the top, as it is in the official web GUI.

Also, I find the wording "Own device" reads a bit oddly. In fact, most of the devices listed are my own devices! I would prefer "This device", which is also what is used in the official web GUI.

**Comment by Martchus** [comment]
I guess all of this makes sense. Maybe I'll find the time to implement this soon as it shouldn't be a big deal.

**Comment by Martchus** [comment]
This change has been implemented via the commits referenced by GitHub. So I guess the issue can be closed.
