### ISSUE TITLE
Use Folder rather than Directory wording

### ISSUE THREAD

**Issue by JohnVeness** [Martchus/syncthingtray#204]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [x] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [x] Backend libraries

**Is your feature request related to a problem? Please describe.**
Throughout the UI, the words directory & directories are used, when instead Syncthing uses the words folder & folders. Although the meaning is probably clear to most, it would be better to match Syncthing terminology.

**Describe the solution you'd like**
Directory replaced with Folder etc.

**Additional context**
I'm happy to submit a PR if you agree with this :)

**Comment by Martchus** [comment]
I know. I have never dared to take the effort to change it. It would likely make sense to change also all internal class/function names and descriptions and one had to take care that translations still work (without having to retranslate every affected string).

**Comment by JohnVeness** [comment]
Ah this is bigger than I thought - I didn't consider having to change internal names too, or translations! Another complication is that this isn't a simple search and replace - for example, the official Syncthing GUI refers to "directories" when showing the global or local size of a folder, and you also have a setting for a Qt plugin directory which probably shouldn't change.

**Comment by Martchus** [comment]
I suppose changing just the user-visible strings (and their translations) would nevertheless be the first step. Maybe I can find the time to look into that next week.

**Comment by JohnVeness** [comment]
I've had a go at this myself, if you're interested. See #206

**Comment by Martchus** [comment]
I've merged your PR and also added a few further commits for cleanup and completeness. This should cover all English and German user-facing strings.

**Comment by JohnVeness** [comment]
Many thanks :)

**Comment by Martchus** [comment]
I guess this can be considered done; not sure whether it makes sense to change the names of all internal functions/classes/files.
