### ISSUE TITLE
DLL file not found

### ISSUE THREAD

**Issue by jeysoncc** [Martchus/syncthingtray#211]
I've been using this for months without problems. I always unzip the files and I open the .exe file, but this time, I got an error. A DLL file was not found. Did I do something wrong? How can I fix it?

![Captura de pantalla 2023-11-07 162824](https://github.com/Martchus/syncthingtray/assets/109998358/838acf1b-d8d9-4a0c-9ffb-5ae175569994)
![Captura de pantalla 2023-11-07 162912](https://github.com/Martchus/syncthingtray/assets/109998358/1fb9bb6f-1b92-4a74-b667-2fd683d6545e)

Screenshot Translation: _"Code execution failed because libzstd.dll was not found.
This problem can be solved by reinstalling the program."_

OS: Microsoft Windows 23H2 (22631.2506)

**Comment by Martchus** [comment]
That's a bug, indeed. I possibly haven't spotted it because I have the DLL somehow in the search path.

**Comment by Martchus** [comment]
This is a regression caused by updating to Qt 6.6.0, in particular by commit https://github.com/qt/qtbase/commit/3f45905953d57e0174059d7d9d6bc75c3c1c406c. I'll simply revert this commit and rebuild relevant bits.

**Comment by Martchus** [comment]
I re-uploaded the Windows binaries and updated the release notes accordingly. The re-uploaded binaries should work as `objdump -x syncthingtray.exe | grep 'DLL Name'` does not show any DLLs anymore that don't belong to Windows itself. So I'm closing the issue although it would be nice if you could confirm whether it works on your end, too.

**Comment by jeysoncc** [comment]
Everything's good now. Thanks.
