### ISSUE TITLE
Running tests overwrites .config/autostart entry

### ISSUE THREAD

**Issue by itsxaos** [Martchus/syncthingtray#221]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`: 1.4.10-1 & 1.4.11-1, `qtutilities`: 6.13.3-1 and `c++utilities`: 5.24.4-1
* Qt version: `qt5-base 5.15.11+kde+r148-1` / `qt6-base 6.6.1-2`
* C++ compiler (name and version): `clang 16.0.6-1` / `gcc 13.2.1-3`
* C++ standard library (name and version) `libc++ 16.0.6-1` / `gcc-libs 13.2.1-3`
* Operating system (name and version): Arch Linux

**Bug description**

Running the tests (i.e. when updating the AUR package) overwrites the autostart entry command to something like `"/home/xaos/.cache/yay/syncthingtray/src/syncthingtray-1.4.10/syncthingwidgets/syncthingwidgets_wizard_tests" qt-widgets-gui --single-instance`.
This then means Syncthing Tray does not autostart on subsequent reboots / logins.

I've had a quick look at `syncthingwidgets/tests/wizard.cpp` and some of the `syncthingwidgets/settings` files but I haven't been able to figure out why this is happening.

**Steps to reproduce**
1. Setup Syncthing Tray autostart
2. Check `~/.config/autostart/syncthingtray.desktop`
```
...
Exec="/usr/bin/syncthingtray" qt-widgets-gui --single-instance`
...
```
3. Update Syncthing Tray / run the tests (`yay -Su syncthingtray`)
4. Check `~/.config/autostart/syncthingtray.desktop`
```
...
Exec="/home/xaos/.cache/yay/syncthingtray/src/syncthingtray-1.4.11/syncthingwidgets/syncthingwidgets_wizard_tests" qt-widgets-gui --single-instance
...
```

**Expected behavior**
Tests probably should not change config / autostart files, or if they have to, try to restore them to how they were.

**Additional context**
I think this has been happening for quite a while, it just took me some time to figure out why the autostart kept breaking.

P.S.: Thanks for your work on Syncthing Tray, I like it a lot!

**Comment by Martchus** [comment]
That should definitely not be the case and it's likely an oversight on my side. Thanks for reporting, I'll have a look at this tomorrow.

**Comment by Martchus** [comment]
Should be fixed on master. I also updated the AUR packages.

**Comment by itsxaos** [comment]
Awesome, thank you!
I reinstalled just now and the fix for the AUR package works.
