### ISSUE TITLE
winget install does not seem to actually create syncthingtray alias

### ISSUE THREAD

**Issue by martianrock** [Martchus/syncthingtray#222]
**Relevant components**
* [X] Standalone tray application (based on Qt Widgets)

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: syncthingtray-1.4.11-x86_64-w64-mingw32.exe
* Operating system (name and version): Windows 11

**Bug description**
After installing via winget, you cannot start the app using syncthingtray command

**Steps to reproduce**
1. `winget install syncthingtray` in a powershell window to install syncthingtray
2. restart shell to pick up new env:PATH
3. type `synctingtray` in powershell window
4. alias is not found, syncthingtray is not launched

**Expected behavior**
synctingtray command should be able to launch the app after install. 

winget install prints this line:
```Command line alias added: "syncthingtray"```
which implies that syncthingtray command can be used to lauch the app

**Additional context**
I was able to inspect $env:PATH variable to find newly added path to synctingtray install and was able to launch it using syncthingtray-1.4.11-x86_64-w64-mingw32.exe
Content of the added path after install:
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a---        12/11/2023   9:14 PM         962062 ﬓ  syncthingtray-1.4.11-x86_64-w64-mingw32-cli.exe
-a---        12/11/2023   9:25 PM         708465   syncthingtray-1.4.11-x86_64-w64-mingw32-LICENSES.md
-a---        12/11/2023   9:14 PM       59621406 ﬓ  syncthingtray-1.4.11-x86_64-w64-mingw32.exe

```

**Comment by Martchus** [comment]
The winget package is not developed within this repository. Please file an issue where it is developed. (The developer of the winget package is most likely not reading issues you're creating here.)

**Comment by martianrock** [comment]
added https://github.com/microsoft/winget-pkgs/issues/132145
