### ISSUE TITLE
KDE Error loading syncthing

### ISSUE THREAD

**Issue by zany130** [Martchus/syncthingtray#227]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [x] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`:1.4.12-1, 6.13.4-1, 5.24.5-1
* Qt version: 5.15.12
* C++ compiler (name and version): GCC 13.2.1
* C++ standard library (name and version): …
* Operating system (name and version): Garuda Linux

**Bug description**
Syncthing tray does not load after updating `qt5-webengine`

**Steps to reproduce**
1. Update `qt5-webengine` to  `5.15.16-3`
2. run synching tray

**Expected behavior**
synching tray loads as expected

**Additional context**
```
file:///usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/main.qml:13:34: Type FullRepresentation unavailable

file:///usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/FullRepresentation.qml:16:9: Type ToolBar unavailable

file:///usr/share/plasma/plasmoids/martchus.syncthingplasmoid/contents/ui/ToolBar.qml:7:1: module "martchus.syncthingplasmoid" is not installed
```

running in terminal gives the following
```
syncthingtray
syncthingtray: error while loading shared libraries: libvpx.so.9: cannot open shared object file: No such file or directory
```

**Comment by Martchus** [comment]
Garuda Linux is not supported; you cannot generally use packages from my binary Arch Linux repository on other Arch-based systems. It may work by accident, though. If you've built packages on your own then you're on your own anyway when it comes to handling rebuilds that may be necessary after updating packages.

I suspect that in this case the version of ffmpeg that is installed on your system needs to be rebuilt against an updated version of libvpx you have recently installed on your system. However, that has really nothing to do with Syncthing Tray or my Arch Linux packaging.

**Comment by Martchus** [comment]
I'm closing this issue because it is most likely a setup issue on your end and there's really nothing to be improved on my side.

You can still write a comment or re-open the ticket if you have further questions or think it is a problem of Syncthing Tray after all (but please explain why you think so).

**Comment by zany130** [comment]
> I suspect that in this case the version of ffmpeg that is installed on your system needs to be rebuilt against an updated version of libvpx you have recently installed on your system. However, that has really nothing to do with Syncthing Tray or my Arch Linux packaging.

I did this in fact I tried rebuilding your `synchingtray`  AUR package and it complained that it was looking for `libvpx.so.9` instead of `libvpx.so.8`

I am using `ffmpeg` from the arch repos and am fully up to date

trying to reproduce this in arch linux VM just to ensure that its not a garuda issue.

**Comment by Martchus** [comment]
Rebuilding my `syncthingtray` package won't help because libvpx is not a direct dependency of it. To me this error looks like some other library like `ffmpeg` or `qt5-webengine` that use libvpx directly need a rebuild. Since you're saying you're using official packages and you're up to date that is of course rather strange and should not be the case.
