### ISSUE TITLE
Provide package for Linux Mint

### ISSUE THREAD

**Issue by Kamul-PL** [Martchus/syncthingtray#228]
**Is your feature request specific to a certain platform/environment? Please specify.**
Linux Mint 21.3 Cinnamon 6.0.4

**Is your feature request related to a problem? Please describe.**
There's no *syncthingtray* in Linux Mint repository. Tried to install with:
`sudo apt install syncthingtray`
command, as suggested. But the package doesn't exist.

**Describe the solution you'd like**
I enter the
`sudo apt install syncthingtray`
 command in the terminal and the package is being installed.

Or maybe there are any other solution to my problem? Help, please.

**Comment by Martchus** [comment]
Judging by https://repology.org/project/syncthingtray/versions Syncthing Tray is not available for Linux Mint. I suggest asking developers of Linux Mint to create packages or create your own repository for that distribution like I did for Arch Linux, openSUSE and Fedora.

Note that I cannot provide packages for all of the many distributions out there and also won't look into creating/maintaining packages for Linux Mint. I keep the ticket open in case someone else wants to help with that.

Note that it may be possible to use Debian or Ubuntu packages which do exist according to repology. There's also a generic binary for GNU/Linux systems you can download from the release section on GitHub.

**Comment by Kamul-PL** [comment]
Thanks for your reply!
I thought Linux Mint is so close to Debian and Ubuntu, that if the package is available for them, it will be automatically available for Linux Mint. But I was wrong. Sorry, but don't know the details how the packages are being crated.

> Note that I cannot provide packages for all of the many distributions out there and also won't look into creating/maintaining packages for Linux Mint.

This is obvious to me. Thank you once again!

**Comment by Martchus** [comment]
With that I'd actually close this issue. If somebody wants to create a package for Mint we can reopen it if that's wanted (but supposedly this is better tracked by an issue on Linux Mint's side).
