### ISSUE TITLE
Folder IDs with URL-reserved characters break requests

### ISSUE THREAD

**Issue by tschai-yim** [Martchus/syncthingtray#229]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [x] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [x] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: `1.4.12`, `6.13.4`, `5.24.5`
* Qt version: probably `6.6.1`
* C++ compiler (name and version): …
* C++ standard library (name and version): …
* Operating system (name and version): NixOS unstable ([this derivation](https://github.com/NixOS/nixpkgs/blob/ae5c332cbb5827f6b1f02572496b141021de335f/pkgs/applications/misc/syncthingtray/default.nix))

**Bug description**
Syncthing Tray does not escape folder IDs when making requests. I have a folder ID  `name+` which results in the following internal error:
```
Error: Unable to request folder statistics: Error transferring http://localhost:8384/rest/db/status?folder=name+ - server replied: Not Found
```
The `+` character is most likely interpreted as a space by Syncthing. Manually making the request with `name%2B` returns the expected result.

**Steps to reproduce**
1. Register folder with ID `name+`
2. Start Syncthing Tray
3. Get notification that the request failed

**Expected behavior**
Special characters in the folder ID get escaped and Syncthing Tray can interact with these folders.

**Additional context**
- [Relevant section in code](https://github.com/Martchus/syncthingtray/blob/4265a94a63d3e6aeee895dc971783d30f28089fe/syncthingconnector/syncthingconnection_requests.cpp#L1122)
- `QUrlQuery::addQueryItem()` does not [automatically escape](https://doc.qt.io/qt-6/qurlquery.html#addQueryItem)
- There's [`QUrl::toPercentEncoding()`](https://doc.qt.io/qt-6/qurl.html#toPercentEncoding) which could maybe solve this

**Comment by Martchus** [comment]
Thanks for bringing that to my attention. I'll have a look at it as soon as possible. Supposedly I should also check other places where parameters are passed like this.

**Comment by Martchus** [comment]
Fixed on master, see commit referenced by GitHub.
