### ISSUE TITLE
Hide Plasma Applet When Syncthing is Idle

### ISSUE THREAD

**Issue by BreadYogurt** [Martchus/syncthingtray#23]
Plasma applets in the system tray have the ability to hide/unhide theirselves in the overflow menu. The syncthingtray applet does not take advantage of this feature. It would be nice if the applet hid itself when Syncthing is idle, and unhid itself when not idle (syncing/error/disconnected/etc).

**Comment by Martchus** [comment]
I don't like it but still a valid feature request and likely easy to implement as an optional setting.

**Comment by Martchus** [comment]
Implemented on latest master. You can choose the states when the Plasmoid should be hidden in the settings.

It only works when showing the Plasmoid within the notification area, though. When adding it as an own Plasmoid setting the passive state doesn't seem to have any effect.
