### ISSUE TITLE
Popup opening in center of screen

### ISSUE THREAD

**Issue by Protarios** [Martchus/syncthingtray#233]
(Manjaro Linux)
In the past the syncthingtray popup window opened next to the tray icon, where it would be expected.
Now it always opens in the center of the screen, except, if the setting dialogue is open, then it opens relative to the settings window.
"Use mouse position" is checked.

![grafik](https://github.com/Martchus/syncthingtray/assets/11992477/1a4c81ca-59ae-4e90-9c88-86c9c9dfe665)
![grafik](https://github.com/Martchus/syncthingtray/assets/11992477/122ce37a-c93e-45e8-8916-24d379441db0)

**Comment by Martchus** [comment]
Probably due to you switching to Wayland. Use X11 or the Plasmoid.
