### ISSUE TITLE
Plasma 6 Support

### ISSUE THREAD

**Issue by zany130** [Martchus/syncthingtray#235]
Thanks for the great software! 

Not sure if you are aware but plasma 6 came out and all plasmoid need to be ported https://develop.kde.org/docs/plasma/widget/porting_kf6/

**Comment by Martchus** [comment]
This has already been done since the first alpha release.

**Comment by zany130** [comment]
Hmm I installed it from the aur and its not working (saying it needs to be ported). (and didn't find any issue about plasma 6) so I thought it hasn't been ported yet... ill try building from git to see if that helps

**Comment by Martchus** [comment]
You don't need to build from Git. Plasma 5 has been supported for several versions. Be sure to use `syncthingtray-qt6`, though. This is already explained in pinned comments so please read them.
