### ISSUE TITLE
Changing the folder with data does not work in any way

### ISSUE THREAD

**Issue by jintaxi** [Martchus/syncthingtray#237]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [x] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: syncthingtray-qt5-1.5.0-x86_64-w64-mingw32.exe.zip, not used (i think), not used (i think)
* Qt version: 5.15.12
* C++ compiler (name and version): not used (i think)
* C++ standard library (name and version): not used (i think)
* Operating system (name and version): 23H2 22631.3007

**Bug description**
In the original version of Syncthing, there is a -data flag that says where to store the database of indexed files
(index-v 0.14.0.db for the current version of Syncthing 1.27.4). SyncthingTray also has an option that allows you to change the database storage directory. But this option does not work.

**Steps to reproduce**
0. Delete the existing index-v 0.14.0.db folder
1. Switch SyncthingTray to portable mode
2. Use the Syncthing version built into SyncthingTray
3.1 Try to change either in Settings -> Startup -> Syncthing launcher -> Data Directory 
3.2                       or in the ini libSyncthingDataDir file

**Expected behavior**
SyncthingTray will store the database of indexed files in the specified folder (as it happens with the -data flag in the original Syncthing)

**Screenshots**
![image](https://github.com/Martchus/syncthingtray/assets/74786420/53e5e9cc-ebb6-4c02-95d3-93cbceecc43c)

\\/ \\/ \\/

![image](https://github.com/Martchus/syncthingtray/assets/74786420/8ff846e1-2b5a-4dea-beef-22fb148c4c35)

**Comment by Martchus** [comment]
Thanks for reporting. This was fortunately just a simple mistake which is fixed now (see commit referenced by GitHub).
