### ISSUE TITLE
Support for environment variables for data/config folders

### ISSUE THREAD

**Issue by jintaxi** [Martchus/syncthingtray#243]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [x] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**
Both for Windows and Linux.

**Is your feature request related to a problem? Please describe.**
In the `Syncthing Tray -> Settings -> Startup -> Syncthing launcher -> Config directory/Data directory` support for environment variables is needed. Such as `%LocalAppData%` in Windows.

**Describe the solution you'd like**
When writing something like `%LocalAppData%/Syncthing`, the program interprets it not as `%LocalAppData%/Syncthing` to a folder in the local directory, but actually follows the path specified in the environment variable.

**Describe alternatives you've considered**
I write the full path to the `AppData/local` folder, which makes it difficult to port the program (for example, for a USB stick), or leave it in the program folder (`./data`).

**Comment by Martchus** [comment]
Another alternative would be to use the environment variables mentioned by `syncthing serve --help` and not set anything in the settings dialog. At least I *think* the integrated Syncthing instance allows that as well.

However, I guess I can add support for those substituions (or would accept a PR adding this feature).

**Comment by Martchus** [comment]
Closing as this is now implemented. The implementation uses https://pkg.go.dev/os#ExpandEnv under the hood so the syntax is `$VAR`  or `${VAR}` and I suppose that also counts under Windows.
