### ISSUE TITLE
Failed test in AUR

### ISSUE THREAD

**Issue by vinoff** [Martchus/syncthingtray#246]
I am installing syncthingtray via aur `yay -S syncthingtray` but it is failing a test, namely:

`          3 - syncthingwidgets_run_wizard_tests (Subprocess aborted)`

It seems to be something that happens frequently to other people, at least according to AUR comments, though I couldn't find a fix. 

Any suggestion?

I think this is the important section of the logs. Let me know if you need more:

```
3/3 Testing: syncthingwidgets_run_wizard_tests
3/3 Test: syncthingwidgets_run_wizard_tests
Command: "/home/vinoff/.cache/yay/syncthingtray/src/syncthingtray-1.5.1/syncthingwidgets/syncthingwidgets_wizard_tests"
Directory: /home/vinoff/.cache/yay/syncthingtray/src/syncthingtray-1.5.1/syncthingwidgets
"syncthingwidgets_run_wizard_tests" start time: Apr 09 10:26 WEST
Output:
----------------------------------------------------------

(syncthingwidgets_wizard_tests:156030): Gtk-WARNING **: 10:26:34.982: Unable to locate theme engine in module_path: "adwaita",

(syncthingwidgets_wizard_tests:156030): Gtk-WARNING **: 10:26:34.986: Unable to locate theme engine in module_path: "adwaita",
********* Start testing of WizardTests *********
Config: Using QtTest library 5.15.13, Qt 5.15.13 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 13.2.1 20230801), arch unknown
QDEBUG : WizardTests::initTestCase() "HOME dir: /tmp/syncthingwidgets_wizard_tests-OwOEoZ"
PASS   : WizardTests::initTestCase()
PASS   : WizardTests::testShowingSettings()
QWARN  : WizardTests::testConfiguringLauncher() This plugin does not support propagateSizeHints()
QWARN  : WizardTests::testConfiguringLauncher() This plugin does not support propagateSizeHints()

=== Received signal at function time: 299950ms, total time: 300001ms, dumping stack ===
=== End of stack trace ===
QFATAL : WizardTests::testConfiguringLauncher() Test function timed out
FAIL!  : WizardTests::testConfiguringLauncher() Received a fatal error.
   Loc: [Unknown file(0)]
Totals: 2 passed, 1 failed, 0 skipped, 0 blacklisted, 300004ms
********* Finished testing of WizardTests *********
<end of output>
Test time = 300.33 sec
----------------------------------------------------------
Test Failed.
"syncthingwidgets_run_wizard_tests" end time: Apr 09 10:31 WEST
"syncthingwidgets_run_wizard_tests" time elapsed: 00:05:00
----------------------------------------------------------

End testing: Apr 09 10:31 WEST
```

**Comment by Martchus** [comment]
The last questions on the AUR that actually related to this specific test are a bit older. I though I was able to iron-out those problems.

Unfortunately this isn't so easy to debug in the build environment. I usually run tests in headful mode and step though them via GDB to see what's going on.

Does this always happen or just sometimes?

The GTK-related warnings look a bit weird. They look like you're using a special platform integration plugin or Qt Widgets style. Maybe this is problematic.

By the way, you probably want to use the Qt 6 based version at this point. It would also be interesting to know whether it works to build `syncthingtray-qt6` in your environment.

Note that I generally recommend to build in a clean chroot using `makechrootpkg`.

**Comment by vinoff** [comment]
The qt6 version installed, though I am unsure if the problem was/is with the qt5 version or with the fact that I rebuilt all dependencies. Regardless, it is installed. Thank you @Martchus!
