### ISSUE TITLE
Tray Icon remains green when remote device is disconnected

### ISSUE THREAD

**Issue by Lcchy** [Martchus/syncthingtray#248]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Version of `syncthingtray`: 1.5.1
* Operating system (name and version): Fedora 39

**Bug description**
When I shutdown the remote device ("linode" in the screenshot), syncthingtray, which is running on my pc ("lemur") , detects that the device is disconnected but the tray icon does not turn grey. 

**Expected behavior**
The tray icon turns grey to reflect the connection loss.

**Screenshots**
![screenshot_2024-Apr-10th_19h07m11s](https://github.com/Martchus/syncthingtray/assets/52164716/244ed036-7b8e-4bcc-89fd-4d23cb2fe0d4)

When I pause the device from my pc, the tray icon behaves as expected:
![screenshot_2024-Apr-10th_19h17m03s](https://github.com/Martchus/syncthingtray/assets/52164716/d8550fde-b145-44e6-90eb-29aece3d8f20)

Ps: I would also like to receive a desktop notification about the connection loss, even though I have setup all notifications in the settings, that is not the case. Is this possible?

I am new to syncthingtray, and I hope that I have not simply overlooked some setting regarding my issue.

**Comment by Martchus** [comment]
It behaves actually as expected. I could add a setting to allow changing the behavior in the way you described. Should it turn gray if at least one remote is not connected or only if all remotes are not connected? 

Adding a notification would also be possible.

Not sure when I'll find the time to implement this but I'd accept a PR. Just make sure the default behavior stays.

**Comment by Lcchy** [comment]
Ah I see, thanks for the quick reply! 

In my use case it would make more sense for it to turn grey if at least one remote is disconnected.

I will look into the code and see if it seems doable for me to write a PR.

**Comment by Martchus** [comment]
If it is doable then let me know if you start coding so we're not duplicating the effort. (I'll also assign myself to this issue on GitHub when I'll find the time to work in it myself.)

**Comment by Lcchy** [comment]
Hi! Sorry I am having a busy time, I have looked at the code but I don't have enough time at the moment to be able to take it on.
