### ISSUE TITLE
Tray icon not displayed

### ISSUE THREAD

**Issue by leezu** [Martchus/syncthingtray#25]
First, thanks for developing this tool! On KDE Plasma 4.14.2, KDE Frameworks 5.51.0, QT 5.11.1 I am facing trouble making syncthingtray work.
While I can launch syncthingtray, no visual indication (ie. tray icon) happens. Launching a second time notifies `Info: Application already running, sending args to previous instance`. Calling with `--webui` or `--trigger` works (but tray icon is still missing).
In addition the Plasmoid is not displayed. I can select and add it to my Desktop, but then nothing happens (https://github.com/Martchus/syncthingtray/issues/17). 

Do you have any suggestions how to debug this?

**Comment by herrwusel** [comment]
Did you check your 'status & notification' [area?](https://community.kde.org/Plasma/Notifications#System_tray_panel)

**Comment by Martchus** [comment]
Does the tray icon work for other Qt 5 applications? Is the icon maybe just hidden (by the notifications plasmoid)? Are you sure it is using the right [QPA plugin](http://doc.qt.io/qt-5/qpa.html). Eg. using qt5ct might not work under Plasma but such misconfiguration can easily happen when often switching between different desktop environments.

For debugging, the log of `plasmashell` would be interesting as well. You could also test under another desktop environment to see whether it makes a difference.

I usually debug the application itself using gdb within Qt Creator. To make this easy, I use the method described in [building this straight](https://github.com/Martchus/syncthingtray#building-this-straight) also with Qt Creator. There are also instructions about [debugging the Plasmoid](https://github.com/Martchus/syncthingtray/blob/master/plasmoid/testing.md).

So https://github.com/Martchus/syncthingtray/issues/17 is reproducible by multiple users. Maybe it is a bug after all and not just a configuration issue.

**Comment by leezu** [comment]
Thanks @herrwusel @Martchus . I am embarrassed to say @herrwusel is right and I didn't check the 'status & notification' area. Thanks for pointing this out! Regarding #17, I observe the following (unique; most entries are logged multiple times) entries when moving the Plasmoid from the 'Add Widgets' window to some location on my Desktop:

```
Oct 25 08:12:14 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletDelegate.qml:82:13: QML QQuickItem*: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
Oct 25 08:12:24 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/PanelConfiguration.qml:81:5: QML ToolBar: Binding loop detected for property "implicitWidth"
Oct 25 08:12:24 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/panelconfiguration/ToolBar.qml:87:5: QML GridLayout: Binding loop detected for property "showText"
Oct 25 08:12:27 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletDelegate.qml:82:13: QML QQuickItem*: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
Oct 25 08:12:29 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletDelegate.qml:82:13: QML QQuickItem*: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
Oct 25 08:12:31 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletDelegate.qml:82:13: QML QQuickItem*: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
Oct 25 08:12:32 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletDelegate.qml:82:13: QML QQuickItem*: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
Oct 25 08:12:35 leonard-xps13 kdeconnectd[27562]: qt.bluetooth.bluez: No uuids found for "28:B2:BD:E3:AB:24"
Oct 25 08:12:37 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletDelegate.qml:82:13: QML QQuickItem*: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
```
I am not sure if any of these logs is related to the syncthingtray Plasmoid. For example, moving the "Analogue Clock" to my Desktop generates the following unique entries:
```

Oct 25 08:16:22 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/PanelConfiguration.qml:81:5: QML ToolBar: Binding loop detected for property "implicitWidth"
Oct 25 08:16:22 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/configuration/panelconfiguration/ToolBar.qml:87:5: QML GridLayout: Binding loop detected for property "showText"
Oct 25 08:16:24 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletDelegate.qml:82:13: QML QQuickItem*: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
Oct 25 08:16:25 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletDelegate.qml:82:13: QML QQuickItem*: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
Oct 25 08:16:27 leonard-xps13 plasmashell[27540]: adding "org.kde.plasma.analogclock"
Oct 25 08:16:30 leonard-xps13 plasmashell[27540]: file:///usr/share/plasma/shells/org.kde.plasma.desktop/contents/explorer/AppletDelegate.qml:82:13: QML QQuickItem*: Detected anchors on an item that is managed by a layout. This is undefined behavior; use Layout.alignment instead.
```

I will update #17 once I followed your debugging the Plasmoid instructions.

**Comment by Martchus** [comment]
I can reproduce the problem that it doesn't show after restarting under Plasma. However, with qt5ct/Tint2 is works.

It definitely worked before under Plasma, too. Seems to be a regression in either Plasma, Qt 5 or my own code.

**Comment by Martchus** [comment]
I've just restarted `plasmashell` on my machine (since it was already running for 6 days without crash!). After the restart the issue is gone. So in my case it was very likely just Plasma behaving weird.
