### ISSUE TITLE
Syncthing Tray is in a perma state of reconnecting

### ISSUE THREAD

**Issue by trdemoss** [Martchus/syncthingtray#253]
Syncthing Tray is in a perma state of reconnecting.  The main sync thing application is running out of this Windows folder, C:\Users\RDeMoss\AppData\Local\Syncthing.  This is running normally and syncs with my devices as it should.  In settings for the "Startup" navigation | "Syncthing launcher" tab, I have the Syncthing executable pointing directly at the Windows folder and exe file.  The arguments are "-no-browser -no-restart -logflags=3".  In the Syncthing log view, I can see that Syncthing is running and looks happy.

When I look at "Tray" navigation | Connections, I see the Syncthing URL which works and connects; the API Key which is also correct; the HTTPS certificate is set to Auto-detect and HTTPS is enabled; The selected Overall Status is checked, but the reconnection status is "reconnecting" and has been like that for days.

Any suggestions to debug the perma reconnecting state would be much appreciated.  I have set this to HTTP mode and that did not fix it.  I've added the https-cert.pem to the HTTPS line and that didn't do anything.  I've stopped and started syncing many times and the same with the tray application.  I've imported the syncthing configuration settings and that seems to work fine but the parameters don't change because I believe they are correct.  I do see these 

I do see these events in the logs, but they appear to be devices that are offline or unresponsive from a polling cycle.

```[B4DX5] 2024/04/18 17:30:25 INFO: Device GNF4YE4 client is "syncthing v1.27.3" named "SM-G986U" at 10.xxx.10.236:22000-10.xxx.10.135:22000/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256/LAN-P10-5U7GETSGKVDD64O9MIKOE8UBM2
[B4DX5] 2024/04/18 17:31:30 INFO: Lost primary connection to GNF4YE4 at 10.xxx.10.236:22000-10.xxx.10.135:22000/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256/LAN-P10-5U7GETSGKVDD64O9MIKOE8UBM2: reading length: read tcp 10.xxx.10.236:22000->10.xxx.10.135:22000: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (0 remain)
[B4DX5] 2024/04/18 17:31:30 INFO: Connection to GNF4YE4 at 10.xxx.10.236:22000-10.xxx.10.135:22000/tcp-server/TLS1.3-TLS_AES_128_GCM_SHA256/LAN-P10-5U7GETSGKVDD64O9MIKOE8UBM2 closed: reading length: read tcp 10.xxx.10.236:22000->10.xxx.10.135:22000: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.```

**Comment by Martchus** [comment]
So this doesn't work at all? Or is this state only reached after a while?

Are there some log messages or errors from Syncthing Tray itself? See https://github.com/Martchus/syncthingtray/issues/252#issuecomment-2063325731 for how to get those.

**Comment by trdemoss** [comment]
Thanks for the reply Martchus.  Syncthing itself is running normally.  I added a screenshot of the synching webUI and the Syncthing Tray into the attached support bundle.  Only the Tray software is saying that it's reconnecting.  When I first installed the tray, it was working fine.  I added my devices and folders and made other changes like enabling HTTPS.  Later, after a reboot, the Tray is stuck on reconnecting.  I checked the obvious settings like the API key, HTTPS settings, etc and those seem to be set properly.  I'm sure this will work, but can't find logs for the Tray or any debug settings.  I've also tried selecting and deselecting the Overall status options and clicking the "apply" button.  It never changes from "reconnecting."

[support-bundle-B4DX5M6-2024-04-22T163034.zip](https://github.com/Martchus/syncthingtray/files/15069187/support-bundle-B4DX5M6-2024-04-22T163034.zip)

**Comment by Martchus** [comment]
It looks really like things are broken on Syncthing Tray's side but it is hard to tell why. So reading the logs from stdout as described in https://github.com/Martchus/syncthingtray/issues/252#issuecomment-2063325731 and my next comment is not possible?

**Comment by t214c** [comment]
A few points in my case:

1. I have a PC connected to the local area only. This PC experiences such weird behavior of Tray.
2. 3/4 times this error "Reconnecting" happens.
3. Syncthing runs normally (but in two processes). Web GUI runs fine, even when launched from Tray.
4. Almost every time I quit Tray, it complains about "Kill syncthing process?"
5. Tray does not produce log output (only syncthing's log in the settings)
6. Syncthing runs with `-H syncthing` argument.

If you want me to try something, please ask.

**Comment by Martchus** [comment]
Point 4 sounds like Syncthing isn't responding to the API call to shut it down. So probably Syncthing Tray has a hard time communicating with Syncthing via its API which would also explain point 2.

For point 5: From your other issues I assume you're using Windows. Then see [the CLI documentation](https://github.com/Martchus/syncthingtray/blob/master/docs/cli.md#important-remarks) for getting output on the terminal and [development documentation](https://github.com/Martchus/syncthingtray/blob/master/docs/devel.md#logging) for enabling more logging.

Maybe Qt is trying to be clever here taking the systems connectivity state into account when it shouldn't. What version of Qt are you using?

**Comment by t214c** [comment]
> I assume you're using Windows.

Yes

> What version of Qt are you using?

6.10.1

> enabling more logging.

I meant by right clicking the tray icon and selecting "Log". The other PC with internet produces log just fine without me changing anything.

---

7. One syncthing process command line (in the task manager) is `syncthing.exe <arguments>`, the other `<full path>\syncthing.exe <arguments>`, if relevant.

**Comment by t214c** [comment]
8. When simply opening the Tray settings and clicking OK (without having to change anything), **the tray turns blue and connects**.

**Comment by Martchus** [comment]
> I meant by right clicking the tray icon and selecting "Log". The other PC with internet produces log just fine without me changing anything.

Ah, than that's just another symptom of it not being able to do API requests.

---

To 7: Considering you're saying that Syncthing itself is generally responding (e.g. when opening the official UI in a web browser) I would say how you launched Syncthing itself should not matter. The only exception is that you have two instances and Syncthing Tray tries to connect to the unavailable/unresponsive one and your test with the web browser connects to the responsive one. (Note that *one* Syncthing instance uses processes (one for monitoring, one for the actual daemon).)

To 8: That's weird. It means that everything is working after all and correctly setup. It just gets stuck somehow initially. Maybe the initial connection attempt runs into some error case that isn't handled correctly leading to the overall API-handling getting stuck. I have no idea why that would be the case, though. Maybe you can nevertheless see whether you can gather logs of Syncthing Tray as I've mentioned before.

**Comment by t214c** [comment]
Here is the log after the point 8 behavior. Sorry for the ham-fisted redactions. I'll see if I can get a log while Tray is not working.

```
2026-01-26T##:25:12.1289065###:##: 
syncthing v2.0.13 "Hafnium Hornet" (go1.25.5 windows-amd64) builder@github.syncthing.net 2025-12-23 08:10:48 UTC (log.pkg=main)

2026-01-26T##:25:12.1661762###:##: 
Failed to fetch latest release information (error="Get \"\": unsupported protocol scheme \"\"" log.pkg=upgrade)

2026-01-26T##:25:12.1671754###:##: 
Initial automatic upgrade (error="no version to select" log.pkg=main)

2026-01-26T##:25:12.1672673###:##: 
Calculated our device ID (device=#######-...-####### log.pkg=syncthing)

2026-01-26T##:25:12.1683096###:##: 
Overall rate limit in use (send="is unlimited" recv="is unlimited" log.pkg=connections)

2026-01-26T##:25:12.1704038###:##: 
TCP listener starting (address=(ip):(port) log.pkg=connections)

2026-01-26T##:25:12.170941###:##: 
Ready to synchronize (folder.label=(label) folder.id=(id) folder.type=sendreceive log.pkg=model)

2026-01-26T##:25:12.1714526###:##: 
GUI and API listening (address=(ip):(port) log.pkg=api)

2026-01-26T##:25:12.1714526###:##: 
Access the GUI via the following URL: https://(ip):(port)/ (log.pkg=api)

2026-01-26T##:25:12.1714526###:##: 
Loaded configuration (name=C log.pkg=syncthing)

2026-01-26T##:25:12.1714526###:##: 
Loaded peer device configuration (device=####### name=PC address="[(ip):(port)]" log.pkg=syncthing)

2026-01-26T##:25:12.1762539###:##: 
Ready to synchronize (folder.label=(label) folder.id=(id) folder.type=sendreceive log.pkg=model)

2026-01-26T##:25:12.1783314###:##: 
Ready to synchronize ...

2026-01-26T##:25:12.2177685###:##: 
Completed initial scan ...

2026-01-26T##:25:12.696588###:##: 
Measured hashing performance

2026-01-26T##:25:12.7534794###:##: 
Completed initial scan ...

2026-01-26T##:25:13.1301385###:##: 
Failed to fetch latest release information (error="Get \"\": unsupported protocol scheme \"\"" log.pkg=upgrade)

2026-01-26T##:25:17.2155491###:##: 
Established secure connection ...

2026-01-26T##:25:17.2156466###:##: 
New device connection ....

2026-01-26T##:25:22.2320623###:##: 
Established secure connection ...

2026-01-26T##:25:22.2320623###:##: 
Additional device connection ...

2026-01-26T##:25:27.2550215###:##: 
Established secure connection ...

2026-01-26T##:25:27.2558582###:##: 
Additional device connection ...
```

**Comment by t214c** [comment]
What level logging do you need? Also what should the value of the env variable be? Set `LIB_SYNCTHING_CONNECTOR_LOG_ALL` to what? I tried value of `1` but syncthingtray-cli.exe still didn't output anything even after the settings thing.

---

~~9. It insists that folder xyz is out of sync even though:~~
    ~~1. "Out of sync" line says none~~
    ~~2. Web GUI says fine~~
Nevermind that. Web GUI updated after a few seconds.

**Comment by Martchus** [comment]
> What level logging do you need? Also what should the value of the env variable be? Set `LIB_SYNCTHING_CONNECTOR_LOG_ALL` to what? I tried value of `1` but syncthingtray-cli.exe still didn't output anything even after the settings thing.
> 

Yes, setting this variable like that is what I had in mind. Maybe I can test it myself later when I have the time under Windows by just plugging-off the LAN cable.

Note that some things are based on polling (in Syncthing Tray and the official UI). Hence both might not be perfectly in-line with each other. Of course they shouldn't show different states for too long.

**Comment by t214c** [comment]
> by just plugging-off the LAN cable

You might need to allow LAN but disable internet/gateway access.

**Comment by Martchus** [comment]
> You might need to allow LAN but disable internet/gateway access.

Right, as just plugging-off the LAN cable did *not* allow me to reproduce the issue. How do you disable internet/gateway access? I guess I could just *mis*configure a static gateway to break internet access. That seems a bit hacky and might again not fully replicate your setup. So what exactly did you configure on your system?

---

> 8. When simply opening the Tray settings and clicking OK (without having to change anything), **the tray turns blue and connects**.

That's actually a quite interesting detail. When clicking OK it applies the connection settings and probably comes to the conclusion it needs to re-connect. That will in turn first abort all pending requests - and that's probably what causes it to get unstuck again. Of course some initial requests getting stuck shouldn't cause further requests to get stuck as well. So that would be a bug/limitation in Qt Network. (Maybe Qt Network limits the number of pending HTTP requests.)

I'm wondering whether it helps to set a timeout for requests in settings. By default there's no timeout so requests unfortunately *can* get stuck by default in the way I described but configuring a timeout might help with that. (No timeout is still the default "timeout" because the Syncthing API has some routes which can take a very long time to complete. Well, it is probably actually just the route to trigger a scan. So maybe it would make sense to add an exception for that one route and otherwise have a reasonable default timeout.)

**Comment by t214c** [comment]
> That seems a bit hacky and might again not fully replicate your setup.

If it is stupid but works,... :) The gateway needs to be a valid (connected) device but not the router. i.e. another client.
