### ISSUE TITLE
Environment variables do not go through to Syncthing when using libsyncthing

### ISSUE THREAD

**Issue by daniele-athome** [Martchus/syncthingtray#255]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [x] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`: [1.5.2-x86_64-w64-mingw32](https://github.com/Martchus/syncthingtray/releases/download/v1.5.2/syncthingtray-1.5.2-x86_64-w64-mingw32.exe.zip)
* Operating system (name and version): Windows 10 21H2 build 19044.4291

**Bug description**
I can't find a way to pass environment variables to syncthing. I'd like to set `all_proxy` to use a SOCKS5 proxy and I can't set global environment variables due to OS policy configuration. I tried writing a simple .bat file:

```
@echo off
setlocal
  set all_proxy=http://127.0.0.1:9090/ && set ALL_PROXY_NO_FALLBACK=1 && start syncthingtray-1.5.2-x86_64-w64-mingw32.exe
endlocal
```

I also tried other another approach (several actually):

```
@echo off
set all_proxy=http://127.0.0.1:9090/
set ALL_PROXY_NO_FALLBACK=1
start syncthingtray-1.5.2-x86_64-w64-mingw32.exe
```

I also tried without using "start".

Syncthing logs at INFO level whether a proxy configuration is present, but it never does.

**Steps to reproduce**
1. set environment variable in cmd or in a .bat script
2. launch Syncthing via libsyncthing

**Expected behavior**
Libsyncthing should be using proxy settings from `all_proxy` environment variable.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by Martchus** [comment]
Does this work when starting the regular `syncthing.exe`? E.g. when you use:

```
@echo off
set all_proxy=http://127.0.0.1:9090/
set ALL_PROXY_NO_FALLBACK=1
start syncthing.exe
```

where `syncthing.exe` is from https://github.com/syncthing/syncthing/releases/tag/v1.27.6.

Note that I don't think that `libsyncthing` will unset any environment variables. I'm also not sure where these two environment variables are actually supposed to be evaluated.

**Comment by daniele-athome** [comment]
I'm an idiot. all_proxy needs to use the socks5 scheme otherwise it won't work.

```
set all_proxy=socks5://127.0.0.1:9090
```

It works now. Sorry :-)
