### ISSUE TITLE
Fedora 40 packages in OBS

### ISSUE THREAD

**Issue by rominf** [Martchus/syncthingtray#256]
Fedora 40 is out yesterday: https://fedoramagazine.org/announcing-fedora-linux-40/. It would be great to build packages for the latest Fedora version in OBS.

**Comment by Martchus** [comment]
I added the repos.

**Comment by Martchus** [comment]
Looks like OBS was quite fast and everything built fine. Can I remove Fedora 36?

**Comment by rominf** [comment]
Absolutely! Fedora 36 and Fedora 37 can be removed, since they are end of life. Fedora 38 will be end of life soon:
https://docs.fedoraproject.org/en-US/releases/eol/

Thank you for your project and Fedora packages!
