### ISSUE TITLE
Quick question: Where are the config files and how to re-force the config wizard?

### ISSUE THREAD

**Issue by vinoff** [Martchus/syncthingtray#262]
My config seems to be messed up. I want a do-over. Where are the config files located (on Linux) and is it possible to re-do the config wizard that one usually gets at first start?

I am using syncthingtray-qt6 from AUR.

**Comment by Martchus** [comment]
Read the relevant README section: https://github.com/Martchus/syncthingtray?tab=readme-ov-file#location-of-the-configuration-file

**Comment by vinoff** [comment]
Thank you!
