### ISSUE TITLE
Which version for Windows 64 Bit and which Version of Syncthing original is used in the newest version?

### ISSUE THREAD

**Issue by marsch1975** [Martchus/syncthingtray#263]
Hi,

which version for Windows 64 Bit do I need to download? there are so many version, I really don't understand what they are fore. I want a zip/exe, not code for the terminal...

And which Version of Syncthing original is used in the newest vesion?

Thank you very much
Markus

**Comment by marsch1975** [comment]
And what's the difference between syncthingctl and syncthingtray?
Is there any page I can read about all tzhe different versions?

**Comment by marsch1975** [comment]
And what is qt behind some versions?

**Comment by Martchus** [comment]
Checkout the "Downloads" section on the website: https://martchus.github.io/syncthingtray/#downloads-section

All your questions are answered in the README. Note that Qt refers to the [Qt framework](https://www.qt.io) but you probably don't (need) to care.

**Comment by Martchus** [comment]
> And which Version of Syncthing original is used in the newest vesion?

Ok, I guess that question is actually not answered. I always bundle the latest version of Syncthing that has been released at the time I release Syncthing Tray. Note that you're not bound to use the bundled version (see https://github.com/Martchus/syncthingtray/blob/master/README.md#does-this-launch-or-bundle-syncthing-itself-what-about-my-existing-syncthing-installation different kinds of setups).
