### ISSUE TITLE
Clean up Releases section

### ISSUE THREAD

**Issue by slrgt** [Martchus/syncthingtray#266]
Please make the Releases section simpler for average users to understand. I have experience with managing servers, linux, and a lot of tech stuff but even I can't understand the Releases page.

Can you name them things like Windows 64 bit, Windows 32 bit, windows ARM. Im not sure if thats what the differences are but I'm trying to send a friend to install syncthing and I dont know what link to send them
![firefox_HklU6K5Shw](https://github.com/Martchus/syncthingtray/assets/114287507/d4d9d957-13c3-4a74-b815-464763244e42)

theres so many options and the names arent easy to understand

**Comment by Martchus** [comment]
That's what the website is for: https://martchus.github.io/syncthingtray/#downloads-section

If you need binaries for ARM you'll need to compile them yourself at this point.
