### ISSUE TITLE
At first installation, `unexpected argument serve` arrive form syncthing

### ISSUE THREAD

**Issue by SiriosDev** [Martchus/syncthingtray#267]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`: 1.5.3 (Cause at the moment scoop extras is not updated)
* Operating system (name and version): Windows 11

**Bug description**
After a first installation `syncthingtray` fails to start external `syncthing` due to an arguments error, `syncthing.exe: error: unexpected argument serve`. (Arguments by default)

**Screenshots**
![image](https://github.com/Martchus/syncthingtray/assets/26876994/d654c496-2b7a-4352-9c77-021a4354017f)

**Comment by Martchus** [comment]
What default arguments do you suggest then? I copied the default arguments from how Syncthing is launched via systemd under Linux - maybe under Windows it needs to be called differently. Where is your `syncthing.exe` coming from and does it work if you use an absolute path (to be sure the right binary is invoked)?

**Comment by Martchus** [comment]
It works just fine here with the latest version of Syncthing Tray and Syncthing under Windows 11 (but nothing has changed here recently so I don't think updating to the most recent versions will help in your case). Probably your `syncthing.exe` is not actually Syncthing.

**Comment by SiriosDev** [comment]
I'm currently on Syncthing 1.27.8 “Gold Grasshopper” installed via scoop (main), syncthingtray 1.53 installed via scoop (extra), everything comes from the original repos, I tried using arguments manually and it gives the same error

**Comment by Martchus** [comment]
> I tried using arguments manually and it gives the same error

That means it is definitely not the fault of the Syncthing Tray launcher then. In my tests `syncthing.exe` from the official Syncthing downloads on GitHub worked just fine with `serve` and my other default parameters. So your version of Syncthing behaves strangely. Note that I'm not using Scoop myself and looking into any issues specific to this packaging is out of scope for this issue tracker (but I can try to assist you a little bit).

**Comment by SiriosDev** [comment]
I'll try it from the official site and let you know if the problem persists

**Comment by SiriosDev** [comment]
Found the problem! the scoop shims includes `serve` argument

**Comment by Martchus** [comment]
No problem.
