### ISSUE TITLE
Downloads tab is messed up on Windows 11

### ISSUE THREAD

**Issue by soredake** [Martchus/syncthingtray#269]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.5.0
* Qt version: 6.6.2
* C++ compiler (name and version): …
* C++ standard library (name and version): …
* Operating system (name and version): Windows 11 Pro

**Bug description**
![изображение](https://github.com/Martchus/syncthingtray/assets/5204968/68b1b3c5-86fa-49c0-bd00-63ccbbc44d4a)

**Steps to reproduce**
1. Trigger downloading (by putting something in remote folder)
2. Go to downloads tab
3. Downloads tab looks not good

**Expected behavior**
Downloads tab should display correctly

**Screenshots**
![изображение](https://github.com/Martchus/syncthingtray/assets/5204968/9711ea0e-d56e-4f9a-97a7-8b1dfe0ac8a7)

**Additional context**

**Comment by Martchus** [comment]
I haven't seen that yet. I'll try to reproduce this explicitly with the latest version of Synching Tray when I have time. 

Note that I cannot support older versions. So preferably file tickets for the current version.

**Comment by soredake** [comment]
Oh, I only now noticed that syncthing is for some reason not updated, sorry! In the newer version downloads tab works fine.

**Comment by Martchus** [comment]
Good. Of course it could be an issue only happening under some circumstances and the versions don't really differ. So feel free to reopen if it happens with the latest version after all. (For now I hope it was just a Qt bug that has been fixed in Qt 6.7.1.)
