### ISSUE TITLE
Syncthing Tray doesn't start at Windows startup

### ISSUE THREAD

**Issue by tonypachino** [Martchus/syncthingtray#276]
I installed syncthing tray and after a while it just won't start at windows 11 login when i enter my login windows 11 password.

Then i double click on syncthing tray installation exe file and then syncthing tray just execute itself.

Why, when i start installation file, it should start installation and not start it as already installed app.

How can i solve this problem?

**Comment by Martchus** [comment]
Syncthing Tray has no installer, just like Syncthing itself. Checkout the README for details. You can move around the executable if you like but then you'll have to revisit autostart settings so the path of the autostart entry is updated to point to the new location of the executable.
