### ISSUE TITLE
Plasmoid does not show up in tray, only as a widget

### ISSUE THREAD

**Issue by genderneutralnoun** [Martchus/syncthingtray#279]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.6.0-qt6, ???, ???
* Qt version: QT6
* C++ compiler (name and version): ???
* C++ standard library (name and version): ???
* Operating system (name and version): Fedora 40 KDE Spin

**Bug description**
I recently moved to a new computer with Fedora 40 KDE on it, the same as my old one. However, upon installing `syncthing`, `syncthingtray-qt6`, and `syncthingplasmoid-qt6`, only the version of the tray icon that is the standalone application shows up in the tray. I can enable the plasmoid as a widget, but this is not desired for my use case. As well, I distinctly remember there being setting(s) to enable to hide the standalone tray app while leaving the plasmoid enabled, but there are no such settings in the settings menu of either the plasmoid or the tray app. It's like the tray app can't "see" that the plasmoid is installed.

**Steps to reproduce**
1. Install `syncthing`, `syncthingtray-qt6`, and `syncthingplasmoid-qt6` via the provided repository
2. Start syncthingtray via the application menu shortcut
3. Suffer

**Expected behavior**
I expected to be able to see the plasmoid in the system tray, as had been happening on my old computer.

**Screenshots**

**Additional context**
I did copy over a lot of config files from my old computer, but I've regenerated `syncthingtray.ini` at least 3 times now. Also, I put question marks in some of the versioning asks because I couldn't figure out how to check the versions for those. If you need their versions, please tell me how to check that and I will happily provide.

**Comment by Martchus** [comment]
I'm not using Fedora myself so maybe the packages are broken. However, before we jump to conclusions: Did you check that you have added the correct repository - the one for your particular version of Fedora? Note that I do provide a repo for Fedora 40 but maybe it is not compatible with the "KDE Spin" you're using.

> I can enable the plasmoid as a widget, but this is not desired for my use case.

I'm not sure what you mean by that.

> 2. Start syncthingtray via the application menu shortcut

This step makes no sense if you want to use the Plasmoid. The application menu only contains an entry for the stand-alone tray application. Read the corresponding README section for how to configure the Plasmoid: https://github.com/Martchus/syncthingtray?tab=readme-ov-file#configuring-plasmoid

> It's like the tray app can't "see" that the plasmoid is installed.

Why would it? The tray app is completely independent of the Plasmoid with no dependencies on any KDE-specifics. You can (but probably don't want to) run it in parallel with the Plasmoid. You can also uninstall `syncthingtray-qt6` if you only need the Plasmoid on that system.

**Comment by genderneutralnoun** [comment]
Sorry for the absence - been having some medical stuff going on.

> I'm not sure what you mean by that.

In the README, it's written that you can use the plasmoid "as part of the system tray Plasmoid". That is how I wish to use the Plasmoid. I don't want it to be pinned to my taskbar like my clock Plasmoid (or "widget"), I want it to vanish if I choose to quit Syncthing for whatever reason, and to be in line with my other tray icons, i.e. for Discord, Bitwarden, and Steam. In the past, when I had installed both the plasmoid and the standalone tray app, I had two Syncthing icons in my system tray, which I was then able to resolve by setting a setting to only show the Plasmoid version of the tray icon. I would prefer to use the Plasmoid version of the tray icon since it properly shows as a pop-up on my system, instead of always appearing in the center of my desktop as the standalone tray app does. 

> You can also uninstall `syncthingtray-qt6` if you only need the Plasmoid on that system.

I did actually try that - however, not only does the plasmoid not show up in the tray when uninstall `syncthingtray-qt6`, if I try to add it as a widget via right click on task bar -> Add Widgets..., then click on it, it crashes KDE.

Hopefully I've helped clear up at least some confusion.

**Comment by Martchus** [comment]
The way you want to configure it is basically how most people (including me) configure it so this should normally be possible and work. Note that there's no setting to prefer the Plasmoid version. You simply don't (auto)start the standalone version for not having it around.

What you described in the last paragraph obviously shouldn't be the case. Without further details about the crash I cannot help, though.

For me it generally works under openSUSE Tumbleweed and Arch Linux as described in the README and I cannot support or help with any Fedora-specifics if they might be important. Maybe another Fedora user can help with that.

**Comment by genderneutralnoun** [comment]
Okay, I think I got mixed up a little. The setting I was referring to is probably this, from the readme:
> Whether the Plasmoid is shown as part of the system tray Plasmoid can be configured in the settings of the system tray Plasmoid.
I would do this, but, the Syncthing plasmoid simply does not show up in my system tray. ...Oh. Well _that's_ weird. Apparently the system tray entry that is the actual plasmoid (it shows up under System Services) had been forcibly hidden. I feel like an idiot now haha.

**Comment by Martchus** [comment]
Supposedly in your case a surplus empty/disabled entry for the Plasmoid is shown as well. This definitely doesn't help to make it less confusing. (See https://github.com/Martchus/syncthingtray/issues/239 for this issue.)

If it works for you I'd close this issue then.
