### ISSUE TITLE
Dolphin integration not working on Arch

### ISSUE THREAD

**Issue by wigneyliam** [Martchus/syncthingtray#28]
Hey,

I've installed this on Arch from the aur with a pretty standard KDE install, kio is also installed. 

When I open dolphin the first time I right click I can see the option for syncthing how ever upon clicking it the option disappears
 until I launch a new instance of dolphin. Hovering over it also doesn't give the menu options shown in the screenshot.

I'm not to sure how to debug this so any pointers would be great!

Thanks!

**Comment by Martchus** [comment]
Likely it is unable to connect. The Dolphin menu just attempts to read your local Syncthing config file to figure the address/port and credentials. I suppose I'll have to improve this so you can configure it like the tray icon. And I should also add the "internal errors" dialog from the tray to it.

However, there are ways to debug: 
* Set the environment variable `KIO_SYNCTHING_LOG_STATUS=1`; the connection status should be logged to stderr.
* https://github.com/Martchus/syncthingtray/blob/master/fileitemactionplugin/testing.md

**Comment by Martchus** [comment]
I have looked into the code again and there's actual debug output for the case the config can not be found: https://github.com/Martchus/syncthingtray/blob/master/fileitemactionplugin/syncthingfileitemaction.cpp#L200

So do you get any of these messages?

**Comment by wigneyliam** [comment]
Hey sorry I didn't get any notifications for this, I'll have a look now!

**Comment by wigneyliam** [comment]
As of updating yesterday to the latest -git it's working, I build it normally to test if the lastest worked before trying to do a debug build but yeah I don't know if it's worth it now that it's working. 

Thanks for your help and the software! It's one of the reasons I prefer Plasma!
