### ISSUE TITLE
Make arch linux updateable again ("installing boost-libs (1.86.0-1) breaks dependency 'libboost_filesystem.so=1.83.0-64' required by syncthingtray-qt6")

### ISSUE THREAD

**Issue by financelurker** [Martchus/syncthingtray#281]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [x] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**
Yes, for arch linux. As of today in the arch pacman repo there are new dependency versions for the boost libraries:
```console
11  extra/boost                 1.83.0-9  -> 1.86.0-1
10  extra/boost-libs            1.83.0-9  -> 1.86.0-1
```
But a pacman update shows the following error:
```console
installing boost-libs (1.86.0-1) breaks dependency 'libboost_filesystem.so=1.83.0-64' required by syncthingtray-qt6
```

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Eg. I'm always frustrated when […]
I am frustrated since I cannot update my arch system anymore... :)

**Describe the solution you'd like**
I guess the solution would be to make syncthingtray-qt6 also work with the newer boost-libs version?

**Describe alternatives you've considered**
I could try to exclude the boost updates, but then there's also the following hint:
```console
 -> Excluding packages may cause partial upgrades and break systems
```
And since I need that machine also for earning money I cannot risk to have a broken system for now...

**Comment by financelurker** [comment]
Okay... Interestingly enough: I've removed syncthingtray-git from that machine and installed syncthingtray-qt6 AUR package it now works...?

**Comment by Martchus** [comment]
The packages need to be rebuilt. Please read the comments on the AUR about that. 

The Git package hasn't been rebuilt yet because it currently doesn't build. No need to file a bug report, I'll just have to adapt tests to recent changes.

**Comment by hownioni** [comment]
Hey but how do I rebuild the package against boost if it doesn't let me install it. I've searched how to do it the clean way as you say but I keep failing and haven't found any helpful info so I'm forced to do it the dirty way as you say. Maybe it would be better if you just included a how-to guide because a lot of the userbase of the program just uses an AUR helper and expect everything to work and I imagine you get these kinds of issues opened again and again, maybe doing that would stop it from happening further.

**Comment by financelurker** [comment]
So, what I did was:
1. yay -R syncthingtray-git (remove it)
2. pacman -Syyuu (update packages)
3. yay -S syncthingtray-qt6 (rebuild and install)

And in step 3 I told yay to clean/fresh build it. That worked for me, and I guess that when syncthingtray-qt6 built again afterwards it was then using the updated boost lib version. I hope that helps, @hownioni

**Comment by hownioni** [comment]
@financelurker thank you, that's what I ended up doing, I was just mad I couldn't do it the "clean" way

**Comment by Martchus** [comment]
The clean way is to use makechrootpkg which is documented in the Arch Wiki: https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot
