### ISSUE TITLE
Tray menu position adjustment

### ISSUE THREAD

**Issue by Balot0x00** [Martchus/syncthingtray#290]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**
windows10 x64

**Is your feature request related to a problem? Please describe.**
As you can see, this is a full screenshot of my desktop, and in the top right corner of the screenshot is the UI of the  SyncthingTray

 menu.

But the problem I have is that since I have the windows taskbar at the top of the screen and hidden by default.

When I open the SyncthingTray menu and want to close it, I can't click on the button further up, so I have to reopen the tray menu every time until I can click on the “Close” button.
(trans by deepl)
![image](https://github.com/user-attachments/assets/84dfb6fb-f6b7-4f59-b0a6-ecba538578c1)

**Describe the solution you'd like**
If possible, users can customize the location of the tray menu display.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Martchus** [comment]
English please…

**Comment by Martchus** [comment]
But how did you get all these letters there? Are you proposing localization for the website? I'm afraid that won't be immediately doable because it needed to be internationalized first - so far all text is hard-coded in English.

**Comment by Martchus** [comment]
Note that there haven't been any long-term contributors for translations of Syncthing Tray. So I assume there will be no difference when it comes to the website. So the effort of internationalizing it will likely be in vain. So I'm not going to do it. Anybody is welcome to contribute, though. Just don't pull-in any frameworks or big libraries for that. I'd like to keep the code of the website as simple as possible.

**Comment by Martchus** [comment]
About the positioning issue: Checkout the appearance settings. You can specify the window position manually. I would recommend using a popup window, though. This way the window closes simply by clicking somewhere else.

**Comment by Balot0x00** [comment]
> English please…

If possible, users can customize the location of the tray menu display.
I'm sorry, I thought there was a localization worker on the project.


> But how did you get all these letters there? Are you proposing localization for the website? I'm afraid that won't be immediately doable because it needed to be internationalized first - so far all text is hard-coded in English.

found this project from  Google search


> Note that there haven't been any long-term contributors for translations of Syncthing Tray. So I assume there will be no difference when it comes to the website. So the effort of internationalizing it will likely be in vain. So I'm not going to do it. Anybody is welcome to contribute, though. Just don't pull-in any frameworks or big libraries for that. I'd like to keep the code of the website as simple as possible.

Yeah, I can understand that.


> About the positioning issue: Checkout the appearance settings. You can specify the window position manually. I would recommend using a popup window, though. This way the window closes simply by clicking somewhere else.

emmmm i see, Then there's no problem with this setup, thinks
![image](https://github.com/user-attachments/assets/1d079aab-d313-42ed-af31-3e8829893068)
