### ISSUE TITLE
Support Fedora 41 in OBS

### ISSUE THREAD

**Issue by SirFritz** [Martchus/syncthingtray#292]
Hi.

Fedora 41 released a week ago but OBS currently has no packages available for it.  It would be great to support the new release.

Thanks.

**Comment by Martchus** [comment]
Fedora 41 is not available on OBS yet via the "Add from distribution …" button - which is the user friendly workflow to add additional repositories there. So I added Fedora 41 by editing the project config manually. I hope this has not any problematic side effects. Packages are building now.

> Fedora 41 released a week ago …

I'm not a Fedora user and don't follow their releases. If you want me to add the repository as soon as possible don't wait a week to create an issue here :-)
(Of course OBS might not have the repo immediately so there might still be some delay.)

**Comment by Martchus** [comment]
The repo doesn't show up on https://software.opensuse.org/download.html?project=home:mkittler&package=syncthingtray but it has been populated, see https://download.opensuse.org/repositories/home:/mkittler/Fedora_41/x86_64/. So you can add it was `https://download.opensuse.org/repositories/home:mkittler/Fedora_41/home:mkittler.repo`.

**Comment by SirFritz** [comment]
Thanks, I waited a week because it wasn't urgent for me and I'm sure you're busy yourself.
