### ISSUE TITLE
Portable mode and autostart do not work together

### ISSUE THREAD

**Issue by AndrewSav** [Martchus/syncthingtray#295]
**Relevant components**
* [X] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [X] Backend libraries

**Environment and versions**
![2024-11-13_18-36-05](https://github.com/user-attachments/assets/33fd54b1-a6c2-4a22-9a71-f1c06f666a0c)
* Operating system (name and version): Windows 11

**Bug description**
When the program starts via the autostart option, `syncthingtray.ini` placed directly next to the executable is ignored.

**Steps to reproduce**
Put an empty `syncthingtray.ini` next to the execuatable. Select "Start the tray icon when the desktop environment launches" option (see the screenshot below. Save and reboot. Observe that `syncthingtray.ini` from `AppData` is used.

**Expected behavior**
I expect the program to use `syncthingtray.ini` placed directly next to the executable.

**Screenshots**
![image](https://github.com/user-attachments/assets/7e4cfc13-6f50-4fc6-95ec-2e23d24f51f4)

**Additional context**
When Windows runs a program via `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run` the current folder is set to `System32`. It appears that `qtutilities` instead of detecting the executable path and checking its folder relies on the current folder instead which breaks down if the program was not started from its folder, as the case is with autostart option.

This can be considered a feature request if one would like to insist that portable mode is not meant to be used with autostart. Some package managers ([scoop](https://github.com/ScoopInstaller/Scoop)) install programs in portable mode by default to support multi-user environments which causes unexpected behaviour.

**Comment by Martchus** [comment]
This should be fixed within qtutilities. I only tested it under GNU/Linux so far.

**Comment by AndrewSav** [comment]
@Martchus thank you. If you could ping this issue when it makes to the next exe build that would be much appreciated.

**Comment by Martchus** [comment]
You can simply subscribe to release notifications on GitHub. I could also provide a development build for Windows later/tomorrow if you already want to test it out.

**Comment by Martchus** [comment]
Development build of the latest version: https://martchus.dyn.f3l.de/repo/arch/ownstuff-experimental/os/x86_64/mingw-w64-syncthingtray-qt6-1.6.4-1-any.pkg.tar.zst

You can extract it with e.g. bsdtar. The executables with `-static` suffix are the relevant ones.

**Comment by AndrewSav** [comment]
This seems to work, thank you for the fix. (Windows Explorer extracts the archive just fine)

**Comment by Martchus** [comment]
Thanks for testing. (Explorer can now really extract these archives. I suppose sometimes Microsoft actually adds useful features after all.)
