### ISSUE TITLE
[Windows 10] Saving config file does nothing

### ISSUE THREAD

**Issue by Manuel-S** [Martchus/syncthingtray#30]
I got the current version on a new PC and set up the tray to connect to syncthing and changed the language, everything seemed to be fine, but whenever I restart the application, I always get the "first run" window again and no configuration is retained.

The application does not seem to write any kind of config file when I press OK/Apply.

I tried with the previous binary (0.8.3) and not only did it automatically pick up the syncthing config, it also retained the settings on restart.

After having run the older binary, starting 0.8.4 now also loads the config correctly and also saves changes, so I guess there must be a problem creating the config file if it doesn't exist in 0.8.4.

**Comment by Martchus** [comment]
That's a strange issue. I can't remember any changes which would cause that. I need to test that myself.
