### ISSUE TITLE
Icons are not scaled correctly when 2 different scales are set in the system

### ISSUE THREAD

**Issue by jintaxi** [Martchus/syncthingtray#300]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Android app or mobile UI in general
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.6.3, IDK, IDK
* Qt version: 6.8.0
* C++ compiler (name and version): IDK
* C++ standard library (name and version): IDK
* Operating system (name and version): WIndows 24H2 26100.1742

**Bug description**
I have two monitors: a laptop -- 16" 16:10 2560x1600 and an external monitor -- 27" 16:9 2560x1440. If you set the system scaling to 150% on the laptop screen (Windows recommendation), then the tray icons change their style and size, because of this they do not fit into the allotted fields (screenshot 1). If you set the scale to 100% on the laptop monitor, then the icons have the correct scale (screenshot 2)

**Steps to reproduce**
1. Change system scaling on the laptop monitor

**Expected behavior**
Icons should adjust to the scaling of the main display (in my case - 100%).

**Screenshots**
Laptop Screen 150%, external monitor 100%
<img width="399" alt="{5A05EAFE-9AE5-4DE7-BA82-D37165BACB26}" src="https://github.com/user-attachments/assets/2e5f19e7-0bb4-4de9-9868-0ee8264c848a">

Laptop Screen 100%, external monitor 100%
![{23364311-EC86-4775-9E3A-A191263E3584}](https://github.com/user-attachments/assets/cad53205-e86a-4681-8ed4-753495d4a8e2)

**Additional context**
Maybe this is a problem with Windows itself, because there is also a screenshot application (standard, Win+ Shift + S) also has a different scale of irony.

**Comment by Martchus** [comment]
Looks like you're using the setting "Prefer icons from theme over ForkAwesome icons (needs restart to apply)". Does this also happen when disabling this setting?

I definitely tested this in the past on Windows 11 and it worked (with "Prefer icons from theme over ForkAwesome icons (needs restart to apply)" disabled, though). Maybe a regression.

I will not be able to work on this issue before the next release but please test the next release if it comes out. I had to change relevant code and maybe this also fixes the problem.

**Comment by jintaxi** [comment]
Wow. It really worked. I just turned off this setting (ForkAwesome icon) and it really started to scale correctly. Thank you very much!

**Comment by Martchus** [comment]
Well, it is still a problem I'll have to investigate because this setting shouldn't break scaling. However, under Windows there's no native icon theme anyway so I guess it isn't very important so we can keep this closed. I'll have to re-visit the code of this feature for #282 anyway.
