### ISSUE TITLE
Update failed from winget (Uniget-UI), lack of proper privileges ?

### ISSUE THREAD

**Issue by LbqpdL** [Martchus/syncthingtray#303]
Hello,
I installed syncthingtray from winget repository, through the uniget-UI interface:
![image](https://github.com/user-attachments/assets/8c8a7db9-b456-486f-a239-5b9b5783a5f0)

Today the update failed with the following error:

> Starting package update operation for package id=Martchus.syncthingtray with Manager name=Winget
> Given installation options are <InstallationOptions: SkipHashCheck=False;InteractiveInstallation=False;RunAsAdministrator=False;Version=;Architecture=;InstallationScope=;InstallationScope=;CustomParameters=;RemoveDataOnUninstall=False>
> Process Executable     : C:\Users\username\AppData\Local\Microsoft\WindowsApps\winget.exe
> Process Call Arguments :  update --id "Martchus.syncthingtray" --exact --source winget --accept-source-agreements --disable-interactivity --silent  --include-unknown --accept-package-agreements --force
> Working Directory      : C:\Users\username
> Process Start Time     : 12/12/2024 17:53:13
> 
> Trouvé Syncthing Tray [Martchus.syncthingtray] Version 1.6.4
> La licence d’utilisation de cette application vous est octroyée par son propriétaire.
> Microsoft n’est pas responsable des paquets tiers et n’accorde pas de licences à ceux-ci.
> Le code de hachage de l’installation a été vérifié avec succès
> Extraction des archives...
> Extraction de l’archive réussie
> Début de la désinstallation du paquet...
> Une erreur inattendue s'est produite lors de l'exécution de la commande :
> remove: Acc�s refus�.: "C:\Users\username\AppData\Local\Microsoft\WinGet\Packages\Martchus.syncthingtray_Microsoft.Winget.Source_8wekyb3d8bbwe\syncthingtray-1.6.3-x86_64-w64-mingw32.exe"
> Échec du programme de désinstallation avec le code de sortie : 0x8a150003 : Échec de l’exécution de la commande
> Process Exit Code      : -1978335145

Note : I was not asked for admin privileges

OS: Windows 11 Pro
![image](https://github.com/user-attachments/assets/bb7412be-a080-470c-9788-d27f9444aeee)

Syncthing installed alongside with syncthingtray
![image](https://github.com/user-attachments/assets/8f76ed05-0c8f-4563-8c3f-5a4eaabe3735)

**Comment by Martchus** [comment]
Please report issues specific to community provided packaging on the relevant downstream bugracker. I am not using winget myself and heared of Uniget-UI for the first time so cannot help with that.

**Comment by LbqpdL** [comment]
Opened a ticket here: https://github.com/marticliment/UniGetUI/issues/3069

"I am afraid that, since this issue can also be caused by winget.exe, the cause is not UniGetUI, but rather WinGet. You may want to contact the package publisher (in this case Martchus) to let them know that their package can not be installed/upgraded properly"

**Comment by Martchus** [comment]
I'm not the publisher of that package, though. As mentioned, the winget package is community provided and I don't even use winget myself. 

If you can come up with steps to reproduce the problem that do *not* involve winget you can reopen this issue but otherwise this is really the wrong issue tracker. 

If an upstream change is required to make winget packaging work you can open a feature request. You need to describe the feature in a generic way that doesn't require knowledge of winget specifics, though.

**Comment by LbqpdL** [comment]
OK, thank you for your support, I will seek the best issue tracker to raise this issue.
Best regards,

**Comment by LbqpdL** [comment]
Hello, I was able to circumvent the issue by killing the running process before applying the update.

Steps:

- Quit the running process (kill the process through Windows Manager, or if you have enabled the system tray icon during the first install, quit the process from there)
- Launch the update from Uniget-UI

**Comment by Martchus** [comment]
Ok, that might be helpful to anyone finding this issue.

Note that Syncthing Tray can be started with `--replace` which might be something the winget packager could utilize. So you could ask for that on the issue tracker of that package. (This would be a feature request about the concrete winget package and *not* about Syncthing Tray and UniGetUI.)

**Comment by LbqpdL** [comment]
Request to winget package maintainers opened here:
https://github.com/microsoft/winget-pkgs/issues/199789
