### ISSUE TITLE
Suggestion: New status to indicate that all remotes are disconnected

### ISSUE THREAD

**Issue by abryant** [Martchus/syncthingtray#306]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Android app or mobile UI in general
* [ ] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**
It doesn't seem to be, but I've only tried the Plasmoid.

**Is your feature request related to a problem? Please describe.**
I've just started using Syncthing, and it seems weird that the tray icon can't show me whether remote devices are disconnected, even when I can see they they're disconnected by opening up the panel.

I've been reading a bit of the code, and initially thought that the "Disconnected" status was meant to mean this, but on closer inspection it seems to just mean that the plasmoid is disconnected from Syncthing. The relevant code seems to be around here:
https://github.com/Martchus/syncthingtray/blob/bf4132a6a05000a310a4ef602f512ce6dc83344d/syncthingconnector/syncthingconnection.cpp#L1180

**Describe the solution you'd like**
Add an option to make the main icon for the plasmoid change when all remotes are disconnected. This would be an extra checkbox under "Connection -> Overall status" like "All remotes are disconnected".

**Describe alternatives you've considered**
Clicking on the icon manually whenever I want to be sure that everything has been synced to my server.

**Additional context**
![SyncthingTray-StatusIcon](https://github.com/user-attachments/assets/9aaa9c75-bdfd-4963-bbed-6a38f4d51728)

**Comment by Martchus** [comment]
This is something I have already on my mind for a long time but I've never come to implement it. Maybe it is time :-)

This should actually not be that difficult to implement considering the status computation is already configurable. Maybe it makes sense to come up with a distinct "badge icon" for this, though.

> I've been reading a bit of the code, and initially thought that the "Disconnected" status was meant to mean this, but on closer inspection it seems to just mean that the plasmoid is disconnected from Syncthing. The relevant code seems to be around here:

Yes, that's how it is.

**Comment by Martchus** [comment]
I pushed a commit implementing this on the master branch. If configured it now shows an "X" emblem in case there's no remote device connected.

**Comment by abryant** [comment]
That's amazing, I wasn't expecting it anywhere near this quickly! I've rebuilt from master and it's working great, thank you!
