### ISSUE TITLE
Systemd unit cannot be found

### ISSUE THREAD

**Issue by gringo-go-go** [Martchus/syncthingtray#31]
First of all - thank you for that great app!

I just keep wondering: where is the systemd unit for syncthing instance? Systemctl shows that it's disabled, but tray app keeps the syncthing instance alive (even after reboot). It's probably not even an issue, but I didn't know where to ask that question.

![image](https://user-images.githubusercontent.com/17615974/52532421-35bb0680-2d25-11e9-9cb4-c199383eb5f1.png)

![image](https://user-images.githubusercontent.com/17615974/52532429-47041300-2d25-11e9-9504-d8d5fb706b8f.png)

**Comment by gringo-go-go** [comment]
Oh, systemd list-unit-files --user. Sorry to bother!

**Comment by Martchus** [comment]
No problem. Maybe this should be noted the GUI.
