### ISSUE TITLE
CMake errors on (k)ubuntu - testtarget module and Qt5LinguistTools

### ISSUE THREAD

**Issue by mojolo** [Martchus/syncthingtray#34]
Hello. I tried to build on kubuntu dingo v19.04 but received the following 2 errors. Do you have any recommendations? Thanks for your help.

* **Error 1: c++utilities - TestTarget module**
```
CMake Warning at /home/mojo_lo/build/syncthingtray/sources/c++utilities/cmake/modules/TestTarget.cmake:40 (message):
  Unable to add test target because cppunit could not be located.
```

* **Error 2: qtutilities - Qt5LinguistTools**
```
CMake Error at /home/mojo_lo/build/syncthingtray/sources/qtutilities/cmake/modules/QtConfig.cmake:271 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.
```

**The build commands I executed were:**
```
cmake -DWEBVIEW_PROVIDER:STRING=webkit -DJS_PROVIDER:STRING=script \                                     
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX="/usr/local" \
      $SOURCES/subdirs/syncthingtray
```

**Here's the full terminal output:**
```
-- Using iconv from the standard library for target c++utilities.
-- Using std::fstream for NativeFileStream
-- Linking c++utilities against special library for std::filesystem support is not required.
-- Configuring project c++utilities
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- For the check target to work, it is required to call enable_testing() on the source directory root.
-- Using template for global.h from own (c++utilities) source directory.
-- Using template for version.h from own (c++utilities) source directory.
-- Using template for Config.cmake from own (c++utilities) source directory.
-- Using template for template.pc from own (c++utilities) source directory.
-- Checking for one of the modules 'cppunit>=1.13.0'
CMake Warning at /home/mojo_lo/build/syncthingtray/sources/c++utilities/cmake/modules/TestTarget.cmake:40 (message):
  Unable to add test target because cppunit could not be located.
Call Stack (most recent call first):
  /home/mojo_lo/build/syncthingtray/sources/c++utilities/CMakeLists.txt:194 (include)


-- Using template for doxygen from own (c++utilities) source directory.
-- Generating target for generating API documentation for c++utilities with Doxygen
-- Using template for config.h from own (c++utilities) source directory.
-- D-Bus notifications enabled
-- Configuring project qtutilities
-- Using default CXX11 ABI (not forcing old CX11 ABI).
-- For the check target to work, it is required to call enable_testing() on the source directory root.
-- Building with Qt Widgets GUI.
-- Building WITHOUT Qt Quick GUI.
-- Project has D-Bus interface declarations which will be processed.
-- Linking qtutilities against Qt 5 module Qt5::Gui.
-- Linking qtutilities against Qt 5 module Qt5::Widgets.
-- Linking qtutilities against Qt 5 module Qt5::Core.
-- Linking qtutilities against Qt 5 module Qt5::DBus.
-- qmake variable QT_INSTALL_TRANSLATIONS is /usr/share/qt5/translations
-- Project has translations which will be released.
CMake Error at /home/mojo_lo/build/syncthingtray/sources/qtutilities/cmake/modules/QtConfig.cmake:271 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  /home/mojo_lo/build/syncthingtray/sources/qtutilities/CMakeLists.txt:188 (include)


-- Configuring incomplete, errors occurred!
See also "/home/mojo_lo/build/syncthingtray/build_dir/CMakeFiles/CMakeOutput.log".
```

**Comment by Martchus** [comment]
Error 1 is just a warning. You can ignore it if you're not intestested in running the testsuite. Otherwise, install CppUnit.

To fix error 2 you need to install [qttools](https://code.qt.io/cgit/qt/qttools.git/).

I recommend to use `-DWEBVIEW_PROVIDER:STRING=webengine -DJS_PROVIDER:STRING=qml` instead of using those deprecated modules. Of course you need to install Qt WebEngine and Qt Qml for this to work.

Note that the install prefix specified via `-DCMAKE_INSTALL_PREFIX="/usr/local"` is likely not writeable by your regular user account. So you needed to run `make install` as root. I don't recommend that. Better install it somewhere in your home directory.

By the way, if you have found out how the required packages are called under Ubuntu you can share the list. Other users will likely be thankful. Note that you need to install devel packages as well because obviously for the build header files and CMake files are required.

**Comment by mojolo** [comment]
Thanks for the quick response and tips! This cmake commands worked on Kubuntu 19.0.4:

```
cmake -DWEBVIEW_PROVIDER:STRING=webengine -DJS_PROVIDER:STRING=qml \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_INSTALL_PREFIX="/home/<username>/.local/" \
$SOURCES/subdirs/syncthingtray
```

I think these packages will ensure that all dependencies are satisfied on Kubuntu 19.0.4. There could be others but I had most of the `Qt` and `KF5` packages either 1) automatically installed with Kubuntu, or 2) manually installed from previous package builds.
```
apt install qtbase5-dev qtbase5-dev-tools qtdeclarative5-dev qtdeclarative-dev-tools libqt5svg5-dev qttools5-dev qttools5-dev-tools qtwebengine5-dev qtwebengine5-dev-tools plasma-workspace-dev libkf5kio-dev
```
On ubuntu gnome desktop, all of the packages below may be needed. Probably isn't a likely use-case, but here are the names of all the packages I could identify:

### > Qt
---

**Qt5::Base**: `qtbase5-dev qtbase5-dev-tools`

**Qt5::Core**: `libqt5core5a`

**Qt5::Concurrent**: `libqt5concurrent5`

**Qt5::DBus**: `libqt5dbus5`  
Possibly these too: `libdbusmenu-qt5-2 libdbusextended-qt5-1 libdbusextended-qt5-dev`

**Qt5::Declarative**: `qtdeclarative5-dev qtdeclarative-dev-tools`

**Qt5::Gui**: `libqt5gui5`

**QT5::LinguistTools**: `qttools5-dev qttools5-dev-tools`

**Qt5::Network**: `libqt5network5`

**QT5::QML**: `libqt5qml5 qml-module-qtwebengine`  
Possibly these too: `libqt5webchannel5 libqt5webchannel5-dev qml-module-qtwebchannel qml-module-qtwebview qml-module-qtwebsockets`

**Qt5::Svg**: `libqt5svg5-dev`

**Qt5::WebEngineWidgets**: `qtwebengine5-dev qtwebengine5-dev-tools`

**Qt5::Widgets**: `libqt5widgets5`

### > For Plasma Integration
---

**KF5::Plasma**: `plasma-workspace-dev`
Will automatically install these dependencies:  `plasma-workspace libkworkspace5-5 plasma-integration`

**KF5::KIOCore**: `libkf5kio-dev`
Will automatically install these dependencies: `kio libkf5kiocore5 libkf5kiogui5`

**KF5::KIOFileWidgets**: `libkf5kiofilewidgets5`

**KF5::KIOWidgets**: `libkf5kiowidgets5`
Possibly this too: `libkf5widgetsaddons-dev`

**KF5::KIONTLM**: `libkf5kiontlm5`

**Comment by Martchus** [comment]
Thanks for providing the list of packages. Some are not required and the devel packages likely pull the runtime libs anyways. But this should help other Ubuntu users with compiling. Maybe somebody will finally create a package. I could give OBS another try now that I know all package names for the dependencies :-)
