### ISSUE TITLE
Syncthing Tray on macOS

### ISSUE THREAD

**Issue by yan12125** [Martchus/syncthingtray#37]
This is a follow-up of https://github.com/Martchus/cpp-utilities/pull/12. I expect the discussion quite long and out-of-scope of cpp-utilities, so I open an issue here.

First let me put some words for https://github.com/Martchus/cpp-utilities/pull/12#issuecomment-511097420

> You could also share a screenshot

Here you go :)

![螢幕快照 2019-07-13 17 34 51](https://user-images.githubusercontent.com/1937689/61170015-2c64ed00-a596-11e9-9d3f-c29e68d77264.png)

It looks good overall. The most outstanding issue might be that when I left-click or right-click on the tray icon, both the menu and the widget pop up.

> Did CMake create the "bundle" correctly?

Nope. syncthingtray can be started from the terminal (e.g., `/Applications/syncthingtray.app/Contents/MacOS/syncthingtray`) but not via launchd (e.g., `open /Applications/syncthingtray.app` or open it from Finder). The issue appears to be incomplete Info.plist. I managed to get syncthingtray.app working by patching syncthingtray:
```Diff
diff --git tray/CMakeLists.txt tray/CMakeLists.txt
index 44738df..31d6d4b 100644
--- tray/CMakeLists.txt
+++ tray/CMakeLists.txt
@@ -111,3 +111,13 @@ include(ConfigHeader)
 
 # create desktop file using previously defined meta data
 add_desktop_file()
+
+if(APPLE)
+    set_target_properties(${META_TARGET_NAME} PROPERTIES
+        MACOSX_BUNDLE_BUNDLE_NAME ${META_TARGET_NAME}
+        MACOSX_BUNDLE_GUI_IDENTIFIER ${META_TARGET_NAME}
+        MACOSX_BUNDLE_BUNDLE_VERSION ${META_APP_VERSION}
+        MACOSX_BUNDLE_LONG_VERSION_STRING ${META_APP_VERSION}
+        MACOSX_BUNDLE_SHORT_VERSION_STRING ${META_APP_VERSION}
+    )
+endif()
```

There are some other issues:

* Currently I use an older commit https://github.com/Martchus/syncthingtray/commit/7f307822dfefdbcf39180e10c6a12508adda23b4. https://github.com/Martchus/syncthingtray/commit/2112b003470d901c2729eeb81a30be0dbe87b2ef fails to build on macOS. The first error message is:
```
/Users/yen/Projects/syncthingtray/widgets/settings/settings.cpp:112:39: error: member access into incomplete type
      'Data::SyncthingConnection'
    const auto isRelevant = connection.isLocal();
                                      ^
/Users/yen/Projects/syncthingtray/widgets/settings/./settings.h:27:7: note: forward declaration of 'Data::SyncthingConnection'
class SyncthingConnection;
      ^
```
Looks like `LIB_SYNCTHING_CONNECTOR_SUPPORT_SYSTEMD` is not defined and thus syncthingconnection.h is not included.

* Autostart is not supported.
* There are icons in Docker and the Command-Tab switcher if syncthingtray is running. I expect them hidden. `LSUIElement` key in Info.plist seems the solution [2].

[1] https://developer.apple.com/documentation/xcode_release_notes/xcode_11_beta_3_release_notes
[2] https://developer.apple.com/documentation/bundleresources/information_property_list/lsuielement

**Comment by Martchus** [comment]
> It looks good overall. The most outstanding issue might be that when I left-click or right-click on the tray icon, both the menu and the widget pop up.

That's bad, indeed. And the screenshot speaks for itself. So I'd call it usable but far from nice. Unfortunately tweaking this requires a likely a lot of "playing around" so I'm not able to do it (have no Mac).

> The issue appears to be incomplete Info.plist. I managed to get syncthingtray.app working by patching syncthingtray

Nice. However, I'd prefer to add this patch to `AppTarget.cmake` in c++utilities so all my applications will benefit from it. Your diff is already using the right variable names anyways :-)

> Currently I use an older commit 7f30782. 2112b00 fails to build on macOS.

It also fails for my Windows builds and it should fail everywhere when systemd support is disabled. I'm going to fix this today.

>  Autostart is not supported.

I already distinguish between GNU/LInux and Windows here. Adding a 3rd code path should be easy. It just needs to be implemented.

> There are icons in Docker and the Command-Tab switcher if syncthingtray is running. I expect them hidden. LSUIElement key in Info.plist seems the solution [2].

Since Info.plist is generated by CMake that would likely need to be adjusted via CMake. Hopefully there's a not completely hacky way to do it.

---

Thanks for all the feedback.

**Comment by yan12125** [comment]
> That's bad, indeed

Looking at Qt's tray icon implementation on macOS [1], there are two issues:

* QPlatformSystemTrayIcon::MiddleClick is passed when the middle button is clicked, and QPlatformSystemTrayIcon::Trigger for all other buttons (e.g., both left- and right-clicks).
* The context menu is shown no matter which button is clicked.

I guess the issue can only be fixed inside Qt. Before the issue is fixed, how about not setting the context menu for the tray icon on macOS? All options, except "Close", in the context menu are also available in the widget.

> It also fails for my Windows builds and it should fail everywhere when systemd support is disabled. I'm going to fix this today.

Thanks! I can confirm the latest commit builds fine.

For other issues, I will give it a try when I find time.

[1] https://github.com/qt/qtbase/blob/v5.13.0/src/plugins/platforms/cocoa/qcocoasystemtrayicon.mm#L393-L411

**Comment by Martchus** [comment]
> I guess the issue can only be fixed inside Qt.

That's unfortunate. I guess not setting the context menu is an acceptable workaround. The close button can be shown in the tray widget in this case. The alternative is implementing this on our own like I did with the DBus-Notifications for GNU/Linux where the Qt support is very limited.

> For other issues, I will give it a try when I find time.

Thanks

**Comment by Martchus** [comment]
I'm going to improve 2 points this evening - unless you tell me you're already in the progress:

* Add a configuration with no context menu and everything on the tray widget. That configuration would be the default under Mac.
* Set the `MACOSX_BUNDLE_` properties (like in your code snipped but in c++utilities).

**Comment by yan12125** [comment]
> Add a configuration with no context menu and everything on the tray widget

I simply disable it on macOS: https://gitlab.com/yan12125/macports-overlay/blob/master/www/syncthingtray-devel/files/patch-no-tray-menu.diff. An option will be better!

> Set the `MACOSX_BUNDLE_` properties

Something like this? https://gitlab.com/yan12125/macports-overlay/blob/master/devel/cpp-utilities-devel/files/patch-macosx-bundle.diff

**Comment by Martchus** [comment]
For simplicity I would make it a compile time option. But I don't like `#ifndef Q_OS_MAC` because that doesn't allow to test this configuration on other platforms then Mac (without ugly temporary code adjustments).

> Something like this?

Exactly like this. You could open a PR if you like :-)

**Comment by yan12125** [comment]
> Exactly like this. You could open a PR if you like :-)

Oops I found my previous patch wrong. I've corrected that and opened https://github.com/Martchus/cpp-utilities/pull/13.

> For simplicity I would make it only a compile time option. But I don't like #ifndef Q_OS_MAC because that doesn't allow to test this configuration on other platforms then Mac (without ugly temporary code adjustments).

Got it! I assume it's better not to do the work by myself as you're much more familiar with the code base than me :)

**Comment by Martchus** [comment]
Implemented the `UNIFY_TRAY_MENUS` option which is now enabled by default under Mac OS: https://github.com/Martchus/syncthingtray/commit/708334443fab06cde962e0feb49bdf4177c5ccc1

**Comment by yan12125** [comment]
`UNIFY_TRAY_MENUS` is awesome! I've also created #38 for some other macOS-specific fixes/improvements.

Autostart and custom tray icon handling appear to involve writing non-trivial Objective-C codes. I may not be able to finish them in near future.

**Comment by Martchus** [comment]
Yes, custom tray icon support might be quite some effort (so it might not be worth it).

I would have expected that autostart is as simple as placing a file in some directory. Likely there's also a system provided way to add arbitrary applications to the autostart under Mac? Maybe you can also just add instructions for using it or trigger that dialog somehow.

**Comment by Martchus** [comment]
By the way, if the files in your repository under https://gitlab.com/yan12125/macports-overlay would be useful for other MacOS users it could be mentioned in README.md.

**Comment by yan12125** [comment]
> I would have expected that autostart is as simple as placing a file in some directory.

Ah you're right. I was originally looking at the implementation of syncthing-macos [1]. Turns out there is a simpler approach.

> By the way, if the files in your repository under https://gitlab.com/yan12125/macports-overlay would be useful for other MacOS users it could be mentioned in README.md.

That repository is for work-in-progress software. For syncthingtray, I plan to push it to the main MacPorts repository when the icon and the autostart feature are done. By that time users will be able to install syncthingtray with:
```
sudo port install syncthingtray-devel
```
I will propose a patch to extend README.md for MacPorts users then.

The `-devel` suffix indicates that the software is built from a commit on git-master of the upstream repo rather than a stable version. When a stable version of syncthingtray is out, I will switch to it.

[1] https://github.com/syncthing/syncthing-macos/blob/develop/syncthing/STLoginItem.m

**Comment by yan12125** [comment]
Gonna close this ticket as I consider the porting work is finished. Thank you very much for patience, kind suggestions and fast responses during the past two weeks! Thanks to good program structures, porting it to a new platform is relatively simple.
