### ISSUE TITLE
Please add support for launching syncthing-inotify

### ISSUE THREAD

**Issue by sez11a** [Martchus/syncthingtray#5]
I have been using qsyncthingtray on my Plasma 5 desktop for a while, and it's not as fully featured as this is. It does have one feature, though, that Syncthingtray doesn't: It can launch syncthing-inotify, which allows users to use the inotify mechanism rather than periodic scanning to determine changes in folders. 

Would it be possible for you to add another tab to the Startup section for syncthing-inotify, so both could be launched at the same time? 

Thanks!

**Comment by Martchus** [comment]
I implemented the startup of Syncthing only for Windows users because under Linux you usually start services using the init system. I could extend it, but starting other applications is actually not the purpose of the tray.

However, it would make sense to be able to add/remove watches directly from the tay. But maybe I have to implement watching myself for that (not sure how syncthing-inotify works because I never used it myself).

**Comment by sez11a** [comment]
Yeah, Syncthing is one of those funny cases where you can start it in the "desktop way" (a .desktop file in .config/autostart) for an individual user, or you could start it using systemd with a syncthing@.service file. If I'm using a tray utility, I prefer keeping systemd out of it. Plus you have, of course, those anti-systemd people. :-)  My distro of choice (Manjaro) offers an openrc edition (I don't use it; I'm just mentioning it because it seems relevant). 

Either way, adding support for launching syncthing-inotify would benefit Windows (and Mac) users too.

**Comment by Martchus** [comment]
I'll add it to the TODO list. Adding a clone of the already present Launcher page shouldn't be hard to implement.

Note that the tray can actually [utilize systemd](https://github.com/Martchus/syncthingtray#use-of-systemd). So it makes sense to start Syncthing with systemd when using it anyways. Additionally, systemd and probably also other init systems provide better logging than the tray.

**Comment by Martchus** [comment]
The second launcher tab to start inotify has been implemented: https://github.com/Martchus/syncthingtray/commit/3c2ce3e82f4c30c05227abd4d2db67fac6104299

**Comment by sez11a** [comment]
Thanks! Looking forward to seeing it!

**Comment by Martchus** [comment]
Has been released in 0.5.1 so I'm closing. Feel free to reopen if something is missing.
