### ISSUE TITLE
Gnome/Nautilus overlay icons

### ISSUE THREAD

**Issue by TechupBusiness** [Martchus/syncthingtray#56]
Hi, is it possible to support also gnome/nautilus overlay icons (Ubuntu)? 

Maybe the code of Syncthing GTK may help: https://github.com/syncthing/syncthing-gtk/blob/master/syncthing_gtk/nautilusplugin.py

And: https://www.hvoigt.net/dev/nautilus-extensions-tutor.html

The only feature which does not work in the GTK version is to mark ignored files/folders with a special icon (they get a normal "synced" overlay - but they are not synced).

**Comment by Martchus** [comment]
I don't use Gnome or Nautilus so there's not much incentive for me to do that. And given that a Nautilus plugin already exists I'm also wondering what the benefit of writing yet another Nautilus plugin would be. The comment at the top even claims "[...] but can be used independently". So this runs likely just fine alongside Syncthing Tray.

**Comment by Martchus** [comment]
If someone wants to contribute such a plugin based on the backend libraries provided by this repository I would of course be happy about that contribution.
