### ISSUE TITLE
Changed settings are lost when leaving session in some desktop environemnts

### ISSUE THREAD

**Issue by Martchus** [Martchus/syncthingtray#59]
I tested the following desktop environments:  
* Plasma 5: settings are saved as expected
* LXQt and plain Openbox session: settings are not saved

When stopping the application via Ctrl + C settings aren't saved as well but it would be nice if they would.

As a workaround the tray icon can be closed manually before leaving the session.

So it seems the following change does not work reliably across all desktop environments: https://github.com/Martchus/syncthingtray/commit/27f17fc94cd0b28e2c26d74c95d4270f30c8efbd

**Comment by Martchus** [comment]
worked around via https://github.com/Martchus/syncthingtray/commit/1a1b907f15c1101a41ecbfa3014b35fd2bb2d800

**Comment by sarpik** [comment]
Omg it works perfectly now, thank you so much @Martchus!

**Comment by Martchus** [comment]
You're welcome - it was basically just one line of code :-)
