### ISSUE TITLE
Syncthingtray does not display remote states correctly

### ISSUE THREAD

**Issue by XavierCLL** [Martchus/syncthingtray#62]
Hello,

First I wanted to thank you for the hard work in this awesome app and the integration with KDE is amazing...
I don't completely sure if this is a bug or not, but the states inside Synctrhingtray doesn't display remote states correctly base on the Syncthing web app. Look at this screenshot, that happened when I saved a big folder locally and Syncthing was uploading it to remote devices:

![syc_tray_remote_device](https://user-images.githubusercontent.com/11801453/75618083-9dedad80-5b1d-11ea-8e7a-1ebe27a390b6.png)

I think, not only the state of remote devices in the plasmoid should be fixed, the tray icon should show uploading or synchronizing status

**Comment by Martchus** [comment]
That's not a bug but something I simply haven't implemented yet. I have to admit that the user of the word "idle" is rather confusing.

---

Note that you can configure bright colors and custom Syncthing icon colors for a better look under dark themes.

It also seems that the icons have scaling issues. Not sure why that's the case.

**Comment by XavierCLL** [comment]
Thanks Martchus for the suggestion of the bright colors I set it and right now looks better. About the scaling issues is because I'm using HiDPI display (another bug or enhancement) if you want more info please ask me, I could be a tester of it

**Comment by Martchus** [comment]
I have implemented showing the remote completion. I need to give it a little bit more testing but it should be part of the next release.

**Comment by Martchus** [comment]
It should now behave like the official web UI (including all caveats).
