### ISSUE TITLE
Automatically reconnect after loosing connection to syncthing

### ISSUE THREAD

**Issue by doronbehar** [Martchus/syncthingtray#67]
Hi :)

1st of all, thank you for creating syncthingtray :+1: .

When I am using a flaky network, every once in a while Syncthingtray losses connection to Syncthing. Sometimes it's really because the WiFi connection is truly lost. I was wondering, whether it'd be possible to teach Syncthingtray to try to reconnect periodically to the default Syncthing instance, so I won't have to do that my self every time there's a network error.

**Comment by Martchus** [comment]
> Sometimes it's really because the WiFi connection is truly lost.

Unless you're connecting to a remote instance of Syncthing it should not disconnect in that case. The fact that it happens nevertheless is a [known bug](https://github.com/Martchus/syncthingtray#known-bugs) in Qt's bearer management which is not easy to workaround (Qt 6 will hopefully fix it).

> I was wondering, whether it'd be possible to teach Syncthingtray to try to reconnect periodically to the default Syncthing instance

Of course. The interval to reconnect can be configured for each connection individually within the settings.

**Comment by doronbehar** [comment]
Ohh.. Silly me that I've missed that README section and the settings option.. I thought I was the only one. Thanks for the quick response and best regards :).

**Comment by Martchus** [comment]
No problem, you're welcome :-)
