### ISSUE TITLE
Internal Error - Fails Continuously After VPN Connection

### ISSUE THREAD

**Issue by metal450** [Martchus/syncthingtray#69]
SyncThing Tray is up & running, and fantastic.  And if I connect to an OpenVPN server, it continues to work.  However, as soon as I *disconnect* from the VPN, SyncThing Tray begins repeatedly showing a notification with:

     SyncThing Tray - internal error. Unable to request Syncthing config: Network access is disabled.

The network is definitely not disabled, and I'm able to access the Syncthing web UI in the browser.  If I quit & re-launch SyncThing tray, it begins to work again (until the next time I connect to, and then disconnect from, a VPN).

*****
Using SyncThing Tray 0.10.9
SyncThing 1.5.0 64-bit
Kubuntu 20.04
KDE Plasma 5.18.5
Qt 5.12.8

I installed SyncThing itself via: https://apt.syncthing.net/
I installed SyncThing Tray via AppImage.  From its default configuration, the options I changed were:

* Tray->Insert values from local Syncthing configuration
* Tray->Apply connection settings and try to reconnect
* Tray->Connect automatically on startup
* Tray->Reconnect = 10000 ms
* Startup->Autostart->Start the tray icon when the desktop environment launches
* Startup->Syncthing launcher->Launch Syncthing when starting the tray icon

**Comment by Martchus** [comment]
It might be the same disconnection bug as mentioned here: https://github.com/Martchus/syncthingtray/blob/master/README.md#known-bugs

The bug in the README is about LAN discontents but VPN disconnects might cause it as well. I can try to exclude the bearer plugin from the AppImage.

**Comment by metal450** [comment]
Well, that bug says "...when the network connection goes down. The network connection must be restored or the tray restarted..." In this case, a VPN disconnect might represent a momentary "network connection goes down" - however, the error keeps repeating indefinitely thereafter, until the tray is explicitly quit & re-launched.  So the underlying bug might be the same - but it seems like it should be able to recover once the connection is back, without the need to manually quit & restart, no?

**Comment by Martchus** [comment]
> but it seems like it should be able to recover once the connection is back, without the need to manually quit & restart, no?

Maybe VPN connections screw Qt's bearer framework completely up. I've created an AppImage built from the latest master and *without* the bearer plugin: https://martchus.no-ip.biz/repo/experimental/appimage/syncthingtray-1591296626.027f320-Build72.1.glibc2.17-x86_64.AppImage

Does that work?

**Comment by metal450** [comment]
Yup, that appears to do it!  No error message, either on VPN connect or disconnect.

Is this a good AppImage to use instead, moving forward? Are there any negative ramifications to the removal?

**Comment by Martchus** [comment]
Then it is really just another variation of https://bugreports.qt.io/browse/QTBUG-60949. I'd expect no ramifications. Qt's bearer framework seems to bring more problems than it solves and for Syncthing Tray it shouldn't be relevant at all. I've also been suggested by Qt developers to simply remove the plugin.

**Comment by metal450** [comment]
Great! I'll keep using this appimage moving forward then - thanks for the quick turnaround :)

**Comment by Martchus** [comment]
You're welcome. The AppImage builds on OBS have been updated (but still needs to be published).
