### ISSUE TITLE
Add uninstall to make rules

### ISSUE THREAD

**Issue by cryptism** [Martchus/syncthingtray#70]
Not really a "feature", just that when trying to install this when building from source, I found out that I couldn't uninstall when I had placed it in the wrong directory, which left me having to pick through everything that was on my system. Happy to swing a PR with an additional makefile rule your way, if you think it's appropriate.

**Comment by Martchus** [comment]
The is a CMake project and we usually "don't do that here". But I can nevertheless implement an uninstall target according to: https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake

This FAQ also mentions a simple alternative: 
```
xargs rm < install_manifest.txt
```

Note that this is likely implemented best on `c++utilities` level.

**Comment by cryptism** [comment]
Yeah that is a heap simpler, wish I had thought of it at the time.

Interesting, thanks for the info on CMake. Based on that I'm happy to close since it's clear there's little need to address this for more seasoned users.
