### ISSUE TITLE
No Fedora 31/32 packages on OBS?

### ISSUE THREAD

**Issue by Skirmisher** [Martchus/syncthingtray#72]
I'm interested in using syncthingtray (it looks quite nice!), but the build service does not provide packages for Fedora 32. What's strange is that you build for F28, F29, and F30, all three of which are EOL, while leaving out the currently-maintained releases. Is there some issue with 31 and 32 preventing it from being packaged properly?

**Comment by Martchus** [comment]
I enabled Fedora 31 and 32 repos. Most packages seem to build.

**Comment by Skirmisher** [comment]
Thanks! The application itself is working well here. However, the package seems to be missing the Plasmoid and Dolphin integration—I only see the binary and its associated files in the list of files.

**Comment by Martchus** [comment]
You need to install the packages `syncthingplasmoid` and `syncthingfileitemaction`. (And the CLI would be `syncthingctl`.)

**Comment by Skirmisher** [comment]
Ahh, I see. Seems like it should be documented in the readme section that links to OBS, since the subpackages are not exposed anywhere in the OBS interface, besides viewing `syncthingtray.spec` directly.
