### ISSUE TITLE
Automatic connection and first-try connection do not succeed

### ISSUE THREAD

**Issue by trajanmcgill** [Martchus/syncthingtray#73]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* syncthingtray: 0.11.1
* Qt version: 5.15.0
* Operating system (name and version): Windows 10

**Bug description**
 * "Connect automatically on startup" appears not to work, and selecting an instance to connect to takes two tries to work.
This may be one bug or two. I also am not sure if it is actually failing to connect, or just failing to display that it is connected.

**Steps to reproduce**
1. Set up syncthingtray and configure with a single connection. Select "Connect automatically on startup" and "Start the tray icon when the desktop environment launches".
2. Reboot and log onto Windows.
3. Tray icon appears, but remains gray.
4. Right-click on tray icon, select "Connection", and choose the connection configured in step 1.
5. Icon remains gray / disconnected.
6. [optional] Wait a minute just to make sure it isn't an issue of lag.
7. Right-click on tray icon, select "Connection", and a second time choose the connection configured in step 1.
8. Icon changes to green / connected.

**Expected behavior**
1. Connection to occur on startup, as configured.
2. Connection to occur the first time connection is selected rather than the second.

**Additional context**
Thanks for producing this useful tool!

**Comment by Martchus** [comment]
Admittedly that's something I don't test as I usually use the built-in launcher (and built-in Syncthing library).

According to the mentioned steps you're launching Syncthing externally relying on the "Connect automatically on startup" feature. I'll have to cross-check whether it is broken when I have time. Note that this feature will not try to re-connect automatically when it is not possible to connect. You will need to configure the reconnect interval additionally to make that work. I'm just mentioning it because the steps to reproduce don't contain that configuration and depending on how you start Syncthing it might just not be up on the first connection attempt.

**Comment by Martchus** [comment]
Also be sure not to use "Consider process status for reconnect attempts to local instance" under launcher settings when not actually using the built-in launcher as this will override the "Connect automatically on startup" setting (when I remember correctly).

**Comment by Martchus** [comment]
I've just tested it under Windows with an externally launched instance. I started Syncthing Tray first to ensure the first-try connection does not succeed. I get an error notification as expected and also further error notifications on further connection attempts configured via the reconnect interval. When finally launching Syncthing itself it successfully connects on the next attempt.

Looks like in your case Syncthing isn't even responding in step 5 and only after waiting a minute. Note that it can sometimes take some time until Syncthing is not just running but actually responding to HTTP requests (although a minute seems a bit long unless a database update is performed).

**Comment by trajanmcgill** [comment]
Correct, I am launching Syncthing externally, but I am doing so with the Windows Task Scheduler at startup (not at logon) so it really ought to be running by the time Syncthing Tray launches and tries to connect. I'll try a little more experimentation to see at what step the failure to connect is actually occurring.

**Comment by trajanmcgill** [comment]
Worth noting here is that I upgraded from 0.11.1 a few days ago to 1.1.0 (and Syncthing from 1.8.0 to 1.12.0 at the same time), and it seems as though this problem may have gone away.

**Comment by Martchus** [comment]
I'm not aware of any commit since 0.11.1 which would (intentionally) fix this so I'm not sure whether the update is related. Since I can not reproduce/pin-down the problem myself I still don't know how to help.

**Comment by trajanmcgill** [comment]
Then I'm guessing maybe it was a race condition of some kind somewhere between syncthingtray and Syncthing itself, and I'm not sure if something solved it inadvertently or if it just no longer happens to occur in my setup with later version launch times maybe being slightly different. I'm okay with closing the issue and can report if I ever see it again.
