### ISSUE TITLE
Add option to sort folders by name rather than by ID

### ISSUE THREAD

**Issue by tomasz1986** [Martchus/syncthingtray#75]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [x] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**

No.

**Is your feature request related to a problem? Please describe.**

The folders seem to be listed in the order of their ID rather than name. As such, this makes it very difficult to find a specific one when there are a lot of folders.

**Describe the solution you'd like**

It would be nice to have an option to sort folders by their name rather than ID.

**Describe alternatives you've considered**

The ugly workaround is to manually modify each folder's ID including its name in it, which would then tie the ID to the name.

**Additional context**

**Comment by Martchus** [comment]
It never occurred to me because I never folder labels because I find it weird to have 2 names for the same thing. Maybe I neverthless spend the effort at some point. It is definitely a valid feature request.

I personally would like to sort the folders manually because at a certain amount of folders the list gets quite cluttered and it would be nice to have important folders at the top. Maybe pinning folders to the top would also make sense. I mention this because when implementing the this issue it would make sense to keep these use-cases in mind.

**Comment by tomasz1986** [comment]
> It never occurred to me because I never folder labels because I find it weird to have 2 names for the same thing.

Do you use only IDs then? Do you set them manually on folder creation? By default, Syncthing creates each ID using a random mix of xxxx-xxxx numbers and letters, so just by looking at it, it is impossible to know, which folder is which. I have 30+ folders on this device, so trying to figure out each of them by its ID would be a nightmare :wink:. Unless I tie the ID to the name, but then the problem is, what to do if you want to change the name later? Changing the ID itself requires setting the whole folder synchronisation from scratch again.

**Comment by Martchus** [comment]
Yes. I indeed keep the folder label blank and replace the cryptic default-ID with something meaningful (following a certain pattern). I never had the need to change the ID afterwards.

Note that the list is currently not even sorted by ID. It is just the order the directories appear in the JSON document from Syncthing's API. So I guess I should really improve this.

**Comment by tomasz1986** [comment]
> Note that the list is currently not even sorted by ID. It is just the order the directories appear in the JSON document from Syncthing's API.

The JSON document seems to be sorted alphabetically then, because the IDs are definitely listed from `0` to `9`, and then from `a` to `z`. I think that https://github.com/syncthing/syncthing/issues/6985 is probably somewhat related.

**Comment by Martchus** [comment]
> The JSON document seems to be sorted alphabetically then

Right. The one folder which looked "out of place" was actually also using a label and one of those generated IDs.

---

I've implemented this now. I didn't make it an option because it is quite unlikely that someone really only wants to sort by ID despite having labels.

**Comment by tomasz1986** [comment]
I can confirm that the folders are now all sorted alphabetically when tested in the development build. Thank you very much for the quick fix.

**Comment by tomasz1986** [comment]
I am sorry for reviving the already closed issue, but I have just noticed that devices are also listed in an irregular order. Would it be possible to have them also follow the alphabetical order?

**Comment by Martchus** [comment]
I've already assumed that this would be the next thing to come up. Of course it would be possible. I guess that's one of the next things I'd like to improve.
