### ISSUE TITLE
Add an option to disable scanning/syncing icon overlays

### ISSUE THREAD

**Issue by tomasz1986** [Martchus/syncthingtray#76]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**

No.

**Is your feature request related to a problem? Please describe.**

Right now, it is possible to switch on and off the following notifications.

![image](https://user-images.githubusercontent.com/5626656/96396661-aad12580-1202-11eb-9064-031672deec7d.png)

I think that it would be also useful to have a tick box to disable scanning and syncing notifications all together. The reason is that when having tons of folders and devices, there is syncing and scanning going on basically all the time. This makes the icon go back and forth changing its status constantly, which becomes distracting very quickly.

In addition to the above, personally I am more interested whether Syncthing is actually running rather than what specifically is happening at the moment (especially considering the aforementioned situation with a large number of folders and devices). In this case, the icon serves mainly a purpose to confirm that Syncthing is on and doing its job, and also to give a warning when something brakes.
 
**Describe the solution you'd like**

I would like to have a switch to disable syncthing/scanning notifications, and thus have only a static icon displayed, except for when something else happens, e.g. a disconnect or an error.

**Describe alternatives you've considered**

I do not think that there is any alternative right now, apart maybe from a hack to override the default scanning/syncing icon overlays with transparent or empty icons.

**Additional context**

![image](https://user-images.githubusercontent.com/5626656/96397158-dd2f5280-1203-11eb-8dd7-0fe89fd48710.png)

**Comment by Martchus** [comment]
> I would like to have a switch to disable syncthing/scanning notifications

Note that with "notifications" a popup like this speech bubble is meant: https://doc.qt.io/qt-5/qsystemtrayicon.html#details  
But from your further descriptions I assume you're actually talking about the icon itself. That's something which is indeed not configurable at all so far. I suppose this setting actually fall under the "Icons" tab where I'd add another column to show/hide the "extra bubble" at the bottom-right corner.

**Comment by tomasz1986** [comment]
Hmm, you are actually right. I thought that the icon was meant by "notifications", the reason being that I have actually not seen any speech bubbles from Syncthing Tray. I have now enabled all notifications, but still there is nothing other than the icon change e.g. when a device disconnects or a sync completes.

These are my settings, and the OS is Windows 10.

![image](https://user-images.githubusercontent.com/5626656/96430996-dd4c4400-123d-11eb-8fed-0b1e4335649c.png)

**Comment by Martchus** [comment]
For me the notifications work on Windows 10. Maybe they are blocked/hidden by some notification setting of Windows itself in your case.

> when a device disconnects

There's no notification for that. The "disconnect" checkbox refers to a disconnect by the tray application from Syncthing's REST API.

The styling on your screenshots looks a bit odd as well. It looks like the "Windows" style. Did you select that intentionally or did the "WindowsVista" style not work for you? I'm just asking because that relates to the platform integration plugin which is also responsible for the notifications.

**Comment by tomasz1986** [comment]
> There's no notification for that. The "disconnect" checkbox refers to a disconnect by the tray application from Syncthing's REST API.

This is what I meant. I am sorry for the wording. I meant a state when Syncthing has been shut down, and the address specified in the configuration is inaccessible.

> The styling on your screenshots looks a bit odd as well. It looks like the "Windows" style. Did you select that intentionally or did the "WindowsVista" style not work for you? I'm just asking because that relates to the platform integration plugin which is also responsible for the notifications.

Yes, I am using a high-contrast theme, but the system itself has a lot of group policies set too, so I will try testing this on a clean Windows installation and come back with the results soon.

**Comment by Martchus** [comment]
The current release allows to disable this within the connection settings. You can now choose for each connection configuration what information should be considered to compute the overall status. In your case you would uncheck everything.

**Comment by tomasz1986** [comment]
Thank you very much. Although I must say that I have got kind of used to the icons and simply do not notice them anymore 😉. Still, I have tested the newest version and everything seems to work as supposed.

The issue can be closed now, right?
