### ISSUE TITLE
Approximate sync completion percentages in Devices to integer numbers

### ISSUE THREAD

**Issue by tomasz1986** [Martchus/syncthingtray#81]
**Relevant components**
* [x] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [x] Backend libraries

**Is your feature request specific to a certain platform/environment? Please specify.**

No.

**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Currently, the percentages under "Directories" seem to be approximated to integer numbers. However, the percentages under "Devices" are not. Unless there is a specific reason, I believe that it would be better to have the percentages under "Devices" approximated as well.

**Describe alternatives you've considered**

No alternatives exist.

**Additional context**

![image](https://user-images.githubusercontent.com/5626656/102304073-eccadd80-3f9f-11eb-8da9-1479c98f7ee3.png)

![image](https://user-images.githubusercontent.com/5626656/102304077-ee94a100-3f9f-11eb-81e0-46c5401f2437.png)

**Comment by Martchus** [comment]
Implemented in 75c0f5b.
