### ISSUE TITLE
Plasmoid does not remember color settings

### ISSUE THREAD

**Issue by janprzy** [Martchus/syncthingtray#82]
**Relevant components**
* [x] Plasmoid/applet for Plasma desktop

**Environment and versions**
* Versions: syncthingtray` 1.1.0, `qtutilities` 6.3.2 and `c++utilities` 5.9.0 (installed from the [AUR](https://aur.archlinux.org/packages/syncthingtray/))
* Qt version: 5.15.2
* KDE Plasma 5.20.4 with KDE Frameworks 5.77.0
* Operating system (name and version): Arch Linux, Kernel 5.9.14

**Bug description**
I have set the Syncthing icon to appear white. However, sometimes (I haven't found a pattern yet) it uses the default black color instead. When this happens, going into the Plasmoid's settings (the ones accessible by right-clicking on the icon) and re-applying them makes the icon return  to the correct colors.

**Expected behavior**
The icon should always use the correct color theme.

**Screenshots**
![Screenshot_2020-12-18 _22:07:07](https://user-images.githubusercontent.com/41625296/102662083-66b8bd80-417e-11eb-90ed-ca807a497d81.png)

**Comment by Martchus** [comment]
That's strange. I'm using the same environment and haven't noticed this bug so far.

Note that the black version is actually not the default. The default is the set of colors where idle is green and most of the other states blue.

The only explanation I can think of is that multiple processes write to the settings file (under `~/.config/syncthingtray.ini`) which is also shared with the Qt Widgets based version. In this case the process does the last save wins.

**Comment by janprzy** [comment]
I don't I'm experiencing this issue anymore, so I'm closing it for now. Will reopen if it happens again.
