### ISSUE TITLE
Settings windows are tranparent

### ISSUE THREAD

**Issue by HTOgit** [Martchus/syncthingtray#90]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [x] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Syncthingtray 1.1.3 from AUR
* Qt version: 5.15.2
* C++ compiler (name and version): …
* C++ standard library (name and version): …
* Operating system (name and version): Manjaro with all updates

**Bug description**
Syncthing's settings menu and release note are transparent. I am observing the problem on three computers, all of which run Manjaro with the latest KDE.

**Steps to reproduce**
1. start it

**Screenshots**
![grafik](https://user-images.githubusercontent.com/59915584/112304861-4bd67780-8c9e-11eb-9692-bdad2fd9a933.png)

**Comment by Martchus** [comment]
I can not reproduce this problem. Which Plasma style and Qt Widgets style are you using? I suspect that some styling from the shell itself is inherited by the UI of the Plasmoid's dialogs.

**Comment by Martchus** [comment]
Judging from the window title I assume you're using latte-dock. Even when using that it looks good here.

Note that colors are generally taken from your environments palette (as detected by Qt). So this might be caused by some color being transparent in your palette.

**Comment by HTOgit** [comment]
Hi,

yes on this PC I'm using Latte and Arc-KDE-Theme. With Breeze it's working fine:/

**Comment by Martchus** [comment]
I can not reproduce it using the latest release of Arc (Plasma theme and Kvantum style).

**Comment by Martchus** [comment]
I've been able to reproduce a similar bug with the Lightly style and with default color scheme which comes with it. In my case it helps to switch between the tabs. So far I'm not sure whether the bug is on my side or within the style.
