### ISSUE TITLE
Support signature validation of AppImage via AppImageLauncher

### ISSUE THREAD

**Issue by akwala** [Martchus/syncthingtray#91]
**Relevant components**
* [ ] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ ] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries
* [x] Installation/update

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: syncthingtray-1.1.4-Build39.1.glibc2.17-x86_64.AppImage, …, …
* Qt version: 5.12.8
* C++ compiler (name and version): …
* C++ standard library (name and version): …
* Operating system (name and version): Kubuntu 20.04

(Will provide missing info if relevant.)

**Bug description**
When verifying downloaded file, AppImageLauncher complains that AppImage is not signed.

**Steps to reproduce**
1. Right-click SyncthingTray launcher in the application menu.
2. Select 'Update AppImage'.
3. In AppImageLauncher dialog, check the option to remove old version after update.

**Expected behavior**
AppImageLauncher installs the new version and removes the old one.

**Screenshots**
![image](https://user-images.githubusercontent.com/1786/113917859-bfed4100-97af-11eb-8e7c-d74e1fe622d2.png)

**Additional context**

**Comment by Martchus** [comment]
This never worked. A signature for the AppImage is simply not provided so far. I have never used/tested AppImageLauncher so this is not supported at this point and I'm not sure whether it is worth it. Looks like the tool consumes the repository maintained via OBS directly. Not sure how or whether I can improve this considering it may be a limitation of OBS.

Note that this ticket is almost a duplicate of https://github.com/Martchus/syncthingtray/issues/88 so see my comment there.

**Comment by Martchus** [comment]
Oh, and "Qt version: 5.12.8" in the ticket description makes me laugh. I hope you're aware that the AppImage can not use the system-provided Qt for the sake of compatibility. It actually uses the good old Qt 5.6 (which I blame for any bugs only reproducible within the AppImage).

**Comment by akwala** [comment]
> This never worked. A signature for the AppImage is simply not provided so far. I have never used/tested AppImageLauncher so this is not supported at this point and I'm not sure whether it is worth it. Looks like the tool consumes the repository maintained via OBS directly. Not sure how or whether I can improve this considering it may be a limitation of OBS.

May be possible to disable/suppress the Update AppImage item in the launcher's context-menu. The [digiKam](https://www.digikam.org/download/) launcher, for instance doesn't have it.
