### ISSUE TITLE
How to remove from Autostart (Plasma)?

### ISSUE THREAD

**Issue by frumble** [Martchus/syncthingtray#96]
I have installed and set up this tool but I would prefer to not have it in autostart mode on my KDE Plasma. I cannot find any option to disable autostart and it isn’t in the Plasma system settings for autostart either. How can I disable autostarting?

**Comment by Martchus** [comment]
The autostart settings say:

> This is achieved by adding a *.desktop file under <i>~/.config/autostart</i> so the setting only affects the current user.

This is undone when unchecking the checkbox within the autostart settings. If it doesn't work your can of course delete the file manually.

If there's no file at this location the autostart is configured differently in your case (and not using any feature of Syncthing Tray itself). Hence the problem would be out of scope.

Note that the Plasmoid is either configured to be shown within the panel or not. Hence there are no autostart settings when using the Plasmoid. Additionally, the Plasmoid can be configured to be shown as part of the system tray Plasmoid. If you had configured that and don't want it anymore you have to look within the settings of the system tray Plasmoid.

**Comment by frumble** [comment]
Thanks. So, there is no file in ~/.config/autostart for the Plasmoid. It appears to be part of the systray. Where exactly should I look for the setting for "show as part of the system tray"? I cannot find it in the applet’s settings and not in the Plasma settings window for the systray too.

**Comment by Martchus** [comment]
It should be in the settings of the system tray Plasmoid. I can create a screenshot tomorrow.

**Comment by Martchus** [comment]
![Screenshot_20210621_232327](https://user-images.githubusercontent.com/10248953/122829762-b3c14c00-d2e7-11eb-89ab-8fc523bc06e6.png)

![Screenshot_20210621_232151](https://user-images.githubusercontent.com/10248953/122829645-8d9bac00-d2e7-11eb-9da6-95afafe4e5ca.png)

**Comment by frumble** [comment]
Thanks, that worked!
