### ISSUE TITLE
libboost_filesystem.so version error

### ISSUE THREAD

**Issue by blueorignal** [Martchus/syncthingtray#98]
**Relevant components**
* [X ] Standalone tray application (based on Qt Widgets)
* [ ] Plasmoid/applet for Plasma desktop
* [ ] Dolphin integration
* [ X] Command line tool (`syncthingctl`)
* [ ] Integrated Syncthing instance (`libsyncthing`)
* [ ] Backend libraries

**Environment and versions**
* Versions of `syncthingtray`, `qtutilities` and `c++utilities`: 1.1.8-1 6.4.2-1 5.10.5-1
* Qt version: 5.15.2
* C++ compiler (name and version): gcc 11.1.0-1
* C++ standard library (name and version): gcc-libs 11.1.0-1
* Operating system (name and version): …Manjaro KDE 5.22.3 running LTS kernel 5.10

**Bug description**
After the latest update on Manjaro Linux, syncthingtray launches with the following error:

syncthingtray: error while loading shared libraries: libboost_filesystem.so.1.75.0: cannot open shared object file: No such file or directory

**Steps to reproduce**
1. Launch syncthingtray from terminal
2. Error is displayed

**Expected behavior**
syncthingtray should load normally and place the associated icon in the task bar.

**Additional context**
- The current version of libboost is 1.76.0.
- syncthing itself launches and runs normally from the command line.

**Comment by Martchus** [comment]
Recompile it against the new Boost version. I will bump pkgrel if that's necessary but only in accordance with Arch Linux. When using Manjaro you're on your own (and also cannot use my binary repository directly).

**Comment by blueorignal** [comment]
Thank you for the feedback
